#!/usr/bin/env python3
"""
build.py - assemble the bob explainer films from docs/manim/parts/.

    python3 docs/manim/build.py           write every episode that has a part file
    python3 docs/manim/build.py --list    show the series and what exists

Each episode is emitted TWICE, from the same source:

    docs/manim/<name>.py      one self-contained %%manim cell (paste into a notebook)
    docs/manim/<name>.ipynb   the same cell, ready to open in Colab / Jupyter

Same pattern as docs/arch/build.py and docs/project/build.py: parts in, one
finished artefact out, nothing hand-edited in the output.
"""

import argparse
import ast
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
PARTS = os.path.join(HERE, "parts")

# episode -> (part file, the class that plays the whole episode, title, subtitle)
EPISODES = [
    ("ep01_clb",     "Ep01CLB",     "The CLB",
     "which bit goes where, and why"),
    ("ep02_jtag",    "Ep02JTAG",    "JTAG",
     "the TAP, the instruction register, the boundary ring"),
    ("ep03_config",  "Ep03Config",  "The configuration engine",
     "one memory, two write paths, and the startup that gates them"),
    # planned, see README.md:
    ("ep04_io",      "Ep04IO",      "I/O, pads and the clock", ""),
    ("ep05_bram",    "Ep05BRAM",    "BRAM", ""),
    ("ep06_dsp",     "Ep06DSP",     "DSP", ""),
    ("ep07_routing", "Ep07Routing", "Routing", ""),
    ("ep08_yosys",   "Ep08Yosys",   "Synthesis with yosys", ""),
    ("ep09_vpr",     "Ep09VPR",     "VPR and place-and-route", ""),
    ("ep10_bitgen",  "Ep10Bitgen",  "Bitstream generation", ""),
    ("ep11_flow",    "Ep11Flow",    "The whole flow, by hand and by tool", ""),
    ("ep12_novelty", "Ep12Novelty", "What is ours: bob against OpenFPGA and Aegis", ""),
    ("ep13_errors",  "Ep13Errors",  "Every error we hit, and the rule it became", ""),
]

HEADER = """%%manim -qm {main}
# =============================================================================
#  bob, explained - EPISODE {num}: {title}
#  {sub}
#
#  GENERATED by docs/manim/build.py from docs/manim/parts/. Do not edit here.
#
#  Prerequisite (once per notebook, in a cell of its own):
#      !pip install manim
#      from manim import *
#
#  Quality on the magic line above:  -ql draft   -qm medium   -qh 1080p60
#
#  Render one section instead of the whole episode by putting any of these
#  class names on the magic line:
{targets}
# =============================================================================

"""


def sections(src):
    """the per-section Scene classes in an episode part, in file order"""
    return [n.name for n in ast.parse(src).body
            if isinstance(n, ast.ClassDef) and re.match(r"E\d\dS\d", n.name)]


def build(one=None):
    prelude = open(os.path.join(PARTS, "prelude.py")).read()
    made, missing = [], []
    for i, (name, main, title, sub) in enumerate(EPISODES, start=1):
        path = os.path.join(PARTS, f"{name}.py")
        if not os.path.exists(path):
            missing.append((i, name, title))
            continue
        if one and one not in (name, main):
            continue
        body = open(path).read()
        targets = "\n".join(f"#      {s}" for s in sections(body)) or "#      (none)"
        cell = HEADER.format(main=main, num=i, title=title,
                             sub=sub or title, targets=targets) + prelude + "\n" + body

        py = os.path.join(HERE, f"{name}.py")
        open(py, "w").write(cell)

        lines = cell.rstrip("\n").split("\n")
        md = {"cell_type": "markdown", "metadata": {}, "source": [
            f"# bob, explained - Episode {i}: {title}\n", "\n",
            (sub or title) + "\n", "\n",
            "Run `!pip install manim` and `from manim import *` once first, then this "
            "cell. Start at `-ql`; the class names listed at the top of the cell render "
            "a single section.\n"]}
        code = {"cell_type": "code", "execution_count": None, "metadata": {},
                "outputs": [], "source": [l + "\n" for l in lines[:-1]] + [lines[-1]]}
        nb = {"cells": [md, code], "metadata": {
                "kernelspec": {"display_name": "Python 3", "language": "python",
                               "name": "python3"},
                "language_info": {"name": "python", "version": "3"}},
              "nbformat": 4, "nbformat_minor": 5}
        json.dump(nb, open(os.path.join(HERE, f"{name}.ipynb"), "w"), indent=1)

        # the cell body (everything after the magic line) must be valid Python
        ast.parse("\n".join(lines[1:]))
        made.append((i, name, main, len(lines), len(sections(body))))

    for i, name, main, n, s in made:
        print(f"  E{i:02d}  {name+'.py':22s} {main:14s} {n:5d} lines, {s} sections")
    if missing:
        print("\n  not written yet:")
        for i, name, title in missing:
            print(f"  E{i:02d}  {name:22s} {title}")
    return made


NB_INTRO = [
    "# bob, explained\n", "\n",
    "An FPGA built inside an FPGA, taken apart one topic at a time.\n", "\n",
    "**Run the first two cells once.** After that each episode is a single cell: run it and "
    "its video appears inline.\n", "\n",
    "The magic line carries the quality (`-ql` draft, `-qm` medium, `-qh` 1080p60) and the "
    "scene to render. Every episode cell lists its section classes in a comment at the top - "
    "put one of those on the magic line to re-watch a single idea instead of the whole "
    "episode.\n", "\n",
    "| # | episode |\n", "|---|---|\n",
]


def notebook():
    """one notebook, one cell per episode (prelude in its own setup cell)"""
    prelude = open(os.path.join(PARTS, "prelude.py")).read()

    def code_cell(src):
        lines = src.rstrip("\n").split("\n")
        return {"cell_type": "code", "execution_count": None, "metadata": {},
                "outputs": [], "source": [l + "\n" for l in lines[:-1]] + [lines[-1]]}

    intro = list(NB_INTRO)
    cells, n = [], 0
    for i, (name, main, title, sub) in enumerate(EPISODES, start=1):
        path = os.path.join(PARTS, f"{name}.py")
        if not os.path.exists(path):
            continue
        body = open(path).read()
        targets = "\n".join(f"#      {t}" for t in sections(body)) or "#      (none)"
        head = (f"%%manim -qm {main}\n"
                f"# ===========================================================================\n"
                f"#  EPISODE {i}: {title}\n"
                f"#  {sub or title}\n"
                f"#\n"
                f"#  render one section instead, by putting its class on the magic line above:\n"
                f"{targets}\n"
                f"# ===========================================================================\n\n")
        cells.append(code_cell(head + body))
        intro.append(f"| {i} | **{title}** - {sub or ''} |\n")
        n += 1

    nb = {"cells": [
            {"cell_type": "markdown", "metadata": {}, "source": intro},
            code_cell("!pip install manim"),
            code_cell("# run once: palette, helpers and the BobScene base class\n"
                      "# every episode cell below uses these\n\n" + prelude),
          ] + cells,
          "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3"}},
          "nbformat": 4, "nbformat_minor": 5}
    out = os.path.join(HERE, "bob_explained.ipynb")
    json.dump(nb, open(out, "w"), indent=1)
    print(f"  bob_explained.ipynb    {n} episode cells + 2 setup cells")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("episode", nargs="?", help="build just this one (ep01_clb or Ep01CLB)")
    ap.add_argument("--list", action="store_true")
    a = ap.parse_args()
    if a.list:
        for i, (name, main, title, sub) in enumerate(EPISODES, start=1):
            mark = "x" if os.path.exists(os.path.join(PARTS, f"{name}.py")) else " "
            print(f"  [{mark}] E{i:02d}  {title:45s} {name}")
        return
    build(a.episode)
    if not a.episode:
        notebook()


if __name__ == "__main__":
    main()
