#!/usr/bin/env python3
"""
Generate hw/tb/cfg_vectors.vh for hw/tb/tb_cfg.v.

Every CRC in the file comes from tools/bob/chainbits.py, not from the Verilog,
so the testbench checks cfg_ctrl.v's CRC against an independent implementation
(which is itself checked against the published CRC-32C check value by pytest).
"""

import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "tools", "bob"))

from chainbits import crc32c_bits  # noqa: E402

W = 64                      # cfg_test_top: 4 tiles x 16 bits
MASK = (1 << W) - 1


def h64(v):
    return f"64'h{v & MASK:016x}"


def h32(v):
    return f"32'h{v:08x}"


def main():
    rng = random.Random(0xC0FF1E)
    out = [
        "// hw/tb/cfg_vectors.vh - GENERATED by sim/gen_cfg_vectors.py, do not edit.",
        "// CRCs from tools/bob/chainbits.py (CRC-32C, docs/bitstream-format.md s5).",
        "",
    ]

    start = (rng.getrandbits(W) & ~0b111) | 0b101      # LD2..0 = 101 after startup
    out.append(f"`define STARTUP_WORD {h64(start)}")
    out.append(f"`define STARTUP_CRC  {h32(crc32c_bits(start, W))}")
    out.append("")

    k = rng.getrandbits(W)
    out.append(f"    vec_key_guard({h64(k)}, {h32(crc32c_bits(k, W))});")

    goods = [0, MASK, 0xAAAA_AAAA_AAAA_AAAA, 1, 1 << (W - 1)] + [rng.getrandbits(W) for _ in range(6)]
    for g in goods:
        out.append(f"    vec_good({h64(g)}, {h32(crc32c_bits(g, W))});")

    for bit in (0, W - 1, rng.randrange(W), rng.randrange(W)):
        w = rng.getrandbits(W)
        out.append(f"    vec_corrupt({h64(w ^ (1 << bit))}, {h32(crc32c_bits(w, W))});"
                   f"   // bit {bit} flipped")

    # Length guard in isolation: the expected CRC is correct for the bits that
    # are actually shifted (63 of them, or 65 = word<<1), so ONLY the length
    # check can reject. (A first version used the 64-bit CRC, which let a
    # mutant with the length check deleted pass - caught by mutation testing.)
    w = rng.getrandbits(W)
    out.append(f"    vec_len({h64(w)}, {h32(crc32c_bits(w & ((1 << (W - 1)) - 1), W - 1))}, "
               f"{h32(crc32c_bits(w << 1, W + 1))});")
    w = rng.getrandbits(W)
    out.append(f"    vec_hold({h64(w)}, {h32(crc32c_bits(w, W))});")

    path = os.path.normpath(os.path.join(HERE, "..", "hw", "tb", "cfg_vectors.vh"))
    with open(path, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {path}  ({len(goods)} good, 4 corrupt, 1 length, 1 hold)")


if __name__ == "__main__":
    main()
