// GENERATED by software/bob/golden.py from build/synth/counter/counter.json - do not edit
module counter_golden (
    input wire clk,
    input wire [1:0] sw,
    input wire [3:0] btn,
    output wire [2:0] led
);
    wire n2;
    wire n3;
    wire n4;
    wire n5;
    wire n6;
    wire n7;
    wire n8;
    wire n9;
    wire n10;
    wire n11;
    wire n12;
    wire n13;
    wire n14;
    wire n15;
    wire n16;
    wire n17;
    wire n18;
    wire n19;
    wire n20;
    wire n21;
    wire n22;
    wire n23;
    wire n24;
    wire n25;
    wire n26;
    assign n2 = clk;
    assign n3 = sw[0];
    assign n4 = sw[1];
    assign n5 = btn[0];
    assign n6 = btn[1];
    assign n7 = btn[2];
    assign n8 = btn[3];
    // $auto$alumacc.cc:548:replace_alu$16.slice[0].add
    BOB_ADD #(.INV_B(1'h0)) c0 (.A(1'b1), .B(n12), .CI(1'b0), .O(n14), .CO(n13));
    // $auto$alumacc.cc:548:replace_alu$16.slice[1].add
    BOB_ADD #(.INV_B(1'h0)) c1 (.A(1'b0), .B(n15), .CI(n13), .O(n17), .CO(n16));
    // $auto$alumacc.cc:548:replace_alu$16.slice[2].add
    BOB_ADD #(.INV_B(1'h0)) c2 (.A(1'b0), .B(n18), .CI(n16), .O(n20), .CO(n19));
    // $auto$alumacc.cc:548:replace_alu$16.slice[3].add
    BOB_ADD #(.INV_B(1'h0)) c3 (.A(1'b0), .B(n9), .CI(n19), .O(n22), .CO(n21));
    // $auto$alumacc.cc:548:replace_alu$16.slice[4].add
    BOB_ADD #(.INV_B(1'h0)) c4 (.A(1'b0), .B(n10), .CI(n21), .O(n24), .CO(n23));
    // $auto$alumacc.cc:548:replace_alu$16.slice[5].add
    BOB_ADD #(.INV_B(1'h0)) c5 (.A(1'b0), .B(n11), .CI(n23), .O(n26), .CO(n25));
    // $auto$ff.cc:337:slice$94
    BOB_FDRE #(.INIT(1'h0)) c6 (.C(n2), .CE(n5), .R(n6), .D(n14), .Q(n12));
    // $auto$ff.cc:337:slice$95
    BOB_FDRE #(.INIT(1'h0)) c7 (.C(n2), .CE(n5), .R(n6), .D(n17), .Q(n15));
    // $auto$ff.cc:337:slice$96
    BOB_FDRE #(.INIT(1'h0)) c8 (.C(n2), .CE(n5), .R(n6), .D(n20), .Q(n18));
    // $auto$ff.cc:337:slice$97
    BOB_FDRE #(.INIT(1'h0)) c9 (.C(n2), .CE(n5), .R(n6), .D(n22), .Q(n9));
    // $auto$ff.cc:337:slice$98
    BOB_FDRE #(.INIT(1'h0)) c10 (.C(n2), .CE(n5), .R(n6), .D(n24), .Q(n10));
    // $auto$ff.cc:337:slice$99
    BOB_FDRE #(.INIT(1'h0)) c11 (.C(n2), .CE(n5), .R(n6), .D(n26), .Q(n11));
    assign led[0] = n9;
    assign led[1] = n10;
    assign led[2] = n11;
endmodule
