// bd_demo_bd_wrapper.v - generated by bob from bd/bd_demo_bd.bd.
// Do not edit: Generate wrapper in bob studio (or bd.py generate) rewrites it.
module bd_demo_bd_wrapper (
    input  wire       clk,
    input  wire [1:0] sw,
    input  wire [3:0] btn,
    output wire [2:0] led
);

    wire cnt__en;
    wire cnt__clr;
    wire [1:0] cnt__q;
    wire [1:0] mux__a;
    wire [1:0] mux__b;
    wire mux__sel;
    wire [1:0] mux__y;
    wire press__d;
    wire press__rise;
    wire press__fall;
    wire tog__t;
    wire tog__q;

    assign cnt__en = sw[1];
    assign cnt__clr = btn[0];
    assign mux__a = cnt__q;
    assign mux__b = btn[2:1];
    assign mux__sel = sw[0];
    assign led[1:0] = mux__y;
    assign press__d = btn[3];
    assign tog__t = press__rise;
    assign led[2] = tog__q;

    ip_counter #(.W(2)) cnt (
        .clk(clk),
        .en(cnt__en),
        .clr(cnt__clr),
        .q(cnt__q)
    );

    ip_mux2 #(.W(2)) mux (
        .a(mux__a),
        .b(mux__b),
        .sel(mux__sel),
        .y(mux__y)
    );

    ip_edge_detect press (
        .clk(clk),
        .d(press__d),
        .rise(press__rise),
        .fall(press__fall)
    );

    ip_toggle tog (
        .clk(clk),
        .t(tog__t),
        .q(tog__q)
    );

endmodule
