#!/usr/bin/env python3
"""
golden.py - the golden netlist of a synthesised design (M10).

  golden.write(mod, top) -> Verilog text of module <top>_golden

yosys' own simulation netlist (<top>_syn.v) renames every cell and most nets, so
nothing inside it can be matched to a fabric location. This writes the same
netlist (build/synth/<top>/<top>.json) with one named wire per yosys bit, n<bit>,
and the cell models of tools/bob/synth/bob_cells_sim.v. tools/bob/equiv.py
simulates it next to the source Verilog: its outputs must equal the source's, and
the value of every n<bit> after each clock edge is saved in <top>.trace.json
("nets" / "nets_after"). tools/bob/vpr_run.py records which yosys bit every VPR
net carries, so a CLB's output - its flip-flop - on the fabric (CAPTURE) can be
compared with the golden value of that bit.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _bit(b):
    if isinstance(b, int):
        return f"n{b}"
    return "1'b1" if b == "1" else "1'b0"          # x / z read 0, as everywhere in bob


def _bus(bits):
    """a port connection, MSB first"""
    if len(bits) == 1:
        return _bit(bits[0])
    return "{" + ", ".join(_bit(b) for b in reversed(bits)) + "}"


def _pval(v, width):
    if isinstance(v, str) and set(v) <= set("01xz"):
        v = int(v.replace("x", "0").replace("z", "0"), 2)
    return f"{width}'h{int(v):x}"


def nets(mod):
    """every yosys bit id in the module, sorted"""
    out = set()
    for p in mod["ports"].values():
        out.update(b for b in p["bits"] if isinstance(b, int))
    for c in mod["cells"].values():
        for bits in c["connections"].values():
            out.update(b for b in bits if isinstance(b, int))
    return sorted(out)


def write(mod, top):
    ports = mod["ports"]
    L = [f"// GENERATED by tools/bob/golden.py from build/synth/{top}/{top}.json - do not edit",
         f"module {top}_golden ("]
    decl = []
    for name, p in ports.items():
        w = len(p["bits"])
        rng = f"[{w - 1}:0] " if w > 1 else ""
        decl.append(f"    {'input' if p['direction'] == 'input' else 'output'} wire {rng}{name}")
    L.append(",\n".join(decl))
    L.append(");")
    driven = set()
    for b in nets(mod):
        L.append(f"    wire n{b};")
    for name, p in ports.items():
        for i, b in enumerate(p["bits"]):
            sel = f"{name}[{i}]" if len(p["bits"]) > 1 else name
            if p["direction"] == "input" and isinstance(b, int):
                L.append(f"    assign n{b} = {sel};")
                driven.add(b)
    for k, (cname, c) in enumerate(sorted(mod["cells"].items())):
        t, conn, par = c["type"], c["connections"], c["parameters"]
        L.append(f"    // {cname.replace(ROOT + '/', '')}")
        if t == "$lut":
            w = int(str(par["WIDTH"]), 2) if isinstance(par["WIDTH"], str) else int(par["WIDTH"])
            L.append(f"    BOB_LUT #(.K({w}), .INIT({_pval(par['LUT'], 64)})) c{k} "
                     f"(.I({_bus(conn['A'])}), .O({_bit(conn['Y'][0])}));")
        elif t in ("BOB_FDRE", "BOB_FDSE"):
            rst = "R" if t == "BOB_FDRE" else "S"
            init = _pval(par.get("INIT", "1" if t == "BOB_FDSE" else "0"), 1)
            L.append(f"    {t} #(.INIT({init})) c{k} (.C({_bit(conn['C'][0])}), .CE({_bit(conn['CE'][0])}), "
                     f".{rst}({_bit(conn[rst][0])}), .D({_bit(conn['D'][0])}), .Q({_bit(conn['Q'][0])}));")
        elif t == "BOB_ADD":
            L.append(f"    BOB_ADD #(.INV_B({_pval(par.get('INV_B', 0), 1)})) c{k} (.A({_bit(conn['A'][0])}), "
                     f".B({_bit(conn['B'][0])}), .CI({_bit(conn['CI'][0])}), .O({_bit(conn['O'][0])}), "
                     f".CO({_bit(conn['CO'][0])}));")
        elif t == "BOB_BRAM18":
            pins = ", ".join(f".{p}({_bus(conn[p])})" for p in sorted(conn))
            L.append(f"    BOB_BRAM18 #(.WMODE_A({_pval(par.get('WMODE_A', 1), 2)}), "
                     f".WMODE_B({_pval(par.get('WMODE_B', 1), 2)}), .INIT({_pval(par.get('INIT', 0), 18432)})) "
                     f"c{k} ({pins});")
        elif t == "BOB_DSP":
            pins = ", ".join(f".{p}({_bus(conn[p])})" for p in sorted(conn))
            L.append(f"    BOB_DSP c{k} ({pins});")
        else:
            raise ValueError(f"{cname}: cell type {t} has no golden model")
    for name, p in ports.items():
        if p["direction"] == "output":
            for i, b in enumerate(p["bits"]):
                sel = f"{name}[{i}]" if len(p["bits"]) > 1 else name
                L.append(f"    assign {sel} = {_bit(b)};")
    L.append("endmodule")
    return "\n".join(L) + "\n"
