#!/usr/bin/env python3
"""
report.py - what each example uses and how it was built (M11 design reports).

  tools/bob/report.py [--out docs/reports/M11/designs.md]

From committed data only (no Docker, no board): the yosys cell counts, VPR's packed
blocks, wirelength and critical path, the FASM features and routing muxes the chain
sets, the chain CRC, and how many registers CAPTURE can compare. Board results
are in docs/hwtest/results.log.
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "host"))

import bitstream as B  # noqa: E402
import equiv  # noqa: E402
import fasm_from_vpr as FV  # noqa: E402
import synth  # noqa: E402
import vpr_run  # noqa: E402
from chainbits import crc32c_bits  # noqa: E402


def rows():
    out = []
    for name in vpr_run.EXAMPLES + list(vpr_run.VARIANTS):
        top, pcf = vpr_run.VARIANTS.get(name, (name, None))
        ok, _lines, mod = equiv.equiv([os.path.join(ROOT, "examples", f"{top}.v")], top)
        bs, contents, text = FV.build(name)
        d = os.path.join(vpr_run.RESULTS, name)
        net = open(os.path.join(d, f"{name}.net")).read()
        stamp = vpr_run.read_stamp(name)
        feats = text.splitlines()
        out.append({
            "name": name, "equiv": ok,
            "cells": synth.summary(mod),
            "clb": net.count('instance="clb['), "bram": net.count('instance="bram['),
            "dsp": net.count('instance="dsp['),
            "pins": os.path.relpath(pcf, ROOT) if pcf else "default",
            "wirelength": stamp["wirelength"], "cpd": stamp["cpd_ns"],
            "features": len(feats), "muxes": sum(1 for f in feats if f.startswith("rr")),
            "registers": len(FV.capture_map(name)),
            "crc": f"0x{crc32c_bits(bs.to_int(), B.CHAIN_W):08X}",
            "result": stamp["result_sha"],
        })
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "reports", "M11", "designs.md"))
    args = ap.parse_args()
    R = rows()
    nclb = len(B.CLBS)
    L = ["# M11 design reports",
         "",
         f"Device `{B.DEVICE['name']}`: {nclb} CLBs, {B.NBRAM} BRAMs, {B.NDSP} DSP slices, {B.NPAD} pads, "
         f"{B.CHAIN_W}-bit chain, {len(B.MUX)} routing muxes. Generated by `tools/bob/report.py` from the "
         "committed VPR results (`tools/bob/vpr/`); board results are in `docs/hwtest/results.log`.",
         "",
         "| design | yosys cells | CLBs | BRAM | DSP | pins | wirelength | VPR critical path* | FASM features "
         "(routing muxes) | registers on CAPTURE | chain CRC | VPR result |",
         "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in R:
        cells = ", ".join(f"{k} {v}" for k, v in r["cells"].items())
        L.append(f"| {r['name']} | {cells} | {r['clb']}/{nclb} | {r['bram']} | {r['dsp']} | {r['pins']} | "
                 f"{r['wirelength']} | {float(r['cpd']):.2f} ns | {r['features']} ({r['muxes']}) | "
                 f"{r['registers']} | `{r['crc']}` | `{r['result']}` |")
    L += ["",
          "\\* VPR's timing model uses the reference architecture's 40 nm delays; it is not the speed of "
          "the fabric emulated on the XC7Z020 (set by the host's routing-loop paths, M7 timing notes).",
          ""]
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    open(args.out, "w").write("\n".join(L))
    print(f"wrote {os.path.relpath(args.out, ROOT)}: {len(R)} designs")
    return 0 if all(r["equiv"] for r in R) else 1


if __name__ == "__main__":
    sys.exit(main())
