#!/usr/bin/env python3
"""
Generate hw/tb/vectors.vh from host/designs.py, host/bitstream.py,
tools/bob/model.py and tools/bob/chainbits.py.

Each design is built by the real bitstream engine; combinational expected
outputs come from bitstream.simulate(), sequential ones (M4: routed CE/SR, the
carry-chain counter) from tools/bob/model.py - never from the Verilog. Every
chain carries its CRC-32C and is loaded through the configuration plane
(JPROGRAM, expected CRC, CFG_IN, JSTART), exactly as host/cfgplane.py does.

  ./gen_vectors.py [--out FILE]      honours BOB_DEVICE_JSON (K=4 runs)
"""

import argparse
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "host"))
sys.path.insert(0, os.path.join(HERE, "..", "tools", "bob"))

from bitstream import simulate, FABRIC_CFG_W, LUT_K                       # noqa: E402
from chainbits import crc32c_bits                                        # noqa: E402
from designs import (DESIGNS, BY_KEY, SKIPPED, BRAM_JTAG_VARIANTS, DSP_JTAG_VARIANTS,  # noqa: E402
                     d_gsr_probe, d_ce_sr, d_counter, d_bram_rom, d_bram_jtag,
                     d_dsp_jtag, d_dsp_mult_sw, d_dsp_accum)
import model                                                             # noqa: E402

W = FABRIC_CFG_W
CE_SR_STEPS = (0b00, 0b01, 0b11, 0b01, 0b00, 0b10, 0b01, 0b00)


def hexw(v):
    return f"{W}'h{v:0{(W + 3) // 4}x}"


def crc(v):
    return f"32'h{crc32c_bits(v, W):08x}"


def define(name, word):
    return [f"`define {name}_WORD {hexw(word)}", f"`define {name}_CRC {crc(word)}"]


def loop_free_random_chain(rng):
    import bitstream as B
    word = rng.getrandbits(W)
    nsrc = len(B.SOURCES)
    for t in B.DEVICE["tiles"]:
        if t["type"] != "clb":
            continue
        for f in B.DEVICE["tile_types"]["clb"]["fields"]:
            if f["kind"] != "mux":
                continue
            lo = t["chain_lo"] + f["offset"]
            val = rng.randrange(nsrc, 1 << f["width"])
            word = (word & ~(((1 << f["width"]) - 1) << lo)) | (val << lo)
    return word


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.normpath(
        os.path.join(HERE, "..", "hw", "tb", "vectors.vh")))
    args = ap.parse_args()

    out = [
        "// hw/tb/vectors.vh - GENERATED by sim/gen_vectors.py, do not edit.",
        "//",
        f"// LUT K = {LUT_K}, chain {W} bits. Bitstreams from host/bitstream.py,",
        "// expected outputs from its software model / tools/bob/model.py, CRCs from",
        "// tools/bob/chainbits.py.",
        "",
    ]

    show_bs = BY_KEY["showcase"][1]().build()
    ce_sr_bs = d_ce_sr().build()
    cntj_bs = d_counter("jtag").build()
    cntr_bs = d_counter("run", 0).build()
    other = BY_KEY["three"][1]().build().to_int()

    out += ["// chain round trip: a random pattern whose routing muxes all select an",
            "// out-of-range source (20..31 reads const 0), so committing it cannot build a",
            "// combinational loop - a fully random chain can, and a zero-delay oscillation",
            "// hangs the simulator (it did at M4)."]
    out += define("RT", loop_free_random_chain(random.Random(0xF00D)))
    out += ["// one registered tile, INIT 1, D 0 (designs.d_gsr_probe)"]
    out += define("GSR", d_gsr_probe().build().to_int())
    out += ["// showcase, and a corrupted 'three' chain carrying its true CRC"]
    out += define("SHOW", show_bs.to_int())
    out += [f"`define BAD_WORD {hexw(other ^ (1 << 1234))}", f"`define BAD_CRC {crc(other)}"]
    out += ["// M4: routed CE/SR; 4-bit carry-chain counter, JTAG-stepped and free-running"]
    out += define("CE_SR", ce_sr_bs.to_int())
    out += define("CNTJ", cntj_bs.to_int())
    out += define("CNTR", cntr_bs.to_int())
    out.append("")

    # --- combinational designs ---------------------------------------------------
    out += ["task run_designs;", "begin"]
    total = 0
    for key, desc, fn, sweep in DESIGNS:
        bs = fn().build()
        word = bs.to_int()
        out.append(f"    // ---- {key}: {desc}")
        out.append(f'    dname  = "{key}: {desc}";')
        out.append(f"    cfgw   = {hexw(word)};")
        out.append(f"    cfgcrc = {crc(word)};")
        out.append("    load_config;")
        for v in sweep:
            out.append(f"    check_vec(6'b{v:06b}, 3'b{simulate(bs, v):03b});")
            total += 1
        out.append("    finish_design;")
        out.append("")
    out += ["end", "endtask", "", "task check_showcase;", "begin"]
    for v in BY_KEY["showcase"][2]:
        out.append(f"    check_vec(6'b{v:06b}, 3'b{simulate(show_bs, v):03b});")
    out += ["end", "endtask", ""]

    # --- routed CE/SR sequence (model.py) -------------------------------------------
    m = model.Fabric(ce_sr_bs)
    m.clock(gsr=1)
    out += ["task run_ce_sr;", "begin"]
    for v in CE_SR_STEPS:
        for _ in range(4):
            m.clock(pad_i=v)
        out.append(f"    ce_sr_step(6'b{v:06b}, 3'b{m.outputs(v):03b});")
    out += ["end", "endtask", ""]

    # --- routed CE/SR through INTEST autostep, as host/hwtest.py drives it ------------
    m = model.Fabric(ce_sr_bs)
    m.clock(gsr=1)
    out += ["task run_ce_sr_intest;", "begin"]
    for v in (0b00, 0b01, 0b11, 0b01, 0b00, 0b10, 0b01):
        m.clock(pad_i=v)
        out.append(f"    intest_step(6'b{v:06b}, 1'b{m.outputs(v) & 1});")
        m.clock(pad_i=v)
    out += ["end", "endtask", ""]

    # --- counter sequence (model.py) -------------------------------------------------
    m = model.Fabric(cntj_bs)
    m.clock(gsr=1)
    out += ["task init_cnt_seq;", "begin"]
    for n in range(16):
        state = sum(m.q[(r, 0)] << r for r in range(4))
        out.append(f"    cnt_state[{n}] = 4'b{state:04b}; cnt_pad[{n}] = 3'b{m.outputs(0, cin=1):03b};")
        m.clock(cin=1)
    out += ["end", "endtask", ""]

    # --- M5: BRAM ROM through the fabric (model.py) ----------------------------------
    rng_b = random.Random(0xB5)
    rom_bs = d_bram_rom().build()
    rom_words = [rng_b.getrandbits(18) for _ in range(4)]
    out += define("ROM", rom_bs.to_int())
    out += [f"`define ROM{i} 18'h{w:05x}" for i, w in enumerate(rom_words)]
    m = model.Fabric(rom_bs)
    m.clock(gsr=1)
    for i, w in enumerate(rom_words):
        m.bram.mem[i] = w
    out += ["task rom_check;", "begin"]
    for v in range(4):
        for _ in range(3):
            m.clock(pad_i=v)
        out.append(f"    rom_vec(6'b{v:06b}, 3'b{m.outputs(v):03b});")
    out += ["end", "endtask", ""]

    # --- M5: BRAM write modes / output registers, pins driven over JTAG ----------------
    idle = {"addr": 0, "di": 0, "we": 0, "en": 0, "rst": 0, "regce": 0}
    for name, v in BRAM_JTAG_VARIANTS:
        bs = d_bram_jtag(**v).build()
        out += define(name, bs.to_int())
        cfg = {"wmode_a": model.WRITE_MODES[v["wmode_a"]], "wmode_b": model.WRITE_MODES[v["wmode_b"]],
               "reg_a": int(v["reg_a"]), "reg_b": int(v["reg_b"])}
        bm = model.Bram()
        bm.clock(cfg, {"a": idle, "b": idle}, gsr=1)
        out += [f"task {name.lower()}_run;", "begin"]
        for addr in range(8):
            w = rng_b.getrandbits(18)
            bm.init(True, addr, w)
            out.append(f"    bram_poke(10'd{addr}, 18'h{w:05x});")
        out.append("    jstart;")
        for a, b in model.bram_random_ops(rng_b, 24):
            bm.clock(cfg, {"a": a, "b": b}, gce=1)
            out.append(f"    bram_op(64'h{model.pins_to_drive(a, b):016x}, "
                       f"18'h{bm.do('a', cfg):05x}, 18'h{bm.do('b', cfg):05x});")
        out += ["end", "endtask", ""]

    # --- M6: DSP tile ------------------------------------------------------------------
    M48 = (1 << 48) - 1
    zero = {"a": 0, "b": 0, "c": 0, "d": 0, **{n: 0 for n in model.DSP_CTRL_NAMES}}
    rng_d = random.Random(0xD6)
    for name, c0, c1 in DSP_JTAG_VARIANTS:
        bs = d_dsp_jtag(c0, c1).build()
        out += define(name, bs.to_int())
        cfgs = model.Fabric(bs).dsp_cfgs
        slices = [model.Dsp(), model.Dsp()]
        out += [f"task {name.lower()}_run;", "begin", "    jstart;"]
        for p0, p1 in model.dsp_random_ops(rng_d, 20):
            model.dsp_cascade_clock(slices, cfgs, (p0, p1))
            e0, e1 = model.dsp_cascade_p(slices, cfgs, (p0, p1))
            out.append(f"    dsp_op(248'h{model.dsp_pins_to_drive(p0, p1):062x}, "
                       f"48'h{e0 & M48:012x}, 48'h{e1 & M48:012x});")
        out += ["end", "endtask", ""]

    mult_bs = d_dsp_mult_sw().build()
    out += define("MULT", mult_bs.to_int())
    fm = model.Fabric(mult_bs)
    fm.dsp_drive = model.dsp_pins_to_drive({**zero, "b": 3}, zero)
    out.append(f"`define MULT_DRIVE 248'h{fm.dsp_drive:062x}")
    out += ["task mult_check;", "begin"]
    for v in range(4):
        out.append(f"    mult_vec(6'b{v:06b}, 3'b{fm.outputs(v):03b});")
    out += ["end", "endtask", ""]

    out += define("ACC", d_dsp_accum(0).build().to_int())
    out.append(f"`define ACC_DRIVE 248'h{model.dsp_pins_to_drive({**zero, 'a': 1, 'b': 1}, zero):062x}")
    out.append("")

    with open(args.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {args.out}")
    print(f"  {len(DESIGNS)} designs, {total} vectors, {W} bits each, with CRC-32C"
          + (f"  (skipped at K={LUT_K}: {', '.join(SKIPPED)})" if SKIPPED else ""))


if __name__ == "__main__":
    main()

