/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000101) */

module counter(clk, sw, btn, led);
  input clk;
  wire clk;
  input [1:0] sw;
  wire [1:0] sw;
  input [3:0] btn;
  wire [3:0] btn;
  output [2:0] led;
  wire [2:0] led;
  wire [6:0] _00_;
  wire [5:0] _01_;
  wire [5:0] q;
  BOB_ADD #(
    .INV_B(1'h0)
  ) _02_ (
    .A(1'h1),
    .B(q[0]),
    .CI(1'h0),
    .CO(_00_[1]),
    .O(_01_[0])
  );
  BOB_ADD #(
    .INV_B(1'h0)
  ) _03_ (
    .A(1'h0),
    .B(q[1]),
    .CI(_00_[1]),
    .CO(_00_[2]),
    .O(_01_[1])
  );
  BOB_ADD #(
    .INV_B(1'h0)
  ) _04_ (
    .A(1'h0),
    .B(q[2]),
    .CI(_00_[2]),
    .CO(_00_[3]),
    .O(_01_[2])
  );
  BOB_ADD #(
    .INV_B(1'h0)
  ) _05_ (
    .A(1'h0),
    .B(led[0]),
    .CI(_00_[3]),
    .CO(_00_[4]),
    .O(_01_[3])
  );
  BOB_ADD #(
    .INV_B(1'h0)
  ) _06_ (
    .A(1'h0),
    .B(led[1]),
    .CI(_00_[4]),
    .CO(_00_[5]),
    .O(_01_[4])
  );
  BOB_ADD #(
    .INV_B(1'h0)
  ) _07_ (
    .A(1'h0),
    .B(led[2]),
    .CI(_00_[5]),
    .CO(_00_[6]),
    .O(_01_[5])
  );
  BOB_FDRE #(
    .INIT(1'h0)
  ) _08_ (
    .C(clk),
    .CE(btn[0]),
    .D(_01_[0]),
    .Q(q[0]),
    .R(btn[1])
  );
  BOB_FDRE #(
    .INIT(1'h0)
  ) _09_ (
    .C(clk),
    .CE(btn[0]),
    .D(_01_[1]),
    .Q(q[1]),
    .R(btn[1])
  );
  BOB_FDRE #(
    .INIT(1'h0)
  ) _10_ (
    .C(clk),
    .CE(btn[0]),
    .D(_01_[2]),
    .Q(q[2]),
    .R(btn[1])
  );
  BOB_FDRE #(
    .INIT(1'h0)
  ) _11_ (
    .C(clk),
    .CE(btn[0]),
    .D(_01_[3]),
    .Q(led[0]),
    .R(btn[1])
  );
  BOB_FDRE #(
    .INIT(1'h0)
  ) _12_ (
    .C(clk),
    .CE(btn[0]),
    .D(_01_[4]),
    .Q(led[1]),
    .R(btn[1])
  );
  BOB_FDRE #(
    .INIT(1'h0)
  ) _13_ (
    .C(clk),
    .CE(btn[0]),
    .D(_01_[5]),
    .Q(led[2]),
    .R(btn[1])
  );
  assign _00_[0] = 1'h0;
  assign q[5:3] = led;
endmodule
