#!/usr/bin/env python3
"""
Generate hw/tb/clb_vectors.vh for hw/tb/tb_clb.sv - the M4 CLB flag sweep.

For all 128 combinations of the seven CLB flags, with two random INITs each,
a sequence of cycles with random LUT inputs, carry-in, routed CE and SR, and
the global gce / GSR / GWE. Expected outputs come from software/bob/model.py, so
the testbench checks clb.sv against the model every cycle.

  ./gen_clb_vectors.py [--out FILE]      honours BOB_DEVICE_JSON (K=4 runs)
"""

import argparse
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "software", "bob"))
sys.path.insert(0, os.path.join(HERE, "..", "software", "host"))

import bitstream as B  # noqa: E402
import model as M      # noqa: E402

STEPS = 7


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.normpath(
        os.path.join(HERE, "..", "hw", "tb", "clb_vectors.vh")))
    args = ap.parse_args()

    K, W = B.LUT_K, B.CLB_CFG_W
    rng = random.Random(0xC1B)
    out = [
        "// hw/tb/clb_vectors.vh - GENERATED by sim/gen_clb_vectors.py, do not edit.",
        f"// LUT K = {K}, CLB config {W} bits; expected values from software/bob/model.py.",
        "",
    ]
    n = 0
    for combo in range(1 << len(M.FLAGS)):
        f = {name: (combo >> j) & 1 for j, name in enumerate(M.FLAGS)}
        for _ in range(2):
            init = rng.getrandbits(1 << K)
            cfg = init
            for name in M.FLAGS:
                cfg |= f[name] << B.FIELD[name][0]
            q = None
            for s in range(STEPS):
                i = rng.getrandbits(K)
                cin, ce, sr = rng.getrandbits(1), rng.getrandbits(1), rng.getrandbits(1)
                if s == 0:
                    gsr, gce, gwe = 1, rng.getrandbits(1), 0      # establish q = INIT
                else:
                    gsr = 1 if rng.random() < 0.08 else 0
                    gce = 1 if rng.random() < 0.8 else 0
                    gwe = 1 if rng.random() < 0.85 else 0
                _o6, o5, comb, cout = M.clb_comb(init, f, i, cin)
                known = not (f["ff_en"] and q is None)
                o_pre = (q if f["ff_en"] else comb) if known else 0
                q = M.clb_next(q if q is not None else 0, f, comb, ce, sr, gce, gsr, gwe)
                o_post = q if f["ff_en"] else comb
                out.append(f"    step({W}'h{cfg:x}, {K}'b{i:0{K}b}, {cin}, {ce}, {sr}, "
                           f"{gce}, {gsr}, {gwe}, {o_pre}, {int(known)}, {o5}, {cout}, {o_post});")
                n += 1
    with open(args.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {args.out}  ({n} cycles, K={K})")


if __name__ == "__main__":
    main()
