#!/usr/bin/env python3
"""
Generate hw/tb/dsp_vectors.vh for hw/tb/tb_dsp.v - dsp_core.v against
software/bob/model.py's Dsp.

Every opmode x use_d x d_sub, with random register configurations, random
signed inputs (including full-scale corners), random CE/RST, gce and the odd
GSR. Two slices are simulated as a cascade (slice 1 PCIN = slice 0 P), so the
PCIN>>17 path is exercised with real data.
"""

import argparse
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "software", "bob"))

import model as M  # noqa: E402

CORNERS = {25: [0, 1, -1, (1 << 24) - 1, -(1 << 24)], 18: [0, 1, -1, (1 << 17) - 1, -(1 << 17)],
           48: [0, 1, -1, (1 << 47) - 1, -(1 << 47)]}


def rand_s(rng, w):
    if rng.random() < 0.2:
        return rng.choice(CORNERS[w])
    return rng.randrange(-(1 << (w - 1)), 1 << (w - 1))


def h(v, w):
    return f"{w}'h{v & ((1 << w) - 1):0{(w + 3) // 4}x}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.normpath(
        os.path.join(HERE, "..", "hw", "tb", "dsp_vectors.vh")))
    args = ap.parse_args()

    rng = random.Random(0xD5B)
    out = ["// hw/tb/dsp_vectors.vh - GENERATED by sim/gen_dsp_vectors.py, do not edit.", ""]
    n = 0
    s0, s1 = M.Dsp(), M.Dsp()

    def cfg_bits(c):
        return (c["opmode"] | c["use_d"] << 2 | c["d_sub"] << 3 | c["areg"] << 4 | c["breg"] << 5
                | c["creg"] << 6 | c["dreg"] << 7 | c["mreg"] << 8 | c["preg"] << 9)

    def ctrl_bits(pins):
        return sum(pins[name] << k for k, name in enumerate(M.DSP_CTRL_NAMES))

    for op in range(4):
        for use_d in (0, 1):
            for d_sub in (0, 1):
                for rep in range(3):
                    cfgs = []
                    for _ in range(2):
                        c = {"opmode": op, "use_d": use_d, "d_sub": d_sub}
                        for r in ("areg", "breg", "creg", "dreg", "mreg", "preg"):
                            c[r] = rng.getrandbits(1)
                        cfgs.append(c)
                    for step in range(14):
                        pins = []
                        for _ in range(2):
                            p = {"a": rand_s(rng, 25), "b": rand_s(rng, 18), "c": rand_s(rng, 48),
                                 "d": rand_s(rng, 25)}
                            for name in M.DSP_CTRL_NAMES:
                                prob = 0.08 if name.startswith("rst") else 0.8
                                p[name] = int(rng.random() < prob)
                            pins.append(p)
                        gsr = 1 if step == 0 else int(rng.random() < 0.03)
                        gce = int(rng.random() < 0.85)
                        # cascade: slice 1 PCIN is slice 0's P output before the edge
                        p0_pre = s0.p(cfgs[0], pins[0], 0)
                        s0.clock(cfgs[0], pins[0], 0, gce=gce, gsr=gsr)
                        s1.clock(cfgs[1], pins[1], p0_pre, gce=gce, gsr=gsr)
                        p0 = s0.p(cfgs[0], pins[0], 0)
                        p1 = s1.p(cfgs[1], pins[1], p0)
                        out.append(
                            f"    step({h(cfg_bits(cfgs[0]), 10)}, {h(cfg_bits(cfgs[1]), 10)}, "
                            + ", ".join(f"{h(pins[i]['a'], 25)}, {h(pins[i]['b'], 18)}, "
                                        f"{h(pins[i]['c'], 48)}, {h(pins[i]['d'], 25)}, "
                                        f"{h(ctrl_bits(pins[i]), 8)}" for i in range(2))
                            + f", {gce}, {gsr}, {h(p0, 48)}, {h(p1, 48)});")
                        n += 1
    with open(args.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {args.out}  ({n} cycles, 2 cascaded slices)")


if __name__ == "__main__":
    main()
