#!/usr/bin/env python3
"""Generate build/mux/tb_mux.v: hw/src/fabric/bob_mux.v (LUT6/MUXF7/MUXF8 primitives, M23)
against the behavioural table it replaced, for every width up to 40 inputs, with and without
const1, over every select value (including those past the last input) and random inputs.

tb_bob only meets the muxes this fabric has (at 10 x 10 at most 14 values, select width 4),
so the wide branch (16:1 groups picked on sel[W-1:4]) is exercised here.
"""
import os
import sys

OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), "..", "build", "mux", "tb_mux.v")
REF = '''module bob_mux_ref #(parameter integer N = 2, parameter integer W = 2, parameter integer C1 = 0)(
    input wire [W-1:0] sel, input wire [N-1:0] in, output wire o);
    wire [(1<<W):0] tab;
    generate
        if (C1 != 0) begin : g_c1
            assign tab = {{((1<<W) + 1 - N - 2){1'b0}}, in, 1'b1, 1'b0};
        end else begin : g_c0
            assign tab = {{((1<<W) + 1 - N - 1){1'b0}}, in, 1'b0};
        end
    endgenerate
    assign o = tab[{1'b0, sel}];
endmodule
'''


def main():
    cases = [(n, c) for c in (0, 1) for n in range(1, 41)]
    w = lambda n, c: max(1, (n + c).bit_length())            # noqa: E731  (2**W >= N + 1 + C1)
    L = ["// GENERATED by sim/gen_mux_tb.py, do not edit", "`timescale 1ns/1ps", REF, "module tb_mux;",
         "integer errs = 0, checks = 0, k, s;"]
    for i, (n, c) in enumerate(cases):
        L.append(f"reg [{w(n, c) - 1}:0] s{i}; reg [{n - 1}:0] in{i}; wire o{i}, r{i};")
        L.append(f"bob_mux #(.N({n}), .W({w(n, c)}), .C1({c})) d{i} (.sel(s{i}), .in(in{i}), .o(o{i}));")
        L.append(f"bob_mux_ref #(.N({n}), .W({w(n, c)}), .C1({c})) f{i} (.sel(s{i}), .in(in{i}), .o(r{i}));")
    L.append("initial begin")
    for i, (n, c) in enumerate(cases):
        L.append(f"  for (k = 0; k < 64; k = k + 1) for (s = 0; s < {1 << w(n, c)}; s = s + 1) begin "
                 f"in{i} = {{$random, $random}}; s{i} = s; #1; checks = checks + 1; "
                 f"if (o{i} !== r{i}) begin errs = errs + 1; if (errs < 10) "
                 f"$display(\"  FAIL  N={n} C1={c} sel=%0d: %b, want %b\", s, o{i}, r{i}); end end")
    L.append(f'  $display("=== bob_mux (LUT6/MUXF7/MUXF8) vs the behavioural table: {len(cases)} sizes ===");')
    L.append('  $display("    %0d checks", checks);')
    L.append('  if (errs == 0) $display("=== ALL TESTS PASSED ==="); else $display("=== %0d CHECK(S) FAILED ===", errs);')
    L.append("  $finish;")
    L.append("end")
    L.append("endmodule")
    os.makedirs(os.path.dirname(os.path.abspath(OUT)), exist_ok=True)
    open(OUT, "w").write("\n".join(L) + "\n")


if __name__ == "__main__":
    main()
