#!/usr/bin/env python3
"""
Generate hw/tb/frame_vectors.vh for hw/tb/tb_frames.v (M13): packet streams from
software/bob/packets.py, and every expected STAT, memory and LED value from its
Controller model, software/bob/model.py and software/host/bitstream.py - never from the RTL.

  ./gen_frame_vectors.py
"""

import os
import random
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "software", "host"))
sys.path.insert(0, os.path.join(HERE, "..", "software", "bob"))

import bitstream as B                    # noqa: E402
import packets as P                      # noqa: E402
from chainbits import crc32c_bits        # noqa: E402
from designs import PARTIAL_Q, d_showcase, d_counter, d_partial  # noqa: E402

W = B.CHAIN_W
# stream vector width in the testbench (TB_SW): a whole load of the chain plus packet overhead
SW = 4096 * ((W + W // 16 + 4096) // 4096 + 1)


def hexw(v, w=W):
    return f"{w}'h{v:0{(w + 3) // 4}x}"


def chunked(lines, limit=8000, piece=2048):
    """iverilog's scanner holds at most 16 KB of one token (a `define of a 64k-bit vector is
    16 400 characters): a wide constant becomes a function that assigns it piece by piece,
    and the macro calls the function"""
    out = []
    for line in lines:
        m = re.fullmatch(r"`define (\w+) (\d+)'h([0-9a-fA-F]+)", line)
        if not m or len(line) <= limit:
            out.append(line)
            continue
        name, w, digits = m.group(1), int(m.group(2)), m.group(3)
        v = int(digits, 16)
        out.append(f"function [{w - 1}:0] f_{name}(input dummy);")
        out.append("    begin")
        out.append(f"        f_{name} = {w}'h0;")
        for lo in range(0, w, piece):
            n = min(piece, w - lo)
            part = (v >> lo) & ((1 << n) - 1)
            if part:
                out.append(f"        f_{name}[{lo} +: {n}] = {n}'h{part:x};")
        out.append("    end")
        out.append("endfunction")
        out.append(f"`define {name} f_{name}(1'b0)")
    return out


def stream(name, words):
    n, v = P.to_jtag(words)
    assert n <= SW
    return [f"`define {name}_N {n}", f"`define {name}_V {hexw(v, SW)}"]


def run(words, mem=0, gwe=0, idcode=None):
    c = P.Controller(idcode=idcode, mem=mem)
    c.gwe = gwe
    c.shift_in(*P.to_jtag(words))
    return c


def main():
    out = ["// hw/tb/frame_vectors.vh - GENERATED by sim/gen_frame_vectors.py, do not edit.", "",
           f"`define TB_SW {SW}",
           f"`define SHOW_CRC 32'h{crc32c_bits(d_showcase().build().to_int(), W):08x}",
           f"`define TB_IDCODE 32'h{P.device_idcode():08X}"]
    show = d_showcase().build().to_int()
    cnt = d_counter("jtag").build().to_int()
    out += [f"`define SHOW_W {hexw(show)}", f"`define CNT_W {hexw(cnt)}", f"`define CNT_CRC 32'h{crc32c_bits(cnt, W):08x}"]

    # [1] a good load of showcase
    good = P.load_stream(show)
    c = run(good)
    assert c.mem == show and c.flags["start_ok"]
    out += stream("GOOD", good)
    out += [f"`define GOOD_STAT 32'h{c.stat(gsr=1, gts=1, gwe=0, done=0):08x}"]
    out += [f"`define GOOD_STAT_DONE 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]
    for k, v in enumerate(range(4)):
        out += [f"`define SHOW_PAD{k} 3'b{B.simulate(d_showcase().build(), v) & 7:03b}"]

    # [2] FDRO readback of everything
    rb = P.readback_stream()
    out += stream("RB", rb)
    out += [f"`define RB_WORDS {P.NFRAMES * P.FW}", f"`define RB_EXP {hexw(P.to_jtag(P.frame_words(show))[1], 32 * P.NFRAMES * P.FW)}"]

    # [3] garbage before sync, stream split over three scans
    rng = random.Random(13)
    garbage = [rng.getrandbits(32) & ~0 for _ in range(3)]
    garbage = [g for g in garbage if g != P.SYNC]
    split = garbage + P.load_stream(cnt)
    n, v = P.to_jtag(split)
    n += 5                                             # 5 more garbage bits in front: not word aligned
    v = (v << 5) | 0b10110
    cuts = [0, n // 3 + 7, 2 * n // 3 - 11, n]
    for i in range(3):
        m = cuts[i + 1] - cuts[i]
        out += [f"`define SPLIT{i}_N {m}", f"`define SPLIT{i}_V {hexw((v >> cuts[i]) & ((1 << m) - 1), SW)}"]
    c = P.Controller()
    for i in range(3):
        m = cuts[i + 1] - cuts[i]
        c.shift_in(m, (v >> cuts[i]) & ((1 << m) - 1))
    assert c.mem == cnt and c.flags["start_ok"]
    out += [f"`define SPLIT_STAT 32'h{c.stat():08x}"]

    # [4] one frame-data bit flipped: CRC error, no START
    bad = list(P.load_stream(show))
    i = bad.index(P.type2(P.OP_WRITE, P.NFRAMES * P.FW)) + 1 + 4 * 9 + 2
    bad[i] ^= 1 << 7
    c = run(bad)
    assert c.flags["crc_err"] and not c.flags["start_ok"]
    out += stream("BADCRC", bad) + [f"`define BADCRC_STAT 32'h{c.stat():08x}", f"`define BADCRC_MEM {hexw(c.mem)}"]

    # [5] wrong IDCODE: nothing written
    wid = P.load_stream(show, idcode=0x0BADC0DE)
    c = run(wid)
    assert c.flags["id_err"] and c.mem == 0
    out += stream("BADID", wid) + [f"`define BADID_STAT 32'h{c.stat():08x}"]

    # [6] frames while the design runs (GWE = 1): refused, memory unchanged. The controller
    # state carries over from [1] and [2] (no JPROGRAM in between), as on the board.
    live = P.load_stream(cnt)
    c = P.Controller()
    c.shift_in(*P.to_jtag(good))
    c.shift_in(*P.to_jtag(rb))
    c.gwe = 1
    c.shift_in(*P.to_jtag(live))
    assert c.flags["wr_err"] and c.mem == show
    out += stream("LIVE", live) + [f"`define LIVE_STAT 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]

    # [7] a type-2 header with no type-1 before it
    pkt = [P.DUMMY, P.SYNC, P.type2(P.OP_WRITE, 4), 1, 2, 3, 4]
    c = run(pkt)
    assert c.flags["pkt_err"]
    out += stream("PKT", pkt) + [f"`define PKT_STAT 32'h{c.stat():08x}"]

    # [8] FDRI without WCFG
    nowcfg = [w for w in P.load_stream(show)]
    j = nowcfg.index(P.CMD["WCFG"], nowcfg.index(P.type1(P.OP_WRITE, P.REG["CMD"], 1), 8))
    nowcfg[j] = P.CMD["NULL"]
    c = run(nowcfg)
    assert c.flags["wr_err"] and c.mem == 0
    out += stream("NOWCFG", nowcfg) + [f"`define NOWCFG_STAT 32'h{c.stat():08x}"]

    # [11] no CRC write at all: START must be refused
    nocrc = P.load_stream(show)
    k = nocrc.index(P.type1(P.OP_WRITE, P.REG["CRC"], 1))
    del nocrc[k:k + 2]
    c = run(nocrc)
    assert not c.flags["start_ok"] and not c.errors() and c.mem == show
    out += stream("NOCRC", nocrc) + [f"`define NOCRC_STAT 32'h{c.stat():08x}"]

    # [12] FDRO without RCFG: zeros and WR_ERROR (after [11]'s state)
    norcfg = [w for w in P.readback_stream()]
    k = norcfg.index(P.type1(P.OP_WRITE, P.REG["CMD"], 1))
    del norcfg[k:k + 2]
    # read from a frame with content, so a leak could not pass as zeros
    col = next(cc for cc in P.FRAMES["columns"]
               if any((show >> (P.FB * (cc["base"]) + 32 * w)) & 0xFFFFFFFF for w in range(P.FW)))
    norcfg[norcfg.index(P.type1(P.OP_WRITE, P.REG["FAR"], 1)) + 1] = P.far(col["far_col"])
    c.shift_in(*P.to_jtag(norcfg))
    assert c.flags["wr_err"]
    out += stream("NORCFG", norcfg) + [f"`define NORCFG_STAT 32'h{c.stat():08x}"]

    # [13] M14 partial reconfiguration of a running design: a free-running 4-bit counter
    # up column 1 and a gate on LD1; only the gate's LUT changes (AND -> OR)
    pra = d_partial("and", "run", 0).build().to_int()
    prb = d_partial("or", "run", 0).build().to_int()
    changed = P.changed_frames(pra, prb)
    assert 1 <= len(changed) <= 2, changed
    out += [f"`define PRA_W {hexw(pra)}", f"`define PRB_W {hexw(prb)}",
            "`define PR_Q {" + ", ".join(f"dut.clb_o[{B.CAP_INDEX[c]}]" for c in reversed(PARTIAL_Q)) + "}"]
    prload = P.load_stream(pra)
    c = run(prload)
    assert c.mem == pra and c.flags["start_ok"]
    out += stream("PRLOAD", prload)
    freeze, frames, nfr = P.partial_streams(pra, prb)
    c = P.Controller(mem=pra)
    c.shift_in(*P.to_jtag(prload))
    c.gwe = 1
    c.shift_in(*P.to_jtag(freeze))
    assert c.frozen() and not c.errors()
    out += stream("PRFRZ", freeze) + [f"`define PRFRZ_STAT 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]
    c.shift_in(*P.to_jtag(frames))
    assert c.mem == prb and not c.frozen() and not c.errors()
    out += stream("PRFRM", frames) + [f"`define PRFRM_STAT 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}",
                                      f"`define PR_NFRAMES {nfr}"]
    # M21: readback right after the partial write comes from the BRAM shadow, which must
    # hold design B's frames (the controller model reads the memory itself); the read
    # leaves RCFG set, which [14]'s STAT then includes
    c.shift_in(*P.to_jtag(P.readback_stream()))
    words = [c.read_word(gsr=0, gts=0, gwe=1, done=1) for _ in range(P.NFRAMES * P.FW)]
    assert words == P.frame_words(prb)
    out += [f"`define PRB_RB_EXP {hexw(P.to_jtag(words)[1], 32 * P.NFRAMES * P.FW)}"]
    # [14] (continuing from [13]) a partial with no CRC write: frames land, LFRM refuses,
    # WR_ERROR, the fabric stays frozen
    nfreeze, nframes, _ = P.partial_streams(prb, pra)
    k = nframes.index(P.type1(P.OP_WRITE, P.REG["CRC"], 1))
    del nframes[k:k + 2]
    c.shift_in(*P.to_jtag(nfreeze))
    c.shift_in(*P.to_jtag(nframes))
    assert c.frozen() and c.flags["wr_err"] and c.mem == pra
    out += stream("PRNCF", nfreeze) + stream("PRNC", nframes)
    out += [f"`define PRNC_STAT 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]

    # [15] AGHIGH without a matched IDCODE (right after JPROGRAM): refused, nothing frozen
    noid = [P.DUMMY, P.SYNC, P.NOP] + P.write("CMD", P.CMD["RCRC"]) + P.write("CMD", P.CMD["AGHIGH"]) + [P.NOP]
    c2 = P.Controller()
    c2.shift_in(*P.to_jtag(noid))
    assert c2.flags["wr_err"] and not c2.frozen()
    out += stream("PRNOID", noid) + [f"`define PRNOID_STAT 32'h{c2.stat():08x}"]

    # [16] a fresh load of A, then a partial with a bad CRC: CRC_ERROR, stays frozen
    bfreeze, bframes, _ = P.partial_streams(pra, prb, crc_override=0x12345678)
    c = P.Controller()
    c.shift_in(*P.to_jtag(prload))
    c.gwe = 1
    c.shift_in(*P.to_jtag(bfreeze))
    c.shift_in(*P.to_jtag(bframes))
    assert c.frozen() and c.flags["crc_err"] and c.mem == prb
    out += stream("PRBADF", bfreeze) + stream("PRBAD", bframes)
    out += [f"`define PRBAD_STAT 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]

    # [17] freeze and frames in ONE scan with sysclk stopped (the testbench stops it during
    # long scans): the acknowledgement cannot arrive, so every frame is refused
    c = P.Controller()
    c.shift_in(*P.to_jtag(prload))
    c.gwe = 1
    c.ack = False
    one = P.partial_streams(pra, prb)[0] + P.partial_streams(pra, prb)[1]
    c.shift_in(*P.to_jtag(one))
    assert c.flags["wr_err"] and c.mem == pra
    c.ack = True
    out += stream("PRONE", one) + [f"`define PRONE_STAT 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]

    # [18] M15: BRAM contents as frames (FAR block type 1), before startup: 3 frames of bram0 from
    # frame 3, then 2 frames from bram0's last frame (FAR auto-increment crosses into bram1)
    rng = random.Random(15)
    idc = P.device_idcode()
    d0 = [rng.getrandbits(18) for _ in range(12)]
    d1 = [rng.getrandbits(18) for _ in range(8)]
    brw = [P.DUMMY, P.SYNC, P.NOP] + P.write("CMD", P.CMD["RCRC"]) + P.write("IDCODE", idc)
    brw += P.write("CMD", P.CMD["WCFG"]) + P.write("FAR", P.bram_far(0, 3))
    brw += [P.type1(P.OP_WRITE, P.REG["FDRI"], 12)] + d0
    brw += P.write("FAR", P.bram_far(0, 255)) + [P.type1(P.OP_WRITE, P.REG["FDRI"], 8)] + d1
    crc = 0
    for reg, val in [(P.REG["IDCODE"], idc), (P.REG["CMD"], P.CMD["WCFG"]), (P.REG["FAR"], P.bram_far(0, 3))] + \
            [(P.REG["FDRI"], x) for x in d0] + [(P.REG["FAR"], P.bram_far(0, 255))] + [(P.REG["FDRI"], x) for x in d1]:
        crc = P.crc37(crc, reg, val)
    brw += P.write("CRC", crc) + P.write("CMD", P.CMD["DESYNC"]) + [P.NOP]
    c = P.Controller()
    c.shift_in(*P.to_jtag(brw))
    assert not c.errors() and c.flags["crc_ok"]
    assert c.brams[0][12:24] == d0 and c.brams[0][1020:1024] == d1[:4] and c.brams[1][0:4] == d1[4:]
    out += stream("BRW", brw) + [f"`define BRW_STAT 32'h{c.stat():08x}"]
    for k in range(12):
        out += [f"`define BR0_{k} 18'h{d0[k]:05x}"]
    for k in range(8):
        out += [f"`define BR1_{k} 18'h{d1[k]:05x}"]
    rb = P.bram_readback_stream(0, 255, 2)            # bram0 1020..1023, then bram1 0..3 (all written)
    c.shift_in(*P.to_jtag(rb))
    words = [c.read_word() for _ in range(8)]
    assert words == d1
    out += stream("BRRB", rb) + [f"`define BRRB_EXP {hexw(P.to_jtag(words)[1], 32 * 8)}"]
    out += [f"`define BRRB_STAT 32'h{c.stat():08x}"]

    # [19] a BRAM content frame while the design runs: WR_ERROR, contents unchanged
    live_b = [P.DUMMY, P.SYNC, P.NOP] + P.write("CMD", P.CMD["RCRC"]) + P.write("IDCODE", idc)
    live_b += P.write("CMD", P.CMD["WCFG"]) + P.write("FAR", P.bram_far(0, 3))
    live_b += [P.type1(P.OP_WRITE, P.REG["FDRI"], 4)] + [0x3FFFF] * 4
    c = P.Controller()
    c.shift_in(*P.to_jtag(prload))
    c.gwe = 1
    c.shift_in(*P.to_jtag(live_b))
    assert c.flags["wr_err"]
    out += stream("BRLIVE", live_b) + [f"`define BRLIVE_STAT 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]

    # STAT read stream
    out += stream("RDSTAT", P.read_stream("STAT", 1))
    path = os.path.join(HERE, "..", "hw", "tb", "frame_vectors.vh")
    open(path, "w").write("\n".join(chunked(out)) + "\n")
    print(f"wrote {os.path.normpath(path)}: frame-path scenarios incl. M14 partial reconfiguration, {P.NFRAMES} frames x {P.FW} words")


if __name__ == "__main__":
    main()
