#!/usr/bin/env python3
"""
Generate hw/tb/synth_vectors.vh for hw/tb/tb_synth.v (M8): every example in
examples/ through tools/bob/place.py's flow (yosys -> netlist == source ->
placed/routed -> model == source), then its chain, BRAM contents and the SOURCE
trace for the fabric RTL to be checked against.

  ./gen_synth_vectors.py [--cycles N]
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "host"))
sys.path.insert(0, os.path.join(HERE, "..", "tools", "bob"))

from bitstream import FABRIC_CFG_W   # noqa: E402
from chainbits import crc32c_bits    # noqa: E402
import place                         # noqa: E402

W = FABRIC_CFG_W


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cycles", type=int, default=40, help="trace cycles replayed per design")
    ap.add_argument("--out", default=os.path.normpath(os.path.join(HERE, "..", "hw", "tb", "synth_vectors.vh")))
    args = ap.parse_args()

    out = ["// hw/tb/synth_vectors.vh - GENERATED by sim/gen_synth_vectors.py, do not edit.",
           "// Chains from tools/bob/place.py; expected LEDs from the SOURCE Verilog (tools/bob/equiv.py).",
           "", "task run_synth;", "begin"]
    for top in place.EXAMPLES:
        d, bs, contents, tr = place.flow(top)
        word = bs.to_int()
        cells = {}
        for n, c in d.cells.items():
            cells[n] = c
        out.append(f"    // ---- {top}: {len(d.cells)} CLBs, {len(d.routes)} routed nets")
        out.append(f'    dname  = "{top}";')
        out.append(f"    cfgw   = {W}'h{word:0{(W + 3) // 4}x};")
        out.append(f"    cfgcrc = 32'h{crc32c_bits(word, W):08x};")
        out.append("    commit_config;")
        for b, words in sorted(contents.items()):
            for a, w in enumerate(words):
                if w:
                    out.append(f"    bram_poke(4'd{b}, 10'd{a}, 18'h{w:05x});")
        out.append("    start;")
        for v, before, after in tr["trace"][:args.cycles]:
            out.append(f"    syn_vec(6'b{v:06b}, 3'b{before:03b}, 3'b{after:03b});")
        out.append("    finish_design;")
    out += ["end", "endtask", ""]
    with open(args.out, "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote {args.out}: {len(place.EXAMPLES)} synthesised designs x {args.cycles} clocks")


if __name__ == "__main__":
    main()
