#!/usr/bin/env python3
"""
Generate hw/tb/frame_vectors.vh for hw/tb/tb_frames.v (M13): packet streams from
tools/bob/packets.py, and every expected STAT, memory and LED value from its
Controller model, tools/bob/model.py and host/bitstream.py - never from the RTL.

  ./gen_frame_vectors.py
"""

import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "host"))
sys.path.insert(0, os.path.join(HERE, "..", "tools", "bob"))

import bitstream as B                    # noqa: E402
import packets as P                      # noqa: E402
from chainbits import crc32c_bits        # noqa: E402
from designs import d_showcase, d_counter  # noqa: E402

W = B.CHAIN_W
SW = 16384                               # stream vector width in the testbench


def hexw(v, w=W):
    return f"{w}'h{v:0{(w + 3) // 4}x}"


def stream(name, words):
    n, v = P.to_jtag(words)
    assert n <= SW
    return [f"`define {name}_N {n}", f"`define {name}_V {hexw(v, SW)}"]


def run(words, mem=0, gwe=0, idcode=None):
    c = P.Controller(idcode=idcode, mem=mem)
    c.gwe = gwe
    c.shift_in(*P.to_jtag(words))
    return c


def main():
    out = ["// hw/tb/frame_vectors.vh - GENERATED by sim/gen_frame_vectors.py, do not edit.", "",
           f"`define SHOW_CRC 32'h{crc32c_bits(d_showcase().build().to_int(), W):08x}",
           f"`define TB_IDCODE 32'h{P.device_idcode():08X}"]
    show = d_showcase().build().to_int()
    cnt = d_counter("jtag").build().to_int()
    out += [f"`define SHOW_W {hexw(show)}", f"`define CNT_W {hexw(cnt)}", f"`define CNT_CRC 32'h{crc32c_bits(cnt, W):08x}"]

    # [1] a good load of showcase
    good = P.load_stream(show)
    c = run(good)
    assert c.mem == show and c.flags["start_ok"]
    out += stream("GOOD", good)
    out += [f"`define GOOD_STAT 32'h{c.stat(gsr=1, gts=1, gwe=0, done=0):08x}"]
    out += [f"`define GOOD_STAT_DONE 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]
    for k, v in enumerate(range(4)):
        out += [f"`define SHOW_PAD{k} 3'b{B.simulate(d_showcase().build(), v) & 7:03b}"]

    # [2] FDRO readback of everything
    rb = P.readback_stream()
    out += stream("RB", rb)
    out += [f"`define RB_WORDS {P.NFRAMES * P.FW}", f"`define RB_EXP {hexw(P.to_jtag(P.frame_words(show))[1], 32 * P.NFRAMES * P.FW)}"]

    # [3] garbage before sync, stream split over three scans
    rng = random.Random(13)
    garbage = [rng.getrandbits(32) & ~0 for _ in range(3)]
    garbage = [g for g in garbage if g != P.SYNC]
    split = garbage + P.load_stream(cnt)
    n, v = P.to_jtag(split)
    n += 5                                             # 5 more garbage bits in front: not word aligned
    v = (v << 5) | 0b10110
    cuts = [0, n // 3 + 7, 2 * n // 3 - 11, n]
    for i in range(3):
        m = cuts[i + 1] - cuts[i]
        out += [f"`define SPLIT{i}_N {m}", f"`define SPLIT{i}_V {hexw((v >> cuts[i]) & ((1 << m) - 1), SW)}"]
    c = P.Controller()
    for i in range(3):
        m = cuts[i + 1] - cuts[i]
        c.shift_in(m, (v >> cuts[i]) & ((1 << m) - 1))
    assert c.mem == cnt and c.flags["start_ok"]
    out += [f"`define SPLIT_STAT 32'h{c.stat():08x}"]

    # [4] one frame-data bit flipped: CRC error, no START
    bad = list(P.load_stream(show))
    i = bad.index(P.type2(P.OP_WRITE, P.NFRAMES * P.FW)) + 1 + 4 * 9 + 2
    bad[i] ^= 1 << 7
    c = run(bad)
    assert c.flags["crc_err"] and not c.flags["start_ok"]
    out += stream("BADCRC", bad) + [f"`define BADCRC_STAT 32'h{c.stat():08x}", f"`define BADCRC_MEM {hexw(c.mem)}"]

    # [5] wrong IDCODE: nothing written
    wid = P.load_stream(show, idcode=0x0BADC0DE)
    c = run(wid)
    assert c.flags["id_err"] and c.mem == 0
    out += stream("BADID", wid) + [f"`define BADID_STAT 32'h{c.stat():08x}"]

    # [6] frames while the design runs (GWE = 1): refused, memory unchanged. The controller
    # state carries over from [1] and [2] (no JPROGRAM in between), as on the board.
    live = P.load_stream(cnt)
    c = P.Controller()
    c.shift_in(*P.to_jtag(good))
    c.shift_in(*P.to_jtag(rb))
    c.gwe = 1
    c.shift_in(*P.to_jtag(live))
    assert c.flags["wr_err"] and c.mem == show
    out += stream("LIVE", live) + [f"`define LIVE_STAT 32'h{c.stat(gsr=0, gts=0, gwe=1, done=1):08x}"]

    # [7] a type-2 header with no type-1 before it
    pkt = [P.DUMMY, P.SYNC, P.type2(P.OP_WRITE, 4), 1, 2, 3, 4]
    c = run(pkt)
    assert c.flags["pkt_err"]
    out += stream("PKT", pkt) + [f"`define PKT_STAT 32'h{c.stat():08x}"]

    # [8] FDRI without WCFG
    nowcfg = [w for w in P.load_stream(show)]
    j = nowcfg.index(P.CMD["WCFG"], nowcfg.index(P.type1(P.OP_WRITE, P.REG["CMD"], 1), 8))
    nowcfg[j] = P.CMD["NULL"]
    c = run(nowcfg)
    assert c.flags["wr_err"] and c.mem == 0
    out += stream("NOWCFG", nowcfg) + [f"`define NOWCFG_STAT 32'h{c.stat():08x}"]

    # [11] no CRC write at all: START must be refused
    nocrc = P.load_stream(show)
    k = nocrc.index(P.type1(P.OP_WRITE, P.REG["CRC"], 1))
    del nocrc[k:k + 2]
    c = run(nocrc)
    assert not c.flags["start_ok"] and not c.errors() and c.mem == show
    out += stream("NOCRC", nocrc) + [f"`define NOCRC_STAT 32'h{c.stat():08x}"]

    # [12] FDRO without RCFG: zeros and WR_ERROR (after [11]'s state)
    norcfg = [w for w in P.readback_stream()]
    k = norcfg.index(P.type1(P.OP_WRITE, P.REG["CMD"], 1))
    del norcfg[k:k + 2]
    # read from a frame with content, so a leak could not pass as zeros
    col = next(cc for cc in P.FRAMES["columns"]
               if any((show >> (P.FB * (cc["base"]) + 32 * w)) & 0xFFFFFFFF for w in range(P.FW)))
    norcfg[norcfg.index(P.type1(P.OP_WRITE, P.REG["FAR"], 1)) + 1] = P.far(col["far_col"])
    c.shift_in(*P.to_jtag(norcfg))
    assert c.flags["wr_err"]
    out += stream("NORCFG", norcfg) + [f"`define NORCFG_STAT 32'h{c.stat():08x}"]

    # STAT read stream
    out += stream("RDSTAT", P.read_stream("STAT", 1))
    path = os.path.join(HERE, "..", "hw", "tb", "frame_vectors.vh")
    open(path, "w").write("\n".join(out) + "\n")
    print(f"wrote {os.path.normpath(path)}: 8 frame-path scenarios, {P.NFRAMES} frames x {P.FW} words")


if __name__ == "__main__":
    main()
