#!/usr/bin/env python3
"""
Generate hw/tb/bram_vectors.vh for hw/tb/tb_bram.v - bram_core.v against
software/bob/model.py's Bram, every write mode x output-register combination.

Each block: GSR, preload through the init port (GWE = 0) with readback, then
random operations on both ports with random EN/WE/RST/REGCE/gce and the odd GSR.
Addresses stay in 0..5 so ports keep hitting each other's data; same-address
access by both ports in one cycle with a write is avoided (undefined in UG473).
"""

import argparse
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "software", "bob"))

import model as M  # noqa: E402

NADDR = 6
STEPS = 36


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.normpath(
        os.path.join(HERE, "..", "hw", "tb", "bram_vectors.vh")))
    args = ap.parse_args()

    rng = random.Random(0xB4A)
    out = ["// hw/tb/bram_vectors.vh - GENERATED by sim/gen_bram_vectors.py, do not edit.", ""]
    n = 0

    def emit(cfg, a, b, gce, gsr, gwe, go, wr, m):
        nonlocal n
        out.append(
            f"    step(2'd{cfg['wmode_a']}, 2'd{cfg['wmode_b']}, {cfg['reg_a']}, {cfg['reg_b']}, "
            f"10'd{a['addr']}, 18'h{a['di']:05x}, {a['we']}, {a['en']}, {a['rst']}, {a['regce']}, "
            f"10'd{b['addr']}, 18'h{b['di']:05x}, {b['we']}, {b['en']}, {b['rst']}, {b['regce']}, "
            f"{gce}, {gsr}, {gwe}, {go}, {wr}, "
            f"18'h{m.do('a', cfg):05x}, 18'h{m.do('b', cfg):05x}, 18'h{m.ram['a']:05x});")
        n += 1

    idle = {"addr": 0, "di": 0, "we": 0, "en": 0, "rst": 0, "regce": 0}
    # ONE model for the whole run: the RTL memory and port registers persist
    # from block to block, so the model's must too. Each block starts with GSR.
    m = M.Bram()
    for wma in (0, 1, 2):
        for wmb in (0, 1, 2):
            for ra in (0, 1):
                for rb in (0, 1):
                    cfg = {"wmode_a": wma, "wmode_b": wmb, "reg_a": ra, "reg_b": rb}
                    m.clock(cfg, {"a": idle, "b": idle}, gsr=1)
                    emit(cfg, idle, idle, 0, 1, 0, 0, 0, m)
                    for addr in range(NADDR):                 # preload
                        data = rng.getrandbits(18)
                        m.init(True, addr, data)
                        emit(cfg, {**idle, "addr": addr, "di": data}, idle, 0, 0, 0, 1, 1, m)
                    for addr in range(NADDR):                 # read back
                        m.init(False, addr)
                        emit(cfg, {**idle, "addr": addr}, idle, 0, 0, 0, 1, 0, m)
                    for _ in range(STEPS):
                        ports = {}
                        for p in "ab":
                            ports[p] = {"addr": rng.randrange(NADDR), "di": rng.getrandbits(18),
                                        "we": int(rng.random() < 0.4), "en": int(rng.random() < 0.8),
                                        "rst": int(rng.random() < 0.1), "regce": int(rng.random() < 0.7)}
                        a, b = ports["a"], ports["b"]
                        if a["en"] and b["en"] and a["addr"] == b["addr"] and (a["we"] or b["we"]):
                            b["addr"] = (a["addr"] + 1) % NADDR
                        gce = int(rng.random() < 0.85)
                        gsr = int(rng.random() < 0.03)
                        m.clock(cfg, ports, gce=gce, gsr=gsr, gwe=1)
                        emit(cfg, a, b, gce, gsr, 1, 0, 0, m)

    with open(args.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {args.out}  ({n} cycles, 36 mode/register combinations)")


if __name__ == "__main__":
    main()
