"""
Bitstream generation for the bob fabric (M7: generated from VPR's rr graph).

Every constant, field position, pin and routing mux comes from
tools/bob/device.json, generated by tools/bob/device.py - the single source of
truth. Set BOB_DEVICE_JSON to use another description (the K=4 tests do).

Coordinates are VPR's: x to the East, y to the North; CLBs sit at x in
{1,2,4,5,7,8}, y in 1..8 (x=3 is the BRAM column, x=6 the DSP column, the
perimeter is I/O pads).

Routing model
-------------
The fabric is the routing-resource graph: nodes are wires (CHANX/CHANY), block
input pins (IPIN) and block output pins (OPIN). A node that edges drive has a
mux in the chain; value 0 is const0, IPIN value 1 is const1, and value base+i
selects the i-th driving node (ascending node id). Routing a net is programming
each node on a path from the source OPIN to the sink IPIN to select the node
before it.

The router routes one net at a time: a breadth-first search from every node the
net already owns (so fanout shares wires) to the next sink, never through a
node another net owns. If a net cannot be routed, it is moved to the front and
every net is routed again (a cheap cousin of PathFinder's negotiation).

Board vectors
-------------
pad_i: bit 0 SW0, bit 1 SW1, bits 2..5 BTN0..3.   pad_o: bit k = LDk (k < 3).
Those map to fabric pads through device.json "pads"; every other pad is
reachable by boundary scan only.
"""

import json
import os
from collections import deque

_DEVICE_JSON = os.environ.get("BOB_DEVICE_JSON") or os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tools", "bob", "device.json")
with open(_DEVICE_JSON) as _fh:
    DEVICE = json.load(_fh)

LUT_K = DEVICE["lut_k"]
LUT_INIT_W = 1 << LUT_K
CHAIN_W = DEVICE["chain"]["width"]
FABRIC_CFG_W = CHAIN_W                       # the name every host tool has used since M1

_TT = DEVICE["tile_types"]
FIELD = {f["name"]: (f["offset"], f["width"]) for f in _TT["clb"]["fields"]}
CLB_CFG_W = _TT["clb"]["width"]
CTRL_FIELD = {f["name"]: (f["offset"], f["width"]) for f in _TT["ctrl"]["fields"]}
BRAM_FIELD = {f["name"]: (f["offset"], f["width"]) for f in _TT["bram"]["fields"]}
DSP_FIELD = {f["name"]: (f["offset"], f["width"]) for f in _TT["dsp"]["fields"]}
FLAG_NAMES = ("ff_en", "ff_rstval", "ff_ce_en", "ff_sr_en", "cy_en", "cy_di_sel", "ff_d_sel")
CLB_FF_EN = FIELD["ff_en"][0]
CLB_FF_D_SEL = FIELD["ff_d_sel"][0]

CLOCK_MODES = DEVICE["clock"]["modes"]
DIV_MIN_SHIFT = DEVICE["clock"]["div_min_shift"]

BLOCKS = {b["name"]: b for b in DEVICE["blocks"]}
CLBS = [b["name"] for b in DEVICE["blocks"] if b["type"] == "clb"]          # CAPTURE order
CLB_AT = {(b["x"], b["y"]): b["name"] for b in DEVICE["blocks"] if b["type"] == "clb"}
CLB_XY_INDEX = {(BLOCKS[n]["x"], BLOCKS[n]["y"]): i for i, n in enumerate(CLBS)}
NCLB = len(CLBS)
NBRAM = DEVICE["bram"]["count"]
NDSP = DEVICE["dsp"]["count"]

NPAD = DEVICE["pads"]["count"]
PAD_XY = {p["pad"]: (p["x"], p["y"]) for p in DEVICE["pads"]["io"]}
BOARD_IN = [p["pad"] for p in DEVICE["pads"]["board_inputs"]]      # pad_i bit k -> pad
BOARD_OUT = [p["pad"] for p in DEVICE["pads"]["board_outputs"]]    # pad_o bit k -> pad
BSR_W = DEVICE["bsr"]["width"]

PIN = DEVICE["pins"]                                               # 'clb_x1y1.I[0]' -> node
NODE = {n[0]: n for n in DEVICE["rr"]["nodes"]}
MUX = {m[0]: (m[1], m[2], m[3], tuple(m[4])) for m in DEVICE["rr"]["muxes"]}
DIRECT = {i: o for i, o in DEVICE["rr"]["directs"]}
FANOUT = {}
for _node, (_lo, _w, _base, _ins) in sorted(MUX.items()):
    for _src in _ins:
        FANOUT.setdefault(_src, []).append(_node)
CHAN = {"CHANX", "CHANY"}

BRAM_WRITE_MODES = DEVICE["bram"]["write_modes"]
BRAM_PORT_PINS = [(n, w) for n, w in DEVICE["bram"]["port_pins"]]
BRAM_PINS = [f"{n}{k}" if w > 1 else n for n, w in BRAM_PORT_PINS for k in range(w)]
DSP_OPMODES = DEVICE["dsp"]["opmodes"]
DSP_BUSES = [(n, w) for n, w in DEVICE["dsp"]["buses"]]
DSP_CTRL_NAMES = tuple(DEVICE["dsp"]["ctrl_names"])
DSP_BUS_SOURCES = ("const0", "jtag", "fabric")


def pad_block(pad):
    x, y = PAD_XY[pad]
    return f"io_x{x}y{y}"


def clb_name(x, y):
    if (x, y) not in CLB_AT:
        raise ValueError(f"no CLB at ({x},{y}); CLB columns are "
                         f"{sorted({k[0] for k in CLB_AT})}, rows 1..{max(k[1] for k in CLB_AT)}")
    return CLB_AT[(x, y)]


def bram_pin_name(pin):
    """'addr3' -> ('addr', 3); 'we' -> ('we', 0)"""
    for n, w in BRAM_PORT_PINS:
        if w == 1 and pin == n:
            return n, 0
        if w > 1 and pin.startswith(n) and pin[len(n):].isdigit() and int(pin[len(n):]) < w:
            return n, int(pin[len(n):])
    raise ValueError(f"no BRAM pin {pin}")


def lut(fn, nin=None):
    """Truth table of fn over the LUT's inputs, as the LUT_INIT_W-bit INIT."""
    nin = LUT_K if nin is None else nin
    init = 0
    for a in range(LUT_INIT_W):
        bits = [(a >> k) & 1 for k in range(nin)]
        if fn(*bits):
            init |= 1 << a
    return init


class LUT:
    @staticmethod
    def const0():  return 0
    @staticmethod
    def const1():  return (1 << LUT_INIT_W) - 1
    @staticmethod
    def buf(k=0):  return lut(lambda *b: b[k])
    @staticmethod
    def inv(k=0):  return lut(lambda *b: not b[k])
    @staticmethod
    def and2():    return lut(lambda a, b: a & b, 2)
    @staticmethod
    def or2():     return lut(lambda a, b: a | b, 2)
    @staticmethod
    def xor2():    return lut(lambda a, b: a ^ b, 2)
    @staticmethod
    def nand2():   return lut(lambda a, b: not (a & b), 2)
    @staticmethod
    def nor2():    return lut(lambda a, b: not (a | b), 2)
    @staticmethod
    def xnor2():   return lut(lambda a, b: not (a ^ b), 2)
    @staticmethod
    def and3():    return lut(lambda a, b, c: a & b & c, 3)
    @staticmethod
    def mux2():    return lut(lambda a, b, s: b if s else a, 3)
    @staticmethod
    def maj3():    return lut(lambda a, b, c: (a & b) | (b & c) | (a & c), 3)
    @staticmethod
    def and6():    return lut(lambda *b: all(b), 6)
    @staticmethod
    def xor6():    return lut(lambda *b: sum(b) & 1, 6)


# --- signals ------------------------------------------------------------------------

class Signal:
    pass


class Const(Signal):
    def __init__(self, v): self.v = v
    def __repr__(self): return f"const{self.v}"


class Pad(Signal):
    """The world side of fabric pad n (board inputs are Design.input(k))."""
    def __init__(self, n):
        if not 0 <= n < NPAD:
            raise ValueError(f"pads are 0..{NPAD - 1}")
        self.n = n
    def __repr__(self): return f"pad{self.n}"


class Cell(Signal):
    """CLB (x,y)'s o or o5 output."""
    def __init__(self, x, y, which="o"):
        clb_name(x, y)
        if which not in ("o", "o5"):
            raise ValueError("a CLB output is 'o' or 'o5'")
        self.x, self.y, self.which = x, y, which
    def __repr__(self): return f"clb({self.x},{self.y}).{self.which}"


class BramOut(Signal):
    def __init__(self, b, port, bit):
        if not (0 <= b < NBRAM and port in ("a", "b") and 0 <= bit < 18):
            raise ValueError(f"no BRAM output bram{b}.do_{port}[{bit}]")
        self.b, self.port, self.bit = b, port, bit
    def __repr__(self): return f"bram{self.b}.do_{self.port}[{self.bit}]"


class DspOut(Signal):
    def __init__(self, s, bit):
        if not (0 <= s < NDSP and 0 <= bit < 48):
            raise ValueError(f"no DSP output dsp{s}.p[{bit}]")
        self.s, self.bit = s, bit
    def __repr__(self): return f"dsp{self.s}.p[{self.bit}]"


def source_node(sig):
    if isinstance(sig, Pad):
        return PIN[f"{pad_block(sig.n)}.inpad[0]"]
    if isinstance(sig, Cell):
        return PIN[f"{clb_name(sig.x, sig.y)}.{'O' if sig.which == 'o' else 'O5'}[0]"]
    if isinstance(sig, BramOut):
        return PIN[f"bram{sig.b}.do_{sig.port}[{sig.bit}]"]
    if isinstance(sig, DspOut):
        return PIN[f"dsp{sig.s}.p[{sig.bit}]"]
    raise TypeError(f"{sig!r} has no source pin")


def signal_key(sig):
    if isinstance(sig, Const):
        return ("const", sig.v)
    return ("node", source_node(sig))


class RouteError(Exception):
    pass


# --- the chain word -------------------------------------------------------------------

class Bitstream:
    """The configuration chain as an integer, with field and mux accessors."""

    def __init__(self, word=0):
        self.word = word

    def _put(self, lo, width, value):
        if not 0 <= value < (1 << width):
            raise ValueError(f"value {value} does not fit {width} bits")
        self.word = (self.word & ~(((1 << width) - 1) << lo)) | (value << lo)

    def _get(self, lo, width):
        return (self.word >> lo) & ((1 << width) - 1)

    def set_ctrl(self, clk_mode=0, clk_div=0):
        self._put(*CTRL_FIELD["clk_mode"], clk_mode)
        self._put(*CTRL_FIELD["clk_div"], clk_div)

    def get_ctrl(self, name):
        return self._get(*CTRL_FIELD[name])

    def _block_field(self, block, name):
        b = BLOCKS[block]
        table = {"clb": FIELD, "bram": BRAM_FIELD, "dsp": DSP_FIELD}[b["type"]]
        off, w = table[name]
        return b["chain_lo"] + off, w

    def set_block(self, block, name, value):
        self._put(*self._block_field(block, name), value)

    def get_block(self, block, name):
        return self._get(*self._block_field(block, name))

    def set_field(self, x, y, name, value):
        self.set_block(clb_name(x, y), name, value)

    def get_field(self, x, y, name):
        return self.get_block(clb_name(x, y), name)

    def set_lut(self, x, y, init):
        self.set_field(x, y, "init", init & ((1 << LUT_INIT_W) - 1))

    def set_clb_flags(self, x, y, **flags):
        for name in flags:
            if name not in FLAG_NAMES:
                raise ValueError(f"unknown CLB flag {name}")
        for name in FLAG_NAMES:
            self.set_field(x, y, name, int(flags.get(name, 0)))

    def set_bram(self, b, name, value):
        self.set_block(f"bram{b}", name, value)

    def get_bram(self, b, name):
        return self.get_block(f"bram{b}", name)

    def set_dsp(self, s, name, value):
        self.set_block(f"dsp{s}", name, value)

    def get_dsp(self, s, name):
        return self.get_block(f"dsp{s}", name)

    def set_mux(self, node, value):
        lo, w, _base, _ins = MUX[node]
        self._put(lo, w, value)

    def get_mux(self, node):
        lo, w, _base, _ins = MUX[node]
        return self._get(lo, w)

    def select(self, node, src):
        """Program mux `node` to take its input from node `src`."""
        lo, w, base, ins = MUX[node]
        self._put(lo, w, base + ins.index(src))

    def to_int(self):
        return self.word

    def to_hex(self):
        return f"{self.word:0{(CHAIN_W + 3) // 4}x}"

    def __len__(self):
        return CHAIN_W


# --- designs ---------------------------------------------------------------------------

class Design:
    """Place LUTs, connect BRAM/DSP pins, name outputs; build() routes it."""

    def __init__(self):
        self.bs = Bitstream()
        self.cells = {}          # (x,y) -> dict(init, flags)
        self.sinks = {}          # IPIN node -> Signal
        self.sink_label = {}     # IPIN node -> human name
        self.clock = ("jtag", 0)
        self.bram_cfg = {b: {} for b in range(NBRAM)}
        self.bram_src = {}       # (b, port) -> "jtag" | "fabric"
        self.dsp_cfg = {s: {} for s in range(NDSP)}
        self.dsp_ctrl_src = {}   # s -> "jtag" | "fabric"
        self.routes = {}         # net key -> [nodes]
        self._built = False

    # --- description ---

    def input(self, k):
        """Board input k: 0 SW0, 1 SW1, 2..5 BTN0..3."""
        return Pad(BOARD_IN[k])

    def pad(self, n):
        return Pad(n)

    def const(self, v):
        return Const(1 if v else 0)

    def set_clock(self, mode="jtag", div=0):
        """'jtag' (one step per TCK edge while USER1 ce) or 'run' (an enable every
        2**(div+DIV_MIN_SHIFT) sysclk cycles)."""
        if mode not in CLOCK_MODES:
            raise ValueError(f"clock mode is one of {sorted(CLOCK_MODES)}")
        self.clock = (mode, div)

    def _sink(self, pin, sig, label=None):
        node = PIN[pin]
        if not isinstance(sig, Signal):
            raise TypeError(f"{pin}: {sig!r} is not a Signal")
        if node in self.sinks and signal_key(self.sinks[node]) != signal_key(sig):
            raise ValueError(f"{pin} is already driven by {self.sinks[node]}")
        self.sinks[node] = sig
        self.sink_label[node] = label or pin

    def lut(self, x, y, init, inputs=(), ce=None, sr=None, **flags):
        """Place a LUT at CLB (x,y). `inputs` map positionally to i[0], i[1]...
        `ce` / `sr` (defaults const1 / const0) matter only with ff_ce_en / ff_sr_en."""
        name = clb_name(x, y)
        if (x, y) in self.cells:
            raise ValueError(f"CLB ({x},{y}) already holds a LUT")
        if len(inputs) > LUT_K:
            raise ValueError(f"a LUT{LUT_K} has at most {LUT_K} inputs")
        for f in flags:
            if f not in FLAG_NAMES:
                raise ValueError(f"unknown CLB flag {f}")
        self.cells[(x, y)] = {"init": init, "flags": flags}
        for j in range(LUT_K):
            self._sink(f"{name}.I[{j}]", inputs[j] if j < len(inputs) else Const(0))
        self._sink(f"{name}.ce[0]", Const(1) if ce is None else ce)
        self._sink(f"{name}.sr[0]", Const(0) if sr is None else sr)
        return Cell(x, y, "o")

    def output(self, k, signal):
        """Drive board LED k (pad_o bit k)."""
        if not 0 <= k < len(BOARD_OUT):
            raise ValueError(f"output pads are pad_o[0..{len(BOARD_OUT) - 1}]")
        self._sink(f"{pad_block(BOARD_OUT[k])}.outpad[0]", signal, f"LD{k}")

    def pad_output(self, n, signal):
        self._sink(f"{pad_block(n)}.outpad[0]", signal)

    # --- BRAM ---

    def bram_mode(self, port, write_mode="WRITE_FIRST", out_reg=False, bram=0):
        if write_mode not in BRAM_WRITE_MODES:
            raise ValueError(f"write mode is one of {sorted(BRAM_WRITE_MODES)}")
        self.bram_cfg[bram][f"wmode_{port}"] = BRAM_WRITE_MODES[write_mode]
        self.bram_cfg[bram][f"reg_{port}"] = int(bool(out_reg))

    def bram_pin(self, port, pin, source, bram=0):
        """Connect bram<bram> port 'a'/'b' pin (addr0..9, di0..17, we, en, rst, regce)
        to a Signal (routed) or "jtag" (the whole port then comes from USER4's drive word)."""
        if port not in ("a", "b"):
            raise ValueError("BRAM ports are 'a' and 'b'")
        name, bit = bram_pin_name(pin)
        kind = "jtag" if source == "jtag" else "fabric"
        if self.bram_src.setdefault((bram, port), kind) != kind:
            raise ValueError(f"bram{bram} port {port}: pins are all JTAG-driven or all fabric")
        if kind == "jtag":
            self.bram_cfg[bram][f"jtag_{port}"] = 1
        else:
            self._sink(f"bram{bram}.{name}_{port}[{bit}]", source)

    def bram_out(self, port, bit, bram=0):
        return BramOut(bram, port, bit)

    # --- DSP ---

    def dsp_config(self, s, opmode="M", use_d=False, d_sub=False, areg=0, breg=0, creg=0,
                   dreg=0, mreg=0, preg=0, bus_a="const0", bus_b="const0", bus_c="const0",
                   bus_d="const0"):
        """bus_x: 'const0' (unconnected pins read 0), 'jtag' (the DSP JTAG drive word)
        or 'fabric' (pins connected with dsp_pin)."""
        if opmode not in DSP_OPMODES:
            raise ValueError(f"opmode is one of {sorted(DSP_OPMODES)}")
        cfg = {"opmode": DSP_OPMODES[opmode], "use_d": int(use_d), "d_sub": int(d_sub),
               "areg": int(areg), "breg": int(breg), "creg": int(creg), "dreg": int(dreg),
               "mreg": int(mreg), "preg": int(preg)}
        for bus, src in (("a", bus_a), ("b", bus_b), ("c", bus_c), ("d", bus_d)):
            if src not in DSP_BUS_SOURCES:
                raise ValueError(f"bus source is one of {DSP_BUS_SOURCES}")
            cfg[f"jtag_{bus}"] = int(src == "jtag")
        self.dsp_cfg[s].update(cfg)

    def dsp_pin(self, s, bus, bit, signal):
        """Connect DSP slice s bus pin (a/b/c/d, bit) to a routed Signal or a Const."""
        if self.dsp_cfg[s].get(f"jtag_{bus}"):
            raise ValueError(f"dsp{s} bus {bus} is JTAG-driven")
        self._sink(f"dsp{s}.{bus}[{bit}]", signal)

    def dsp_ctrl(self, s, name, source):
        if name not in DSP_CTRL_NAMES:
            raise ValueError(f"no DSP control {name}")
        kind = "jtag" if source == "jtag" else "fabric"
        if self.dsp_ctrl_src.setdefault(s, kind) != kind:
            raise ValueError(f"dsp{s}: controls are all JTAG-driven or all fabric")
        if kind == "jtag":
            self.dsp_cfg[s]["jtag_ctrl"] = 1
        else:
            self._sink(f"dsp{s}.{name}[0]", source)

    def dsp_out(self, s, bit):
        return DspOut(s, bit)

    # --- routing ---

    def _route_net(self, key, sinks, owner):
        src = key[1]
        tree = [src]
        owner[src] = key
        path_nodes = [src]
        for sink in sinks:
            if owner.get(sink) not in (None, key):
                raise RouteError(f"sink {self.sink_label[sink]} is taken")
            prev = {n: None for n in tree}
            q = deque(tree)
            found = False
            while q and not found:
                n = q.popleft()
                for m in FANOUT.get(n, ()):
                    if m in prev:
                        continue
                    if m == sink:
                        prev[m] = n
                        found = True
                        break
                    if NODE[m][1] not in CHAN or owner.get(m) not in (None, key):
                        continue
                    prev[m] = n
                    q.append(m)
            if not found:
                return self.sink_label[sink]
            m = sink
            while prev[m] is not None:
                p = prev[m]
                if owner.get(m) != key:
                    self.bs.select(m, p)
                    owner[m] = key
                    tree.append(m)
                    path_nodes.append(m)
                m = p
        self.routes[key] = path_nodes
        return None

    def _route(self):
        nets = {}
        for node, sig in self.sinks.items():
            if isinstance(sig, Const):
                self.bs.set_mux(node, sig.v)                    # IPIN: 0 const0, 1 const1
            else:
                nets.setdefault(signal_key(sig), []).append(node)
        order = sorted(nets, key=lambda k: (-len(nets[k]), k))
        for attempt in range(len(order) + 1):
            owner = {}
            self.routes = {}
            saved = self.bs.word
            failed = None
            for key in order:
                sinks = sorted(nets[key], key=lambda s: (NODE[s][2] - NODE[key[1]][2]) ** 2
                               + (NODE[s][3] - NODE[key[1]][3]) ** 2)
                bad = self._route_net(key, sinks, owner)
                if bad:
                    failed = (key, bad)
                    break
            if failed is None:
                return
            self.bs.word = saved
            for node in MUX:                                    # clear routing, keep consts
                if NODE[node][1] in CHAN:
                    self.bs.set_mux(node, 0)
            for node, sig in self.sinks.items():
                if not isinstance(sig, Const):
                    self.bs.set_mux(node, 0)
            order.remove(failed[0])
            order.insert(0, failed[0])
        raise RouteError(f"no route to {failed[1]}")

    # --- build ---

    def build(self):
        if self._built:
            raise RuntimeError("build() is single-shot; make a new Design")
        mode, div = self.clock
        self.bs.set_ctrl(CLOCK_MODES[mode], div)
        for (x, y), spec in self.cells.items():
            self.bs.set_lut(x, y, spec["init"])
            self.bs.set_clb_flags(x, y, **spec["flags"])
        for b, cfg in self.bram_cfg.items():
            for name, v in cfg.items():
                self.bs.set_bram(b, name, v)
        for s, cfg in self.dsp_cfg.items():
            for name, v in cfg.items():
                self.bs.set_dsp(s, name, v)
        self._route()
        self._built = True
        return self.bs

    # --- introspection ---

    def report(self):
        mode, div = self.clock
        used = sum(len(v) - 1 for v in self.routes.values())
        lines = [f"design: {len(self.cells)} LUT(s), {len(self.routes)} routed net(s) over "
                 f"{used} routing node(s), clock {mode}" + (f" div {div}" if mode == "run" else "")]
        for (x, y), spec in sorted(self.cells.items()):
            name = clb_name(x, y)
            ins = ", ".join(f"i{j}={self.sinks[PIN[f'{name}.I[{j}]']]}" for j in range(LUT_K)
                            if not isinstance(self.sinks[PIN[f"{name}.I[{j}]"]], Const))
            lines.append(f"  clb({x},{y})  INIT=0x{spec['init']:0{(LUT_INIT_W + 3) // 4}X}  {ins}")
        for key, nodes in sorted(self.routes.items()):
            sinks = [self.sink_label[n] for n, s in self.sinks.items()
                     if not isinstance(s, Const) and signal_key(s) == key]
            lines.append(f"  net from node {key[1]}: {len(nodes) - 1} wire(s) -> {', '.join(sinks)}")
        return "\n".join(lines)


# --- a software model, for checking a bitstream without hardware -----------------------

def simulate(bs, pad_i, cin=0):
    """pad_o (LD2..0 as an int) for one board input vector, combinational designs only
    (tools/bob/model.py models the flip-flops, BRAM and DSP registers)."""
    import sys
    sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                    "tools", "bob"))
    import model
    for name in CLBS:
        if Bitstream(bs.to_int()).get_block(name, "ff_en"):
            b = BLOCKS[name]
            raise ValueError("simulate() models combinational designs only "
                             f"(clb ({b['x']},{b['y']}) has FF_EN set) - use tools/bob/model.py")
    return model.Fabric(bs).outputs(pad_i, cin)
