#!/usr/bin/env python3
"""
bd.py - block designs: blocks wired on a canvas, turned into a Verilog wrapper (M18).

Vivado's IP integrator, cut down to this fabric. A block design (<bd>.bd, JSON) holds

  blocks   instances of the project's own modules ("module") or of the IP cores in
           software/bob/ip/ ("ip"), each with its parameters and a canvas position
  wires    "src" -> "dst" endpoint pairs. An endpoint is <block>.<port>, optionally
           with a bit select: cnt.q, cnt.q[2], cnt.q[2:1]. The block `board` is the
           board: board.sw[1:0], board.btn[3:0], board.led[2:0] and board.pad<N>.

{"bd": 1, "name": "demo",
 "blocks": [{"id": "cnt", "kind": "ip", "type": "counter", "params": {"W": 3}, "x": 240, "y": 80}],
 "wires":  [{"src": "board.sw[1]", "dst": "cnt.en"}, {"src": "cnt.q", "dst": "board.led"}]}

generate() writes bd/<name>_wrapper.v, a module with the examples' ports (clk, sw[1:0],
btn[3:0], led[2:0]) plus one port per pad used. A design on the board's switches, buttons
and LEDs therefore needs no pin file and keeps the model check of `./bob build`; one that
uses a pad gets constrs/<name>.pcf with every port bit named, as vpr_run.read_pcf() wants.

Rules (validate()), each reported against the endpoint it is about:
  - every block input bit is driven exactly once (tie an unused one to a `const` block)
  - a wire's two ends are the same width
  - a source is a block output or a board input; a destination a block input or a board output
  - a `clk` port is never wired: the fabric has one clock and it reaches every `clk` port
  - a pad is used in one direction only, and not a pad the board already names (use sw/btn/led)
    nor the one the clock takes
  - LED bits nobody drives are tied to 0

Where this diverges from Vivado: no interfaces (AXI and the like: the fabric has none), no
address editor, no clock/reset wizards (one clock, synchronous resets only), and loops of
combinational logic through blocks are left to synthesis to report rather than found here.
"""

import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "software", "host"))

import bitstream as B  # noqa: E402
import project as P  # noqa: E402

VERSION = 1
MARK = "generated by bob from"          # first line of every wrapper: never read back as a module
BOARD = {"sw": ("input", 2), "btn": ("input", 4), "led": ("output", 3)}
BOARD_PADS = set(B.BOARD_IN) | set(B.BOARD_OUT)
# vpr_run.write_eblif gives clk the first pad the board does not name, so that one is taken
CLK_PAD = sorted(p for p in B.PAD_XY if p not in BOARD_PADS)[0]
FREE_PADS = sorted(p for p in B.PAD_XY if p not in BOARD_PADS and p != CLK_PAD)
ID = re.compile(r"[A-Za-z][A-Za-z0-9_]*")
# Verilog-2005 and SystemVerilog keywords (IEEE 1800 Annex B): a block name becomes an
# instance name in the wrapper, so none of these, and none of the wrapper's own ports.
KEYWORDS = set("""
alias always always_comb always_ff always_latch and assert assign assume automatic before begin
bind bins binsof bit break buf bufif0 bufif1 byte case casex casez cell chandle checker class
clocking cmos config const constraint context continue cover covergroup coverpoint cross deassign
default defparam design disable dist do edge else end endcase endchecker endclass endclocking
endconfig endfunction endgenerate endgroup endinterface endmodule endpackage endprimitive
endprogram endproperty endspecify endsequence endtable endtask enum event eventually expect
export extends extern final first_match for force foreach forever fork forkjoin function generate
genvar global highz0 highz1 if iff ifnone ignore_bins illegal_bins implements implies import
incdir include initial inout input inside instance int integer interconnect interface intersect
join join_any join_none large let liblist library local localparam logic longint macromodule
matches medium modport module nand negedge nettype new nexttime nmos nor noshowcancelled not
notif0 notif1 null or output package packed parameter pmos posedge primitive priority program
property protected pull0 pull1 pulldown pullup pulsestyle_ondetect pulsestyle_onevent pure rand
randc randcase randsequence rcmos real realtime ref reg reject_on release repeat restrict return
rnmos rpmos rtran rtranif0 rtranif1 s_always s_eventually s_nexttime s_until s_until_with scalared
sequence shortint shortreal showcancelled signed small soft solve specify specparam static string
strong strong0 strong1 struct super supply0 supply1 sync_accept_on sync_reject_on table tagged
task this throughout time timeprecision timeunit tran tranif0 tranif1 tri tri0 tri1 triand trior
trireg type typedef union unique unique0 unsigned until until_with untyped use uwire var vectored
virtual void wait wait_order wand weak weak0 weak1 while wildcard wire with within wor xnor xor
""".split())
RESERVED = {"board", "clk", "sw", "btn", "led"} | KEYWORDS
ENDPOINT = re.compile(r"^(\w+)\.(\w+)(?:\[(\d+)(?::(\d+))?\])?$")


class BdError(Exception):
    pass


def empty(name):
    return {"bd": VERSION, "name": name, "blocks": [], "wires": []}


def load(path):
    try:
        d = json.load(open(path))
    except (OSError, ValueError) as e:
        raise BdError(f"{path}: {e}")
    if d.get("bd") != VERSION:
        raise BdError(f"{path}: not a version-{VERSION} block design")
    d.setdefault("blocks", [])
    d.setdefault("wires", [])
    return d


def save(path, bd):
    bd = {"bd": VERSION, "name": bd["name"], "blocks": bd.get("blocks", []), "wires": bd.get("wires", []),
          "board": bd.get("board") or {}}     # the canvas: where the board blocks sit, pads added
    with open(path, "w") as fh:
        json.dump(bd, fh, indent=1)
        fh.write("\n")
    return path


def is_generated(path):
    try:
        with open(path) as fh:
            return MARK in fh.readline()
    except OSError:
        return False


def user_files(proj):
    """The project's HDL minus every generated wrapper: a wrapper is made from the blocks,
    so reading it back as one would be circular."""
    return [f for f in proj.hdl_files() if not is_generated(f)] if proj else []


def palette(proj):
    """What can go on the canvas: IP, the project's modules, the board."""
    mods = []
    if proj:
        try:
            mods = [m for m in P.modules(user_files(proj))]
        except P.ProjectError as e:
            mods = [{"error": str(e)}]
    return {"ip": P.ip_catalog(), "modules": mods,
            "board": {"ports": [{"name": n, "dir": d, "width": w} for n, (d, w) in BOARD.items()],
                      "pads": FREE_PADS}}


# --- resolving blocks to their ports ----------------------------------------------

def _block_ports(blk, proj, ip):
    kind, typ, params = blk.get("kind"), blk.get("type"), blk.get("params") or {}
    if kind == "ip":
        if typ not in ip:
            raise BdError(f"no IP called {typ}")
        rec = ip[typ]
        known = {p["name"] for p in rec["params"]}
        bad = set(params) - known
        if bad:
            raise BdError(f"IP {typ} has no parameter(s) {sorted(bad)}")
        return rec["module"], rec["file"], P.ports([rec["file"]], rec["module"], params)
    if kind == "module":
        files = user_files(proj)
        mods = {m["name"]: m for m in P.modules(files)} if files else {}
        if typ not in mods:
            raise BdError(f"no module {typ} in the project's sources")
        bad = set(params) - set(mods[typ]["params"])
        if bad:
            raise BdError(f"module {typ} has no parameter(s) {sorted(bad)}")
        return typ, None, P.ports(files, typ, params)
    raise BdError(f"block kind is ip or module, not {kind!r}")


def _endpoint(text):
    m = ENDPOINT.match(str(text).strip())
    if not m:
        raise BdError(f"{text!r}: an endpoint is block.port, block.port[i] or block.port[hi:lo]")
    blk, port, hi, lo = m.group(1), m.group(2), m.group(3), m.group(4)
    if hi is not None and lo is None:
        lo = hi
    return blk, port, (int(hi), int(lo)) if hi is not None else None


def check(bd, proj=None):
    """-> {"errors": [...], "warnings": [...], "blocks": {id: {module, file, ports}},
          "pads": {pad: dir}}. An error is {"where": endpoint or block id, "msg": text}."""
    errors, warnings = [], []
    ip = {r["ip"]: r for r in P.ip_catalog()}
    blocks, pads = {}, {}

    name = bd.get("name", "")
    if not ID.fullmatch(name or ""):
        errors.append({"where": "design", "msg": "a block design name is a Verilog identifier"})

    for blk in bd.get("blocks", []):
        bid = blk.get("id", "")
        if not ID.fullmatch(bid or "") or "__" in bid or bid in RESERVED or re.fullmatch(r"pad\d+", bid):
            why = " (a Verilog keyword)" if bid in KEYWORDS else ""
            errors.append({"where": bid or "?", "msg": f"{bid!r} is not a usable block name{why} "
                           "(a Verilog identifier, no __, not a keyword, not board/clk/sw/btn/led/padN)"})
            continue
        if bid in blocks:
            errors.append({"where": bid, "msg": f"two blocks are called {bid}"})
            continue
        try:
            module, f, ports = _block_ports(blk, proj, ip)
        except (BdError, P.ProjectError) as e:
            errors.append({"where": bid, "msg": str(e)})
            continue
        blocks[bid] = {"module": module, "file": f, "kind": blk.get("kind"),
                       "params": blk.get("params") or {},
                       "ports": {p["name"]: p for p in ports}}
        clk = blocks[bid]["ports"].get("clk")
        if clk and (clk["dir"] != "input" or clk["width"] != 1):
            errors.append({"where": f"{bid}.clk", "msg": "a clk port must be a 1-bit input"})

    def port_of(ep, text):
        blk, port, sel = ep
        if blk == "board":
            if port in BOARD:
                d, w = BOARD[port]
            elif re.fullmatch(r"pad\d+", port):
                n = int(port[3:])
                if n in BOARD_PADS:
                    raise BdError(f"{text}: pad{n} is wired to a switch, button or LED on the board; "
                                  "use board.sw, board.btn or board.led")
                if n not in B.PAD_XY:
                    raise BdError(f"{text}: there is no pad{n} (pads 0..{B.NPAD - 1})")
                if n == CLK_PAD:
                    raise BdError(f"{text}: pad{n} carries the clock; use another pad")
                d, w = "inout", 1
            else:
                raise BdError(f"{text}: the board has sw, btn, led and pad<N>, not {port}")
        else:
            if blk not in blocks:
                raise BdError(f"{text}: no block {blk}")
            p = blocks[blk]["ports"].get(port)
            if p is None:
                raise BdError(f"{text}: {blk} ({blocks[blk]['module']}) has no port {port}")
            if port == "clk":
                raise BdError(f"{text}: clk is connected for you - the fabric has one clock")
            d, w = p["dir"], p["width"]
        if sel is None:
            lo, hi = 0, w - 1
        else:
            hi, lo = sel
            if hi < lo or hi >= w:
                raise BdError(f"{text}: [{hi}:{lo}] is outside {port}[{w - 1}:0]")
        return d, w, hi, lo

    driven = {}                     # (block, port) -> {bit: source text}
    good = []
    for i, wire in enumerate(bd.get("wires", [])):
        s_txt, d_txt = wire.get("src", ""), wire.get("dst", "")
        try:
            s_ep, d_ep = _endpoint(s_txt), _endpoint(d_txt)
            sd, _sw, shi, slo = port_of(s_ep, s_txt)
            dd, _dw, dhi, dlo = port_of(d_ep, d_txt)
        except BdError as e:
            errors.append({"where": d_txt or s_txt or f"wire {i}", "msg": str(e)})
            continue
        bad = False
        if s_ep[0] == "board" and s_ep[1].startswith("pad"):
            if pads.setdefault(s_ep[1], "input") != "input":
                errors.append({"where": s_txt, "msg": f"{s_ep[1]} is used as an output elsewhere"})
                bad = True
        elif sd != ("input" if s_ep[0] == "board" else "output"):
            what = "a board output (LED)" if s_ep[0] == "board" else f"an {sd}"
            errors.append({"where": s_txt, "msg": f"{s_txt} is {what}; a wire starts at a block "
                           "output or a board input"})
            bad = True
        if d_ep[0] == "board" and d_ep[1].startswith("pad"):
            if pads.setdefault(d_ep[1], "output") != "output":
                errors.append({"where": d_txt, "msg": f"{d_ep[1]} is used as an input elsewhere"})
                bad = True
        elif dd != ("output" if d_ep[0] == "board" else "input"):
            what = "a board input (switch or button)" if d_ep[0] == "board" else f"an {dd}"
            errors.append({"where": d_txt, "msg": f"{d_txt} is {what}; a wire ends at a block "
                           "input or a board output"})
            bad = True
        if shi - slo != dhi - dlo:
            errors.append({"where": d_txt, "msg": f"{s_txt} is {shi - slo + 1} bit(s) wide but "
                           f"{d_txt} is {dhi - dlo + 1}: select bits, e.g. {s_ep[0]}.{s_ep[1]}"
                           f"[{slo + dhi - dlo}:{slo}]"})
            bad = True
        if bad:
            continue
        taken = driven.setdefault((d_ep[0], d_ep[1]), {})
        clash = [b for b in range(dlo, dhi + 1) if b in taken]
        if clash:
            errors.append({"where": d_txt, "msg": f"{d_ep[0]}.{d_ep[1]}[{clash[0]}] is driven twice: "
                           f"by {taken[clash[0]]} and {s_txt}"})
            continue
        for b in range(dlo, dhi + 1):
            taken[b] = s_txt
        good.append((s_ep, d_ep, (shi, slo), (dhi, dlo)))

    for bid, b in blocks.items():
        for pname, p in b["ports"].items():
            if p["dir"] == "inout":
                errors.append({"where": f"{bid}.{pname}", "msg": "inout ports are not supported"})
            if p["dir"] != "input" or pname == "clk":
                continue
            got = driven.get((bid, pname), {})
            miss = [k for k in range(p["width"]) if k not in got]
            if miss:
                where = f"{bid}.{pname}" + (f"[{miss[0]}]" if p["width"] > 1 else "")
                errors.append({"where": where, "msg": f"{where} is not driven: wire it, or tie it "
                               "off with a const block"})
    led = driven.get(("board", "led"), {})
    if len(led) < BOARD["led"][1] and blocks:
        free = [k for k in range(BOARD["led"][1]) if k not in led]
        warnings.append({"where": "board.led", "msg": f"LD{', LD'.join(map(str, free))} not driven: tied to 0"})
    for bid, b in blocks.items():
        outs = [p for p, v in b["ports"].items() if v["dir"] == "output"]
        used = {s[1] for s, _d, _a, _b in good if s[0] == bid}
        if outs and not used:
            warnings.append({"where": bid, "msg": f"{bid}: no output is used, synthesis will remove it"})
    return {"errors": errors, "warnings": warnings, "blocks": blocks, "pads": pads, "wires": good}


# --- the wrapper -------------------------------------------------------------------

def _sel(w, hi, lo):
    if hi == w - 1 and lo == 0:
        return ""
    return f"[{hi}]" if hi == lo else f"[{hi}:{lo}]"


def wrapper_text(bd, res, origin):
    """Verilog for the checked design `res` (from check())."""
    name = bd["name"]
    pads = sorted(res["pads"].items(), key=lambda kv: int(kv[0][3:]))
    lines = [f"// {name}_wrapper.v - {MARK} {origin}.",
             "// Do not edit: Generate wrapper in bob studio (or bd.py generate) rewrites it.",
             f"module {name}_wrapper (",
             "    input  wire       clk,",
             "    input  wire [1:0] sw,",
             "    input  wire [3:0] btn,",
             "    output wire [2:0] led" + ("," if pads else "")]
    for k, (pad, d) in enumerate(pads):
        lines.append(f"    {d:<6} wire       {pad}" + ("," if k < len(pads) - 1 else ""))
    lines.append(");")

    blocks = res["blocks"]
    decl = []
    for bid, b in blocks.items():
        for pname, p in b["ports"].items():
            if pname == "clk":
                continue
            rng = f"[{p['width'] - 1}:0] " if p["width"] > 1 else ""
            decl.append(f"    wire {rng}{bid}__{pname};")
    if decl:
        lines.append("")
        lines += decl

    def expr(ep, hi, lo):
        blk, port, _ = ep
        if blk == "board":
            w = BOARD[port][1] if port in BOARD else 1
            return port + _sel(w, hi, lo)
        return f"{blk}__{port}" + _sel(blocks[blk]["ports"][port]["width"], hi, lo)

    assigns = [f"    assign {expr(d, *dsel)} = {expr(s, *ssel)};" for s, d, ssel, dsel in res["wires"]]
    led = {b for s, d, _ss, (hi, lo) in res["wires"] if d[:2] == ("board", "led") for b in range(lo, hi + 1)}
    for k in range(BOARD["led"][1]):
        if k not in led:
            assigns.append(f"    assign led[{k}] = 1'b0;")
    for pad, d in pads:
        if d == "output" and not any(dd[:2] == ("board", pad) for _s, dd, _a, _b in res["wires"]):
            assigns.append(f"    assign {pad} = 1'b0;")
    if assigns:
        lines.append("")
        lines += assigns

    for bid, b in blocks.items():
        lines.append("")
        params = b["params"]
        head = f"    {b['module']}"
        if params:
            head += " #(" + ", ".join(f".{k}({int(v)})" for k, v in sorted(params.items())) + ")"
        conns = [f".{p}({'clk' if p == 'clk' else f'{bid}__{p}'})" for p in b["ports"]]
        lines.append(f"{head} {bid} (")
        lines += [f"        {c}" + ("," if i < len(conns) - 1 else "") for i, c in enumerate(conns)]
        lines.append("    );")
    lines.append("")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def pcf_text(bd, res):
    """Every port bit named, as a build with a .pcf requires (vpr_run.read_pcf)."""
    out = [f"# {bd['name']}.pcf - {MARK} the block design {bd['name']}; rewritten by Generate wrapper"]
    for k in range(2):
        out.append(f"set_io sw[{k}] SW{k}")
    for k in range(4):
        out.append(f"set_io btn[{k}] BTN{k}")
    for k in range(3):
        out.append(f"set_io led[{k}] LD{k}")
    for pad in sorted(res["pads"], key=lambda p: int(p[3:])):
        out.append(f"set_io {pad}[0] {pad}")
    return "\n".join(out) + "\n"


def generate(proj, bd_rel, set_top=False):
    """Check the project's block design bd_rel, then write bd/<name>_wrapper.v (and
    constrs/<name>.pcf when a pad is used), copy the IP it uses into ip/, and add all of
    it to the project. -> a summary; raises BdError with the check's errors."""
    import vpr_run
    bd_path = proj.abs(bd_rel)
    bd = load(bd_path)
    res = check(bd, proj)
    if res["errors"]:
        raise BdError("; ".join(f"{e['where']}: {e['msg']}" for e in res["errors"]))
    name = bd["name"]
    written = []
    # IP first: the wrapper instantiates it, and the project must build without software/bob/ip
    for b in res["blocks"].values():
        if b["kind"] == "ip":
            dst = os.path.join(proj.dir, "ip", os.path.basename(b["file"]))
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            if not os.path.exists(dst) or open(dst).read() != open(b["file"]).read():
                shutil.copy(b["file"], dst)
                written.append(proj.rel(dst))
            proj.add_source(dst)
    wpath = os.path.join(os.path.dirname(bd_path), f"{name}_wrapper.v")
    with open(wpath, "w") as fh:
        fh.write(wrapper_text(bd, res, proj.rel(bd_path)))
    written.append(proj.rel(wpath))
    wrel = proj.add_source(wpath)
    proj.add_bd(bd_rel)
    pcf_rel = None
    mine = os.path.join(proj.dir, "constrs", f"{name}.pcf")
    if res["pads"]:
        os.makedirs(os.path.dirname(mine), exist_ok=True)
        with open(mine, "w") as fh:
            fh.write(pcf_text(bd, res))
        vpr_run.read_pcf(mine)                 # it must parse the way the build reads it
        pcf_rel = proj.add_constraint(mine)
        proj.set_active_pcf(pcf_rel)
        written.append(pcf_rel)
    elif proj.data.get("active_pcf") == proj.rel(mine):
        proj.set_active_pcf(None)              # the convention pins need no file
    if set_top:
        proj.data["top"] = f"{name}_wrapper"
    proj.save()
    return {"wrapper": wrel, "top": f"{name}_wrapper", "pcf": pcf_rel, "written": written,
            "warnings": res["warnings"], "blocks": len(res["blocks"]), "wires": len(res["wires"])}


def new_bd(proj, name):
    """bd/<name>.bd, empty, added to the project."""
    if not ID.fullmatch(name or "") or name in RESERVED:
        raise BdError("a block design name is a Verilog identifier")
    path = os.path.join(proj.dir, "bd", f"{name}.bd")
    if os.path.exists(path):
        raise BdError(f"bd/{name}.bd already exists")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    save(path, empty(name))
    rel = proj.add_bd(proj.rel(path))
    proj.save()
    return rel


def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    for c in ("check", "generate"):
        s = sub.add_parser(c)
        s.add_argument("project")
        s.add_argument("bd", help="the .bd, relative to the project")
        if c == "generate":
            s.add_argument("--top", action="store_true", help="make the wrapper the top")
    a = ap.parse_args()
    try:
        proj = P.Project.open(a.project)
        if a.cmd == "check":
            res = check(load(proj.abs(a.bd)), proj)
            for e in res["errors"]:
                print(f"error   {e['where']}: {e['msg']}")
            for w in res["warnings"]:
                print(f"warning {w['where']}: {w['msg']}")
            return 1 if res["errors"] else 0
        print(json.dumps(generate(proj, a.bd, set_top=a.top), indent=1))
    except (BdError, P.ProjectError) as e:
        sys.exit(f"error: {e}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
