#!/usr/bin/env python3
"""
fabric_gen.py - hw/src/generated/bob_fabric.v from the device description (M7).

OpenFPGA's method, flattened: every routing-resource-graph node VPR built is a
wire, every node with drivers is a bob_mux reading its select bits from the
configuration chain, and every block is an instance whose pins are the IPIN /
OPIN wires. Nothing here decides architecture; software/bob/device.py does.

  r<id>       the wire of rr node <id> (CHANX, CHANY, IPIN, OPIN)
  m<id>       its mux (hw/src/fabric/bob_mux.v): value 0 const0, 1 const1 (IPIN
              only), then the inputs in ascending node id
"""


def _vec(nodes):
    """Verilog concatenation with nodes[0] as bit 0."""
    return "{" + ", ".join(f"r{n}" for n in reversed(nodes)) + "}"


def fabric_verilog(dev):
    rr = dev.rr
    L = []
    e = L.append
    npad, nclb = len(dev.pads), len(dev.by_type["clb"])
    nbram, ndsp = len(dev.by_type["bram"]), len(dev.by_type["dsp"])
    k = dev.lut_k

    e("// -----------------------------------------------------------------------------")
    e("// bob_fabric.v - GENERATED by software/bob/fabric_gen.py from software/bob/device.py")
    e(f"// and VPR's routing-resource graph (software/bob/arch/bob_k{k}_rr.xml.gz). Do not edit.")
    e("//")
    e(f"// {dev.name}: {dev.width} x {dev.height} grid, channel width {dev.arch['chan_width']} "
      f"(L{dev.arch['segment_length']} unidirectional, Wilton Fs={dev.arch['fs']}),")
    e(f"// {npad} pads, {nclb} CLBs (LUT{k}), {nbram} BRAMs, {ndsp} DSP slices, "
      f"{sum(m.node in rr.nodes for m in dev.muxes.values())} routing muxes, chain {dev.chain_width} bits.")
    e("// -----------------------------------------------------------------------------")
    e("")
    e("`timescale 1ns / 1ps")
    e("`default_nettype none")
    e('`include "bob_params.vh"')
    e("")
    e("/* verilator lint_off UNUSEDSIGNAL */")
    e("module bob_fabric (")
    e("    input  wire                                   clk,")
    e("    input  wire                                   gce,")
    e("    input  wire                                   gsr,")
    e("    input  wire                                   gwe,")
    e("    input  wire                                   cin,        // carry into every bottom-row CLB")
    e("    input  wire [`BOB_CHAIN_W-1:0]                cfg,")
    e("    input  wire                                   lck,        // M22: CFGLUT5 shift clock (TCK)")
    e("    input  wire                                   l_busy,     // M22: lut_loader.v")
    e("    input  wire                                   l_clr,")
    e("    input  wire [`BOB_FIDX_W-1:0]                 l_idx,")
    e("    input  wire [`BOB_FRAME_BITS-1:0]             l_buf,")
    e("    input  wire [4:0]                             l_cnt,")
    e("    input  wire [`BOB_NPAD-1:0]                   pad_in,")
    e("    output wire [`BOB_NPAD-1:0]                   pad_out,")
    e("    output wire [`BOB_NCAP-1:0]                   clb_o,")
    e("    input  wire [`BOB_NBRAM*64-1:0]               bram_drive,")
    e("    input  wire [`BOB_NBRAM-1:0]                  bram_init_go,")
    e("    input  wire                                   bram_init_wr,")
    e("    input  wire [`BOB_BRAM_ADDR_W-1:0]            bram_init_addr,")
    e("    input  wire [`BOB_BRAM_DATA_W-1:0]            bram_init_data,")
    e("    output wire [`BOB_NBRAM*`BOB_BRAM_DATA_W-1:0] bram_do_a,")
    e("    output wire [`BOB_NBRAM*`BOB_BRAM_DATA_W-1:0] bram_do_b,")
    e("    output wire [`BOB_NBRAM*`BOB_BRAM_DATA_W-1:0] bram_ram_a_q,")
    e("    input  wire [`BOB_NDSP*`BOB_DSP_DRIVE_W-1:0]  dsp_drive,")
    e("    output wire [`BOB_NDSP*48-1:0]                dsp_p")
    e(");")
    e("")

    wires = sorted(n.id for n in rr.nodes.values() if n.type in ("CHANX", "CHANY", "IPIN", "OPIN"))
    e(f"    // {len(wires)} routing-resource nodes")
    for i in range(0, len(wires), 12):
        e("    wire " + ", ".join(f"r{n}" for n in wires[i:i + 12]) + ";")
    e("")

    e("    // --- routing muxes -------------------------------------------------------")
    for m in sorted(dev.muxes.values(), key=lambda m: m.node):
        if m.node not in rr.nodes:
            continue                                  # a crossbar mux: inside bob_clb
        n = rr.nodes[m.node]
        e(f"    bob_mux #(.N({len(m.inputs)}), .W({m.width}), .C1({1 if m.base == 2 else 0})) "
          f"m{m.node} (.sel(cfg[{m.lo} +: {m.width}]), .in({_vec(m.inputs)}), .o(r{m.node}));"
          f"  // {n.type} ({n.xlow},{n.ylow})")
    e("")
    e("    // --- directs (carry, DSP cascade) and undriven nodes -----------------------")
    for ipin, opin in sorted(dev.direct.items()):
        e(f"    assign r{ipin} = r{opin};   // {dev.node_pin[ipin][0]}.{dev.node_pin[ipin][1]}"
          f" <- {dev.node_pin[opin][0]}.{dev.node_pin[opin][1]}")
    for nid in sorted(dev.undriven):
        pin = dev.node_pin.get(nid)
        if pin and pin[1] == "cin[0]":
            e(f"    assign r{nid} = cin;       // {pin[0]}.cin: bottom of a carry column")
        else:
            what = f"{pin[0]}.{pin[1]}" if pin else rr.nodes[nid].type
            e(f"    assign r{nid} = 1'b0;      // {what}: no driver in the rr graph")
    e("")

    P = lambda blk, pin: f"r{dev.pin_node[(blk, pin)]}"          # noqa: E731

    e("    // --- I/O pads -----------------------------------------------------------")
    for b in dev.pads:
        e(f"    assign {P(b.name, 'inpad[0]')} = pad_in[{b.index}];  "
          f"assign pad_out[{b.index}] = {P(b.name, 'outpad[0]')};   // {b.name}")
    e("")

    e("    // --- M22: the shared CFGLUT5 expander (hw/src/core/lut_expand.v) ------------")
    c = dev.cluster
    lay = dev.lutram_layout()
    ns = len(dev.xbar_sources(0, 0))
    nl = _xbar_luts(ns)
    e(f"    wire [{2 * lay['init_per_frame'] - 1}:0] l_cdi_init;")
    e(f"    wire [{lay['xbar_per_frame'] * nl - 1}:0] l_cdi_x;")
    e(f"    lut_expand #(.FB(`BOB_FRAME_BITS), .K({k}), .NI({lay['init_per_frame']}), .XW({dev.xbar_width()}), "
      f".NX({lay['xbar_per_frame']}), .S({ns})) u_lexp (")
    e("        .lbuf(l_buf), .cnt(l_cnt), .cdi_init(l_cdi_init), .cdi_x(l_cdi_x));")
    e("")
    e("    // --- CLBs (row-major); clb_o bit 2i+o = element i's out[o] = CAPTURE order ----")
    e("    // M22: lce[f] = the loader is shifting the CLB's L-frame f (or sweeping, JPROGRAM)")
    flags_w = c["n"] * dev.element_width()
    for b in dev.by_type["clb"]:
        lo = b.chain_lo
        f0 = lo // 128
        ins = _vec([dev.pin_node[(b.name, f"I[{j}]")] for j in range(c["i"])])
        outs = [dev.pin_node[(b.name, f"O[{m}]")] for m in range(2 * c["n"])]
        lce = "{" + ", ".join(f"l_busy & (l_clr | (l_idx == {f0 + f}))" for f in reversed(range(lay["frames"]))) + "}"
        t = f"x{b.x}y{b.y}"
        e(f"    wire [{lay['frames'] - 1}:0] lce_{t} = {lce};")
        e(f"    wire lck_{t};")
        e("`ifdef SIMULATION")
        e(f"    assign lck_{t} = lck & |lce_{t};   // simulation only: edges while this CLB loads (CFGLUT5s ignore the rest)")
        e("`else")
        e(f"    assign lck_{t} = lck;")
        e("`endif")
        e(f"    bob_clb u_clb_x{b.x}y{b.y} (.clk(clk), .gce(gce), .gsr(gsr), .gwe(gwe), "
          f".ce({P(b.name, 'ce[0]')}), .sr({P(b.name, 'sr[0]')}), .cin({P(b.name, 'cin[0]')}),")
        e(f"        .i({ins}),")
        e(f"        .cfg(cfg[{lo + lay['flags_lo']} +: {flags_w}]),   // frames {f0}..{f0 + lay['frames'] - 1}: L-frames")
        e(f"        .lck(lck_{t}), .lce(lce_{t}), .lcdi_init(l_cdi_init), .lcdi_x(l_cdi_x),")
        e(f"        .o({_vec(outs)}), .cout({P(b.name, 'cout[0]')}));")
        first = dev.elements[[el["clb"] for el in dev.elements].index(b.name)]["index"]
        e(f"    assign clb_o[{2 * first} +: {2 * c['n']}] = {_vec(outs)};")
    e("")

    e("    // --- BRAMs ---------------------------------------------------------------")
    for b in dev.by_type["bram"]:
        lo = b.chain_lo
        lsb = []                     # port A pins [31:0], port B [63:32], as the drive word
        for port in "ab":
            for name, w in (("addr", 10), ("di", 18), ("we", 1), ("en", 1), ("rst", 1), ("regce", 1)):
                lsb += [dev.pin_node[(b.name, f"{name}_{port}[{j}]")] for j in range(w)]
        do_a = [dev.pin_node[(b.name, f"do_a[{j}]")] for j in range(18)]
        do_b = [dev.pin_node[(b.name, f"do_b[{j}]")] for j in range(18)]
        i = b.index
        e(f"    wire [17:0] bram{i}_do_a, bram{i}_do_b;")
        e(f"    bram_block u_bram{i} (.sysclk(clk), .gce(gce), .gsr(gsr), .gwe(gwe), "
          f".cfg(cfg[{lo} +: `BOB_BRAM_CFG_W]),")
        e(f"        .pin({_vec(lsb)}),")
        e(f"        .drive(bram_drive[{64 * i} +: 64]), .init_go(bram_init_go[{i}]), .init_wr(bram_init_wr),")
        e("        .init_addr(bram_init_addr), .init_data(bram_init_data),")
        e(f"        .do_a(bram{i}_do_a), .do_b(bram{i}_do_b), .ram_a_q(bram_ram_a_q[{18 * i} +: 18]));")
        e(f"    assign {_vec(do_a)} = bram{i}_do_a;")
        e(f"    assign {_vec(do_b)} = bram{i}_do_b;")
        e(f"    assign bram_do_a[{18 * i} +: 18] = bram{i}_do_a;")
        e(f"    assign bram_do_b[{18 * i} +: 18] = bram{i}_do_b;")
    e("")

    e("    // --- DSP slices (dsp1.pcin <- dsp0.pcout through the direct above) ---------")
    for b in dev.by_type["dsp"]:
        lo, i = b.chain_lo, b.index
        bus = {}
        for name, w in (("a", 25), ("b", 18), ("c", 48), ("d", 25)):
            bus[name] = _vec([dev.pin_node[(b.name, f"{name}[{j}]")] for j in range(w)])
        ctl = _vec([dev.pin_node[(b.name, f"{n}[0]")] for n in
                    ("ce_ad", "ce_b", "ce_m", "ce_p", "rst_ad", "rst_b", "rst_m", "rst_p")])
        pcin = _vec([dev.pin_node[(b.name, f"pcin[{j}]")] for j in range(48)])
        p = [dev.pin_node[(b.name, f"p[{j}]")] for j in range(48)]
        pcout = [dev.pin_node[(b.name, f"pcout[{j}]")] for j in range(48)]
        e(f"    wire [47:0] dsp{i}_p;")
        e(f"    dsp_block u_dsp{i} (.sysclk(clk), .gce(gce), .gsr(gsr), .gwe(gwe), "
          f".cfg(cfg[{lo} +: `BOB_DSP_CFG_W]),")
        e(f"        .a({bus['a']}),")
        e(f"        .b({bus['b']}),")
        e(f"        .c({bus['c']}),")
        e(f"        .d({bus['d']}),")
        e(f"        .ctrl({ctl}), .pcin({pcin}),")
        e(f"        .drive(dsp_drive[{124 * i} +: 124]), .p(dsp{i}_p));")
        e(f"    assign {_vec(p)} = dsp{i}_p;")
        e(f"    assign {_vec(pcout)} = dsp{i}_p;")
        e(f"    assign dsp_p[{48 * i} +: 48] = dsp{i}_p;")
    e("")
    e("endmodule")
    e("/* verilator lint_on UNUSEDSIGNAL */")
    e("")
    L.extend(cluster_verilog(dev))
    e("`default_nettype wire")
    return "\n".join(L) + "\n"


def _xbar_luts(ns):
    """CFGLUT5s in one crossbar mux of ns sources (hw/src/clb/lxmux.v)."""
    leaves = -(-ns // 5)
    return leaves + 1 if leaves > 1 else 1


def cluster_verilog(dev):
    """bob_clb: N elements (hw/src/clb/ble.sv) behind the local crossbar, one lxmux (a
    CFGLUT5 tree, M22) per element input over device.xbar_sources, and the carry
    cin -> e0 -> ... -> e<N-1> -> cout. Generated, because the crossbar's population and
    the L-frame layout are architecture parameters (device.py CLUSTER, lutram_layout)."""
    c, k = dev.cluster, dev.lut_k
    n, ni = c["n"], c["i"]
    ew, xw = dev.element_width(), dev.xbar_width()
    lay = dev.lutram_layout()
    ns = len(dev.xbar_sources(0, 0))
    nl = _xbar_luts(ns)
    if ns > 25:
        raise ValueError(f"crossbar of {ns} sources: lxmux.v's two-level tree holds at most 25")
    L = []
    e = L.append
    e("// -----------------------------------------------------------------------------")
    e(f"// bob_clb - the cluster: {n} logic elements (LUT{k}, fracturable, 2 FFs), {ni} inputs,")
    e(f"// {2 * n} outputs, a {c['xbar']} crossbar of {ns}:1 muxes per element input.")
    e(f"// M22: LUT contents and crossbar in CFGLUT5 ({2 * n + n * k * nl} per CLB), loaded by")
    e(f"// hw/src/core/lut_loader.v from the CLB's L-frames: lce[f] shifts frame f")
    e(f"// (INIT frames 0..{lay['init_frames'] - 1}, crossbar frames {lay['init_frames']}..{lay['frames'] - 1}), "
      "lcdi_* are the shared expander's")
    e(f"// bits (lut_expand.v). cfg: the element flags, element e at [{ew}e +: {ew}] (BOB_ELE_*).")
    e("// -----------------------------------------------------------------------------")
    e("/* verilator lint_off DECLFILENAME */")
    e("module bob_clb (")
    e("    input  wire              clk, gce, gsr, gwe, ce, sr, cin,")
    e(f"    input  wire [{ni - 1}:0]       i,")
    e(f"    input  wire [{n * ew - 1}:0]       cfg,")
    e("    input  wire              lck,")
    e(f"    input  wire [{lay['frames'] - 1}:0]        lce,")
    e(f"    input  wire [{2 * lay['init_per_frame'] - 1}:0]        lcdi_init,")
    e(f"    input  wire [{lay['xbar_per_frame'] * nl - 1}:0]      lcdi_x,")
    e(f"    output wire [{2 * n - 1}:0]       o,")
    e("    output wire              cout")
    e(");")
    e("    /* verilator lint_off UNUSEDSIGNAL */")
    e("    wire _unused = &{1'b0, lcdi_init, lcdi_x};     // not every slot is used by every CLB frame")
    e("    /* verilator lint_on UNUSEDSIGNAL */")
    e(f"    wire [{n}:0] cy;")
    e("    assign cy[0] = cin;")
    e(f"    assign cout  = cy[{n}];")
    for el in range(n):
        f_init, slot = divmod(el, lay["init_per_frame"])
        e(f"    // element {el}: INIT in L-frame {f_init} slot {slot}")
        e(f"    wire [{k - 1}:0] x{el};")
        for j in range(k):
            srcs = dev.xbar_sources(el, j)
            vec = "{" + ", ".join(f"i[{p[2:-1]}]" if p.startswith("I") else f"o[{p[2:-1]}]"
                                  for p in reversed(srcs)) + "}"
            fx, t = divmod(el * k + j, lay["xbar_per_frame"])
            e(f"    lxmux #(.S({len(srcs)})) m{el}_{j} (.in({vec}), .lck(lck), "
              f".lce(lce[{lay['init_frames'] + fx}]), .lcdi(lcdi_x[{t * nl} +: {nl}]), .o(x{el}[{j}]));")
        e(f"    ble u_e{el} (.clk(clk), .gce(gce), .ce(ce), .sr(sr), .gsr(gsr), .gwe(gwe), "
          f".i(x{el}), .cin(cy[{el}]), .cfg(cfg[{el * ew} +: {ew}]),")
        e(f"        .lck(lck), .lce(lce[{f_init}]), .lcdi(lcdi_init[{2 * slot} +: 2]),")
        e(f"        .o(o[{2 * el}]), .o2(o[{2 * el + 1}]), .cout(cy[{el + 1}]));")
    e("endmodule")
    e("/* verilator lint_on DECLFILENAME */")
    e("")
    return L
