#!/usr/bin/env python3
"""
vpr_arch.py - bob's VPR architecture file, derived from OpenFPGA's regression-
tested k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_fracff_40nm.xml.

What is kept from the reference (so VPR/OpenFPGA's tileable rr-graph builder is
exercised exactly as upstream tests it):
  layout      tileable="true" through_channel="false" concat_pass_wire="true",
              io perimeter, EMPTY corners, clb fill, hard-block columns
  routing     one L4 unidirectional segment, sb/cb pattern all 1, Wilton Fs=3,
              mux switch "0" for wires, "ipin_cblock" for connection boxes
  fc          in 0.15 / out 0.10 (frac); carry and clock pins fc 0
  carry       a direct connection clb.cout -> clb.cin

Where bob diverges (and why):
  clb         ONE BLE per tile (bob's CLB: LUT K + FF with CE/SR + carry), so the
              tile pins are I[K-1:0], ce, sr, cin | O, O5, cout. N10 with local
              interconnect is far too many configuration flip-flops for a
              fabric emulated on an XC7Z020.
  carry       runs South to North (cin at the bottom, y_offset +1), as bob's
              fabric always has.
  memory      bob's RAMB18-style 1024 x 18 true dual port (UG473), not the
              1024 x 8 simple dual port.
  dsp         bob's DSP48E1-style slice (UG479 trimmed) with a PCOUT -> PCIN
              direct up the column, not the combinational mult_36.

The routing-resource graph VPR builds from this file is the fabric: every
CHANX/CHANY/IPIN node with more than one driver becomes a configuration mux in
the generated RTL (software/bob/fabric_gen.py), which is OpenFPGA's method.
"""

from xml.sax.saxutils import quoteattr


def _pins(ports):
    """ports: [(dir, name, width)] -> tile/pb_type port lines"""
    out = []
    for d, name, w in ports:
        tag = {"in": "input", "out": "output", "clk": "clock"}[d]
        out.append(f'<{tag} name="{name}" num_pins="{w}"/>')
    return out


def arch_xml(dev):
    """VPR architecture XML text for a Device (software/bob/device.py)."""
    a = dev.arch
    k = dev.lut_k
    W, H = a["vpr_width"], a["vpr_height"]
    L = []
    e = L.append

    e('<?xml version="1.0"?>')
    # No file paths in this header. Its text is hashed into the rr-graph stamp, so a
    # path here means moving a folder invalidates a routing graph that did not change -
    # which is exactly what happened when tools/ became software/.
    e("<!-- GENERATED by vpr_arch.py from the bob device description - do not edit -->")
    e(f'<!-- bob: chan_width="{a["chan_width"]}" lut_k="{k}" (vpr_rrgraph.sh reads this line) -->')
    e("<architecture>")

    # --- models ---------------------------------------------------------------
    e("  <models>")
    for m in dev.vpr_models():
        e(f'    <model name="{m["name"]}">')
        e("      <input_ports>")
        for name, _w, attrs in m["inputs"]:
            e(f'        <port name="{name}"{attrs}/>')
        e("      </input_ports>")
        e("      <output_ports>")
        for name, _w, attrs in m["outputs"]:
            e(f'        <port name="{name}"{attrs}/>')
        e("      </output_ports>")
        e("    </model>")
    e("  </models>")

    # --- tiles ----------------------------------------------------------------
    e("  <tiles>")
    for t in dev.vpr_tiles():
        hattr = f' height="{t["height"]}"' if t["height"] > 1 else ""
        cap = f' capacity="{t["capacity"]}"' if t["capacity"] > 1 else ""
        e(f'    <tile name="{t["name"]}"{hattr} area="0">')
        e(f'      <sub_tile name="{t["name"]}"{cap}>')
        e(f'        <equivalent_sites><site pb_type="{t["name"]}" pin_mapping="direct"/></equivalent_sites>')
        for d, name, w in t["ports"]:
            tag = {"in": "input", "out": "output", "clk": "clock"}[d]
            eq = ' equivalent="full"' if name in t.get("equivalent", ()) else ""
            e(f'        <{tag} name="{name}" num_pins="{w}"{eq}/>')
        e(f'        <fc in_type="frac" in_val="{a["fc_in"]}" out_type="frac" out_val="{a["fc_out"]}">')
        for p in t["fc0"]:
            e(f'          <fc_override port_name="{p}" fc_type="frac" fc_val="0"/>')
        e("        </fc>")
        if t["pinloc"] == "spread":
            e('        <pinlocations pattern="spread"/>')
        else:
            e('        <pinlocations pattern="custom">')
            for side, yoff, pins in t["pinloc"]:
                y = f' yoffset="{yoff}"' if yoff else ""
                e(f'          <loc side="{side}"{y}>{" ".join(pins)}</loc>')
            e("        </pinlocations>")
        e("      </sub_tile>")
        e("    </tile>")
    e("  </tiles>")

    # --- layout ---------------------------------------------------------------
    e('  <layout tileable="true" through_channel="false" concat_pass_wire="true">')
    e(f'    <fixed_layout name="{dev.name}" width="{W}" height="{H}">')
    e('      <perimeter type="io" priority="100"/>')
    e('      <corners type="EMPTY" priority="101"/>')
    e('      <fill type="clb" priority="10"/>')
    for col in a["columns"]:
        e(f'      <col type="{col["type"]}" startx="{col["x"]}" starty="1" priority="20"/>')
        e(f'      <col type="EMPTY" startx="{col["x"]}" starty="1" priority="19"/>')
    e("    </fixed_layout>")
    e("  </layout>")

    # --- device / switches / segments / directs (reference values) -------------
    e("  <device>")
    e('    <sizing R_minW_nmos="8926" R_minW_pmos="16067"/>')
    e('    <area grid_logic_tile_area="0"/>')
    e('    <chan_width_distr><x distr="uniform" peak="1.000000"/><y distr="uniform" peak="1.000000"/></chan_width_distr>')
    e(f'    <switch_block type="wilton" fs="{a["fs"]}"/>')
    e('    <connection_block input_switch_name="ipin_cblock"/>')
    e("  </device>")
    e("  <switchlist>")
    e('    <switch type="mux" name="0" R="551" Cin=".77e-15" Cout="4e-15" Tdel="58e-12" '
      'mux_trans_size="2.630740" buf_size="27.645901"/>')
    e('    <switch type="mux" name="ipin_cblock" R="2231.5" Cout="0." Cin="1.47e-15" '
      'Tdel="7.247000e-11" mux_trans_size="1.222260" buf_size="auto"/>')
    e("  </switchlist>")
    e("  <segmentlist>")
    seg = a["segment_length"]
    e(f'    <segment name="L{seg}" freq="1.000000" length="{seg}" type="unidir" Rmetal="101" Cmetal="22.5e-15">')
    e('      <mux name="0"/>')
    e(f'      <sb type="pattern">{" ".join(["1"] * (seg + 1))}</sb>')
    e(f'      <cb type="pattern">{" ".join(["1"] * seg)}</cb>')
    e("    </segment>")
    e("  </segmentlist>")
    e("  <directlist>")
    for d in dev.vpr_directs():
        e(f'    <direct name="{d["name"]}" from_pin="{d["from"]}" to_pin="{d["to"]}" '
          f'x_offset="{d["dx"]}" y_offset="{d["dy"]}" z_offset="0"/>')
    e("  </directlist>")

    # --- complex blocks ---------------------------------------------------------
    e("  <complexblocklist>")
    L.extend("    " + x for x in _io_pb())
    L.extend("    " + x for x in _clb_pb(k))
    for t in dev.vpr_tiles():
        if t["name"] in ("io", "clb"):
            continue
        L.extend("    " + x for x in _hard_pb(t))
    e("  </complexblocklist>")
    e("</architecture>")
    return "\n".join(L) + "\n"


def _io_pb():
    return [
        '<pb_type name="io">',
        '  <input name="outpad" num_pins="1"/>',
        '  <output name="inpad" num_pins="1"/>',
        '  <mode name="inpad">',
        '    <pb_type name="inpad" blif_model=".input" num_pb="1"><output name="inpad" num_pins="1"/></pb_type>',
        '    <interconnect><direct name="inpad" input="inpad.inpad" output="io.inpad">',
        '      <delay_constant max="4.243e-11" in_port="inpad.inpad" out_port="io.inpad"/></direct></interconnect>',
        '  </mode>',
        '  <mode name="outpad">',
        '    <pb_type name="outpad" blif_model=".output" num_pb="1"><input name="outpad" num_pins="1"/></pb_type>',
        '    <interconnect><direct name="outpad" input="io.outpad" output="outpad.outpad">',
        '      <delay_constant max="1.394e-11" in_port="io.outpad" out_port="outpad.outpad"/></direct></interconnect>',
        '  </mode>',
        '</pb_type>',
    ]


def _ff_pb():
    """bob's flip-flop: FDRE or FDSE (UG474) with CE and SR from the tile pins. One
    primitive, bob_ff; which of the two it is travels as a netlist parameter
    (software/bob/vpr_run.py), because VPR forbids a pack pattern into a multi-mode ff."""
    return ['  <pb_type name="ff" blif_model=".subckt bob_ff" num_pb="1">',
            '    <input name="D" num_pins="1" port_class="D"/>',
            '    <input name="CE" num_pins="1"/>',
            '    <input name="SR" num_pins="1"/>',
            '    <output name="Q" num_pins="1" port_class="Q"/>',
            '    <clock name="C" num_pins="1" port_class="clock"/>',
            '    <T_setup value="66e-12" port="ff.D" clock="C"/>',
            '    <T_setup value="66e-12" port="ff.CE" clock="C"/>',
            '    <T_setup value="66e-12" port="ff.SR" clock="C"/>',
            '    <T_clock_to_Q max="124e-12" port="ff.Q" clock="C"/>',
            '  </pb_type>']


def _clb_pb(k):
    """bob's CLB: one BLE, two modes (as the reference's fle has n1_lut6 and arithmetic).

      logic       .names LUT K -> optional FF; O = FF.Q or LUT out
      arithmetic  bob_add (the LUT computing A^B plus MUXCY/XORCY, DI = I0 = A)
                  -> optional FF; O = FF.Q or sum; cin/cout on the carry direct

    O5 is not offered to VPR (one function per CLB); the M8 hand placer still uses it.
    The tile pins are exactly M7's, so the rr graph - and the fabric - do not change."""
    lut_delay = "\n".join(["261e-12"] * k)
    head = [
        '<pb_type name="clb">',
        f'  <input name="I" num_pins="{k}"/>',
        '  <input name="ce" num_pins="1"/>',
        '  <input name="sr" num_pins="1"/>',
        '  <input name="cin" num_pins="1"/>',
        '  <output name="O" num_pins="1"/>',
        '  <output name="O5" num_pins="1"/>',
        '  <output name="cout" num_pins="1"/>',
        '  <clock name="clk" num_pins="1"/>',
    ]
    ctl = ['    <direct name="ff_ce" input="clb.ce" output="ff.CE"/>',
           '    <direct name="ff_sr" input="clb.sr" output="ff.SR"/>',
           '    <direct name="ff_c" input="clb.clk" output="ff.C"/>']
    logic = ['<mode name="logic">',
             f'  <pb_type name="lut" blif_model=".names" num_pb="1" class="lut">',
             f'    <input name="in" num_pins="{k}" port_class="lut_in"/>',
             '    <output name="out" num_pins="1" port_class="lut_out"/>',
             f'    <delay_matrix type="max" in_port="lut.in" out_port="lut.out">{lut_delay}</delay_matrix>',
             '  </pb_type>']
    logic += _ff_pb()
    logic += ['  <interconnect>',
              '    <direct name="lut_in" input="clb.I" output="lut.in"/>',
              '    <direct name="ff_d" input="lut.out" output="ff.D">',
              '      <pack_pattern name="ble" in_port="lut.out" out_port="ff.D"/>',
              '    </direct>'] + ctl + [
              '    <mux name="o" input="ff.Q lut.out" output="clb.O">',
              '      <delay_constant max="25e-12" in_port="lut.out" out_port="clb.O"/>',
              '      <delay_constant max="45e-12" in_port="ff.Q" out_port="clb.O"/>',
              '    </mux>',
              '  </interconnect>',
              '</mode>']
    arith = ['<mode name="arithmetic">',
             '  <pb_type name="add" blif_model=".subckt bob_add" num_pb="1">',
             '    <input name="a" num_pins="1"/>',
             '    <input name="b" num_pins="1"/>',
             '    <input name="cin" num_pins="1"/>',
             '    <output name="cout" num_pins="1"/>',
             '    <output name="sumout" num_pins="1"/>']
    for i in ("a", "b", "cin"):
        for o in ("sumout", "cout"):
            dly = "0.01e-9" if (i, o) == ("cin", "cout") else "0.3e-9"
            arith.append(f'    <delay_constant max="{dly}" in_port="add.{i}" out_port="add.{o}"/>')
    arith.append('  </pb_type>')
    arith += _ff_pb()
    arith += ['  <interconnect>',
              '    <direct name="a" input="clb.I[0]" output="add.a"/>',
              '    <direct name="b" input="clb.I[1]" output="add.b"/>',
              '    <direct name="cin" input="clb.cin" output="add.cin">',
              '      <pack_pattern name="chain" in_port="clb.cin" out_port="add.cin"/>',
              '    </direct>',
              '    <direct name="cout" input="add.cout" output="clb.cout">',
              '      <pack_pattern name="chain" in_port="add.cout" out_port="clb.cout"/>',
              '    </direct>',
              '    <direct name="ff_d" input="add.sumout" output="ff.D">',
              '      <pack_pattern name="chain" in_port="add.sumout" out_port="ff.D"/>',
              '    </direct>'] + ctl + [
              '    <mux name="o" input="ff.Q add.sumout" output="clb.O">',
              '      <delay_constant max="25e-12" in_port="add.sumout" out_port="clb.O"/>',
              '      <delay_constant max="45e-12" in_port="ff.Q" out_port="clb.O"/>',
              '    </mux>',
              '  </interconnect>',
              '</mode>']
    return head + ["  " + x for x in logic + arith] + ['</pb_type>']


def _hard_pb(t):
    """A hard block (bram, dsp): one primitive, every tile port passed straight through."""
    name, model = t["name"], t["model"]
    prim = f"{name}_prim"
    out = [f'<pb_type name="{name}">']
    out += ["  " + x for x in _pins(t["ports"])]
    out.append(f'  <mode name="{name}">')
    out.append(f'    <pb_type name="{prim}" blif_model=".subckt {model}" num_pb="1">')
    clk = next(n for d, n, _w in t["ports"] if d == "clk")
    for d, n, w in t["ports"]:
        tag = {"in": "input", "out": "output", "clk": "clock"}[d]
        out.append(f'      <{tag} name="{n}" num_pins="{w}"/>')
    for d, n, w in t["ports"]:
        if n in t.get("comb_in", ()):
            continue
        if d == "in":
            out.append(f'      <T_setup value="500e-12" port="{prim}.{n}" clock="{clk}"/>')
        elif d == "out":
            out.append(f'      <T_clock_to_Q max="1e-9" port="{prim}.{n}" clock="{clk}"/>')
    for src, dst in t.get("comb", ()):
        out.append(f'      <delay_constant max="2e-9" in_port={quoteattr(prim + "." + src)} '
                   f'out_port={quoteattr(prim + "." + dst)}/>')
    out.append("    </pb_type>")
    out.append("    <interconnect>")
    for d, n, w in t["ports"]:
        if d == "out":
            out.append(f'      <direct name="{n}" input="{prim}.{n}" output="{name}.{n}"/>')
        else:
            out.append(f'      <direct name="{n}" input="{name}.{n}" output="{prim}.{n}"/>')
    out.append("    </interconnect>")
    out.append("  </mode>")
    out.append("</pb_type>")
    return out
