// traffic_bd_wrapper.v - generated by bob from bd/traffic_bd.bd.
// Do not edit: Generate wrapper in bob studio (or bd.py generate) rewrites it.
module traffic_bd_wrapper (
    input  wire       clk,
    input  wire [1:0] sw,
    input  wire [3:0] btn,
    output wire [2:0] led
);

    wire slow__tick;
    wire fast__tick;
    wire rate__a;
    wire rate__b;
    wire rate__sel;
    wire rate__y;
    wire walk_btn__d;
    wire walk_btn__q;
    wire timer__tick;
    wire timer__load;
    wire [3:0] timer__len;
    wire [3:0] timer__left;
    wire [3:0] ctrl__left;
    wire ctrl__walk;
    wire ctrl__night;
    wire [2:0] ctrl__lamps;
    wire ctrl__load;
    wire [3:0] ctrl__len;
    wire night__tick;
    wire [2:0] night__lamps;
    wire [2:0] lamp__a;
    wire [2:0] lamp__b;
    wire lamp__sel;
    wire [2:0] lamp__y;

    assign rate__a = slow__tick;
    assign rate__b = fast__tick;
    assign rate__sel = sw[1];
    assign timer__tick = rate__y;
    assign night__tick = rate__y;
    assign walk_btn__d = btn[0];
    assign ctrl__walk = walk_btn__q;
    assign ctrl__left = timer__left;
    assign timer__load = ctrl__load;
    assign timer__len = ctrl__len;
    assign ctrl__night = sw[0];
    assign lamp__a = ctrl__lamps;
    assign lamp__b = night__lamps;
    assign lamp__sel = sw[0];
    assign led = lamp__y;

    ip_clkdiv #(.N(4)) slow (
        .clk(clk),
        .tick(slow__tick)
    );

    ip_clkdiv #(.N(2)) fast (
        .clk(clk),
        .tick(fast__tick)
    );

    ip_mux2 #(.W(1)) rate (
        .a(rate__a),
        .b(rate__b),
        .sel(rate__sel),
        .y(rate__y)
    );

    ip_debounce #(.N(1)) walk_btn (
        .clk(clk),
        .d(walk_btn__d),
        .q(walk_btn__q)
    );

    phase_timer timer (
        .clk(clk),
        .tick(timer__tick),
        .load(timer__load),
        .len(timer__len),
        .left(timer__left)
    );

    traffic_fsm ctrl (
        .clk(clk),
        .left(ctrl__left),
        .walk(ctrl__walk),
        .night(ctrl__night),
        .lamps(ctrl__lamps),
        .load(ctrl__load),
        .len(ctrl__len)
    );

    night_flash night (
        .clk(clk),
        .tick(night__tick),
        .lamps(night__lamps)
    );

    ip_mux2 #(.W(3)) lamp (
        .a(lamp__a),
        .b(lamp__b),
        .sel(lamp__sel),
        .y(lamp__y)
    );

endmodule
