#!/usr/bin/env python3
"""
compare.py - bob's Python PnR against VPR, measured the same way (M12a).

  tools/bob/pnr/compare.py [--seed N] [--out docs/reports/M12/pnr_vs_vpr.md]

For every example and variant: VPR's committed result (tools/bob/vpr/<name>/) and a
fresh Python PnR run (build/pnr/<name>/). Both are measured by the same code from
their .place and .route files:

  CLBs            clusters placed on CLB sites
  bb cost         sum over routed nets of the placement bounding-box half-perimeter
  wirelength      sum over used CHANX/CHANY nodes of their span in grid units
                  (VPR's own "Total wirelength" is printed next to it)
  wires, muxes    routing wire nodes used; routing muxes the FASM sets
  run time        Python pack+place+route; VPR's whole flow from its log (in Docker,
                  under amd64 emulation - not a fair speed comparison)

Both results must pass fasm_from_vpr.check_model (the chain on model.py == the
source trace) or the row is marked FAIL.
"""

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BOB = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(BOB))
sys.path.insert(0, BOB)
sys.path.insert(0, os.path.join(ROOT, "host"))

import bitstream as B  # noqa: E402
import fasm_from_vpr as FV  # noqa: E402
import vpr_run  # noqa: E402
from pnr import run as pnr_run  # noqa: E402


def measure(work, name, top):
    place = FV.read_place(os.path.join(work, f"{name}.place"))
    routes = FV.read_route(os.path.join(work, f"{name}.route"))
    net = open(os.path.join(work, f"{name}.net")).read()
    used = set()
    for branches in routes.values():
        for node, _kind in branches[0]:
            if node in B.NODE:
                used.add(node)
    chan = [n for n in used if B.NODE[n][1] in ("CHANX", "CHANY")]
    wl = sum(B.NODE[n][4] - B.NODE[n][2] + B.NODE[n][5] - B.NODE[n][3] + 1 for n in chan)
    # bounding boxes from the route's own terminals: the blocks of each routed net's pins
    bb = 0
    for branches in routes.values():
        pins = [n for n, k in branches[0] if k in ("OPIN", "IPIN") and n in B.NODE]
        xs = [B.NODE[n][2] for n in pins]
        ys = [B.NODE[n][3] for n in pins]
        if xs:
            bb += (max(xs) - min(xs)) + (max(ys) - min(ys))
    bs, contents, text = FV.build(name, work)
    bad, n, _tr = FV.check_model(name, bs, contents, work, top)
    return {"clbs": net.count('instance="clb['), "bb": bb, "wl": wl, "wires": len(chan),
            "muxes": sum(1 for l in text.splitlines() if l.startswith("rr")), "nets": len(routes),
            "ok": not bad, "samples": 2 * n}


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "reports", "M12", "pnr_vs_vpr.md"))
    args = ap.parse_args()
    rows, tot = [], {"v": 0, "p": 0}
    for name in vpr_run.EXAMPLES + list(vpr_run.VARIANTS):
        top, pcf = vpr_run.VARIANTS.get(name, (name, None))
        why = vpr_run.stale(name)
        if why:
            print(f"FAIL  {name}: {why}")
            return 1
        vwork = os.path.join(vpr_run.RESULTS, name)
        pwork, st = pnr_run.run(top, args.seed, pcf, name)
        v, p = measure(vwork, name, top), measure(pwork, name, top)
        stamp = vpr_run.read_stamp(name)
        rows.append((name, v, p, st, stamp))
        tot["v"] += v["wl"]
        tot["p"] += p["wl"]
        print(f"{'PASS' if v['ok'] and p['ok'] else 'FAIL'}  {name:14s} CLBs {v['clbs']:2d}/{p['clbs']:2d}  "
              f"bb {v['bb']:3d}/{p['bb']:3d}  wirelength {v['wl']:3d}/{p['wl']:3d} "
              f"({p['wl'] / max(1, v['wl']):.2f}x)  wires {v['wires']:3d}/{p['wires']:3d}  "
              f"muxes {v['muxes']:3d}/{p['muxes']:3d}  python {st['place_s'] + st['route_s'] + st['pack_s']:.2f} s, "
              f"{st['iterations']} routing iterations   (VPR/Python)")
    ratio = tot["p"] / max(1, tot["v"])
    L = ["# M12a: bob's Python PnR against VPR",
         "",
         f"Generated by `tools/bob/pnr/compare.py --seed {args.seed}`. Same netlist (`vpr_run.prepare`), "
         f"same pins, same rr graph (`{B.DEVICE['name']}`: {len(B.CLBS)} CLBs, W = {B.DEVICE['arch']['chan_width']}); "
         "both results measured by the same code from their `.place` / `.route` files, and both chains "
         "checked on `model.py` against the source trace.",
         "",
         "| design | CLBs VPR / Py | bb cost VPR / Py | wirelength VPR / Py | ratio | wires VPR / Py | routing muxes VPR / Py | Py routing iterations | Py time | model == source |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for name, v, p, st, stamp in rows:
        L.append(f"| {name} | {v['clbs']} / {p['clbs']} | {v['bb']} / {p['bb']} | {v['wl']} / {p['wl']} | "
                 f"{p['wl'] / max(1, v['wl']):.2f} | {v['wires']} / {p['wires']} | {v['muxes']} / {p['muxes']} | "
                 f"{st['iterations']} | {st['pack_s'] + st['place_s'] + st['route_s']:.2f} s | "
                 f"{'VPR ✓ Py ✓' if v['ok'] and p['ok'] else 'FAIL'} ({p['samples']} samples) |")
    L += ["", f"**Total wirelength: VPR {tot['v']}, Python {tot['p']} ({ratio:.2f}×).**", "",
          "Notes:",
          "- wirelength here is the grid span of every used CHANX/CHANY node, computed identically for both; "
          "VPR's own log figure (`Total wirelength`) counts differently and is not used for the ratio.",
          "- bb cost is recomputed from each route's pin nodes, so it is comparable between the two flows.",
          "- VPR's timing-driven router also optimises delay; the Python router optimises congestion and "
          "wirelength only.", ""]
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    open(args.out, "w").write("\n".join(L))
    print(f"total wirelength VPR {tot['v']}, Python {tot['p']} ({ratio:.2f}x) -> {os.path.relpath(args.out, ROOT)}")
    return 0 if all(v["ok"] and p["ok"] for _n, v, p, _s, _t in rows) else 1


if __name__ == "__main__":
    sys.exit(main())
