#!/usr/bin/env python3
"""Collect every number the film shows into data/facts.json.

Sources (all in this repository):
  software/bob/device.json         the device (generated by software/bob/device.py)
  hw/build.cfg                     the IDCODE of the board build
  hw/src/core/jtag_tap6.v          the instruction codes
  hw/src/core/cfg_frames.v         packet registers and commands
  hw/src/core/cfg_ctrl.v           CRC constants
  docs/reports/M26/util.rpt        Vivado utilisation
  docs/reports/M26/timing.rpt      Vivado timing
  docs/hwtest/results.log          the last M26 board run
  example/ at commit c072b6d       the counter through every stage of the flow

Fails loudly if anything is missing, so the film never shows a stale or guessed number.
"""

import json
import os
import re
import subprocess
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, ".."))
EXAMPLE_REV = "c072b6d"


def rd(path):
    with open(os.path.join(REPO, path)) as fh:
        return fh.read()


def git_show(path):
    return subprocess.run(["git", "-C", REPO, "show", f"{EXAMPLE_REV}:{path}"],
                          check=True, capture_output=True, text=True).stdout


def need(cond, what):
    if not cond:
        sys.exit(f"facts.py: {what}")


def device():
    d = json.loads(rd("software/bob/device.json"))
    arch = d["arch"]
    heights = {c["type"]: c["height"] for c in arch["columns"]}
    blocks = []
    for b in d["blocks"]:
        e = {"name": b["name"], "type": b["type"], "x": b["x"], "y": b["y"]}
        if b["type"] in heights:
            e["h"] = heights[b["type"]]
        blocks.append(e)
    count = Counter(b["type"] for b in d["blocks"])
    tt = d["tile_types"]
    clb_fields = [(f["name"], f["width"], f["offset"], f.get("kind")) for f in tt["clb"]["fields"]]
    e0 = [(n[3:], w, o, k) for n, w, o, k in clb_fields if n.startswith("e0.")]
    elem_bits = sum(w for _, w, _, _ in e0)
    muxes = d["rr"]["muxes"]
    mux_bits = sum(m[2] for m in muxes)
    fanin = Counter(len(m[4]) for m in muxes)
    node_types = Counter(n[1] for n in d["rr"]["nodes"])
    return {
        "name": d["name"], "lut_k": d["lut_k"], "arch": arch, "clock": d["clock"],
        "blocks": blocks,
        "count": {"clb": count["clb"], "io": count["io"], "bram": count["bram"],
                  "dsp": count["dsp"], "elements": count["clb"] * d["cluster"]["n"],
                  "luts": count["clb"] * d["cluster"]["n"]},
        "tile_widths": {k: v["width"] for k, v in tt.items()},
        "element_fields": e0, "element_bits": elem_bits,
        "clb_fields_n": len(clb_fields),
        "bram_fields": [(f["name"], f["width"]) for f in tt["bram"]["fields"]],
        "dsp_fields": [(f["name"], f["width"]) for f in tt["dsp"]["fields"]],
        "ctrl_fields": [(f["name"], f["width"]) for f in tt["ctrl"]["fields"]],
        "block_ports": d["block_ports"],
        "chain_width": d["chain"]["width"],
        "frames": {"words": d["frames"]["words"], "bits": d["frames"]["bits"],
                   "count": d["frames"]["count"], "columns": d["frames"]["columns"]},
        "lframes": len(d["lframes"]["list"]),
        "cluster": {k: d["cluster"][k] for k in ("n", "i", "xbar", "frac", "xbar_width")},
        "cfglut5_per_clb": d["cluster"]["lutram"]["cfglut5_per_clb"],
        "lutram": d["cluster"]["lutram"],
        "xbar_sources": len(d["cluster"]["xbar_sources"][0][0]),
        "capture_width": d["capture"]["width"],
        "bsr_width": d["bsr"]["width"],
        "pads": {"count": d["pads"]["count"], "xy": {str(p["pad"]): [p["x"], p["y"]] for p in d["pads"]["io"]},
                 "inputs": d["pads"]["board_inputs"],
                 "outputs": d["pads"]["board_outputs"]},
        "rr": {"nodes": len(d["rr"]["nodes"]), "muxes": len(muxes), "mux_bits": mux_bits,
               "directs": len(d["rr"]["directs"]), "node_types": dict(node_types),
               "fanin_max": max(fanin), "fanin_hist": {str(k): v for k, v in sorted(fanin.items())}},
        "bram": {k: d["bram"][k] for k in ("count", "addr_w", "data_w", "write_modes")},
        "dsp": {k: d["dsp"][k] for k in ("count", "opmodes", "buses", "cascade")},
    }


def idcode():
    m = re.search(r"^idcode\s*=\s*([0-9A-Fa-f]{8})", rd("hw/build.cfg"), re.M)
    need(m, "no idcode in hw/build.cfg")
    return "0x" + m.group(1).upper()


def ir_codes():
    src = rd("hw/src/core/jtag_tap6.v")
    codes = re.findall(r"localparam \[5:0\] IR_(\w+)\s*=\s*6'b([01]{6});", src)
    need(len(codes) >= 15, "IR codes not found in jtag_tap6.v")
    states = re.findall(r"localparam \[3:0\] (\w+)\s*=\s*4'd(\d+);", src)
    need(len(states) == 16, "TAP states not found")
    return [(n, c) for n, c in codes], [(n, int(v)) for n, v in states]


def frames_ctrl():
    src = rd("hw/src/core/cfg_frames.v")
    regs = re.findall(r"R_(\w+) = 5'd(\d+)", src)
    cmds = re.findall(r"C_(\w+) = 5'd(\d+)", src)
    sync = re.search(r"SYNC = 32'h([0-9A-F]+)", src).group(1)
    sts = re.findall(r"ST_(\w+) = 2'd(\d)", src)
    need(regs and cmds and sts, "cfg_frames.v constants not found")
    c = rd("hw/src/core/cfg_ctrl.v")
    poly = re.search(r"CRC_POLY\s*=\s*32'h([0-9A-F]+)", c).group(1)
    key = re.search(r"CTRL_KEY\s*=\s*8'h([0-9A-F]+)", c).group(1)
    return {"regs": [(n, int(v)) for n, v in regs], "cmds": [(n, int(v)) for n, v in cmds],
            "sync": "0x" + sync, "parser_states": [n for n, _ in sts],
            "crc_poly_reflected": "0x" + poly, "ctrl_key": "0x" + key}


def vivado():
    u = rd("docs/reports/M26/util.rpt")

    def row(name):
        m = re.search(r"^\|\s*" + re.escape(name) + r"\s*\|\s*([\d.]+)\s*\|.*?\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*$",
                      u, re.M)
        need(m, f"util.rpt: no row {name}")
        return {"used": float(m.group(1)), "avail": float(m.group(2)), "pct": float(m.group(3))}

    t = rd("docs/reports/M26/timing.rpt")
    m = re.search(r"WNS\(ns\).*?\n\s*-+.*?\n\s*([-\d.]+)\s+[-\d.]+\s+\d+\s+\d+\s+([-\d.]+)", t)
    need(m, "timing.rpt: no design timing summary")
    return {"luts": row("Slice LUTs"), "lutram": row("LUT as Memory"),
            "ffs": row("Slice Registers"), "slices": row("Slice"),
            "bram_tiles": row("Block RAM Tile"), "dsps": row("DSPs"),
            "wns_ns": float(m.group(1)), "whs_ns": float(m.group(2))}


def board_run():
    log = rd("docs/hwtest/results.log").splitlines()
    starts = [i for i, l in enumerate(log) if re.match(r"\S+ \S+\s+M26\s+tag=M26", l)]
    need(starts, "no M26 run in results.log")
    i = starts[-1]
    run = []
    for l in log[i + 1:]:
        if re.match(r"\d{4}-\d\d-\d\d ", l):
            break
        m = re.match(r"\s+(PASS|FAIL)\s+(\S+)", l)
        if m:
            run.append((m.group(1), m.group(2)))
    npass = sum(1 for s, _ in run if s == "PASS")
    return {"date": log[i].split()[0], "pass": npass, "total": len(run),
            "checks": [n for _, n in run]}


def counter():
    ex = {}
    ex["verilog"] = git_show("example/00_rtl/counter.v").rstrip("\n").splitlines()
    stat = git_show("example/01_synthesis/counter.stat")
    ex["cells"] = {m.group(2): int(m.group(1)) for m in re.finditer(r"^\s+(\d+)\s+(BOB_\w+|\$lut)\s*$", stat, re.M)}
    fasm = [l for l in git_show("example/06_fasm/counter.fasm").splitlines() if l.strip()]
    ex["fasm_lines"] = len(fasm)
    ex["fasm_sample"] = fasm[:8]
    ex["fasm_rr_sample"] = [l for l in fasm if l.startswith("rr")][:4]
    info = git_show("example/07_bitstream/bit_info.txt")
    ex["bit_crc"] = re.search(r"CRC (0x[0-9A-F]+)", info).group(1)
    ex["bit_cpd_ns"] = float(re.search(r"critical path ([\d.]+) ns", info).group(1))
    ex["bit_features"] = int(re.search(r"(\d+) configuration settings", info).group(1))
    hexd = git_show("example/07_bitstream/counter.bit.hexdump.txt")
    ex["bit_bytes"] = int(re.search(r"counter\.bit, (\d+) bytes", hexd).group(1))
    ex["bit_hex"] = [l for l in hexd.splitlines() if re.match(r"000000[0-3]0  ", l)][:3]
    sp = git_show("example/07_bitstream/stream_sparse.txt")
    m = re.search(r"(\d+) words, only the (\d+) frames", sp)
    ex["sparse_words"], ex["sparse_frames"] = int(m.group(1)), int(m.group(2))
    ex["sparse_head"] = [l for l in sp.splitlines() if re.match(r"[0-9A-F]{8}  ", l)][:16]
    summ = git_show("example/04_place_route/summary.txt")
    ex["vpr"] = {k: re.search(k + r"\s+([\d.]+)", summ).group(1)
                 for k in ("wirelength", "cpd_ns", "clbs", "pads")}
    route = git_show("example/05_layout/route_in_words.txt")
    blk = route.split("net btn[1]")[1].split("\n\n")[0].strip().splitlines()
    ex["route_btn1"] = [l.strip() for l in blk if l.strip() and not l.strip().startswith("...")][:6]
    ex["routes"] = {}
    for net in ("btn[1]", "led[0]"):
        body = route.split(f"net {net}\n")[1].split("\n\n")[0]
        hops = []
        for l in body.splitlines():
            if "next branch" in l:
                break
            m = re.match(r"\s*(\d+) (OPIN|IPIN|CHANX|CHANY)\s+\((\d+),(\d+)\)(?:->\((\d+),(\d+)\))?(?:.*?rr\d+ = (\d+))?", l)
            if m:
                g = m.groups()
                hops.append({"node": int(g[0]), "kind": g[1], "a": [int(g[2]), int(g[3])],
                             "b": [int(g[4]), int(g[5])] if g[4] else [int(g[2]), int(g[3])],
                             "sel": int(g[6]) if g[6] else None})
        ex["routes"][net] = hops
    tim = git_show("example/08_timing/timing_report.txt")
    ex["timing_path"] = [l.rstrip() for l in tim.splitlines() if re.match(r"\s+[\d.]+ ns  \(", l)]
    ex["delays"] = {m.group(1): float(m.group(2))
                    for m in re.finditer(r"^\s+(\w+)\s+([\d.]+) ns\s*$", tim, re.M)}
    need("mux_chan" in ex["delays"], "no delays in the counter timing report")
    return ex


def milestones():
    """The status table of docs/project/REPORT.md section 4: board result and host LUTs."""
    rep = rd("docs/project/REPORT.md")
    sec = rep.split("## 4. Timeline")[1].split("\n## ")[0]
    out = []
    for l in sec.splitlines():
        m = re.match(r"\| (M\d+\w?) \| (.*?) \| (.*?) \| (.*?) \|$", l)
        if not m:
            continue
        res = m.group(3)
        ok = re.search(r"(\d+)/(\d+)", res)
        lut = re.search(r"([\d ]{3,7}) LUT", res)
        out.append({"m": m.group(1), "what": m.group(2)[:160],
                    "pass": ok.group(0) if ok else None,
                    "luts": int(lut.group(1).replace(" ", "")) if lut else None,
                    "idcode": m.group(4).strip("` ")})
    need(len(out) >= 27, "milestone table not found in REPORT.md")
    return out


def verification():
    rep = rd("docs/project/REPORT.md")
    sims = rep.split("### 15.2")[1].split("### 15.3")[0]
    benches = []
    for m in re.finditer(r"^\| `(\w+)`([^|]*)\| ([\d ]+(?:\+ [\d ]+)?) \| (.*?) \|$", sims, re.M):
        n = sum(int(x.replace(" ", "")) for x in m.group(3).split("+"))
        g2 = m.group(2).replace("(49 CLBs)", "").strip()
        benches.append({"bench": m.group(1) + (" " + g2 if g2 else ""), "checks": n,
                        "what": m.group(4)[:90]})
    muts = rep.split("### 15.3")[1].split("### 15.4")[0]
    suites = [{"suite": m.group(1), "mutants": int(m.group(2))}
              for m in re.finditer(r"^\| `(mutate_\w+\.sh)` \| (\d+) \|", muts, re.M)]
    need(len(benches) >= 8 and len(suites) == 3, "verification tables not found in REPORT.md")
    return {"benches": benches, "mutants": suites, "sim_source": "REPORT.md 15.2 (last make check on M21)"}


def main():
    F = device()
    F["idcode"] = idcode()
    F["ir"], F["tap_states"] = ir_codes()
    F["frames_ctrl"] = frames_ctrl()
    F["vivado"] = vivado()
    F["board"] = board_run()
    F["counter"] = counter()
    F["milestones"] = milestones()
    F["verification"] = verification()
    F["example_rev"] = EXAMPLE_REV
    need(F["count"]["clb"] == 100, "expected the 10 x 10 grid")
    out = os.path.join(HERE, "data", "facts.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as fh:
        json.dump(F, fh, indent=1)
    print(f"wrote {os.path.relpath(out, REPO)}: {F['count']['clb']} CLBs, "
          f"{F['chain_width']} bits in {F['frames']['count']} frames, IDCODE {F['idcode']}, "
          f"board {F['board']['pass']}/{F['board']['total']}, "
          f"{F['rr']['muxes']} routing muxes, {F['element_bits']} bits per element")


if __name__ == "__main__":
    main()
