// hw/tb/cfg_vectors.vh - GENERATED by sim/gen_cfg_vectors.py, do not edit.
// CRCs from software/bob/chainbits.py (CRC-32C, docs/bitstream-format.md s5).

`define STARTUP_WORD 64'h5fd2af93a10b263d
`define STARTUP_CRC  32'h921eda0c

    vec_key_guard(64'ha1e7216044a98846, 32'h3644f666);
    vec_good(64'h0000000000000000, 32'h8c28b28a);
    vec_good(64'hffffffffffffffff, 32'h48674bc7);
    vec_good(64'haaaaaaaaaaaaaaaa, 32'hf7063153);
    vec_good(64'h0000000000000001, 32'hc514cfad);
    vec_good(64'h8000000000000000, 32'h0ede89f2);
    vec_good(64'h53657c95b88584f4, 32'h5620a113);
    vec_good(64'hc45583269784a322, 32'h6fef211a);
    vec_good(64'hf1ebd8668ec544d3, 32'h39f919bf);
    vec_good(64'h001fdca4b080a763, 32'hcfe81772);
    vec_good(64'hbdaf5a30d7021887, 32'ha5994f88);
    vec_good(64'he88e9b0dcbde6ead, 32'hf3e49c79);
    vec_corrupt(64'hc43890caa4a5b095, 32'h8ab747c0);   // bit 0 flipped
    vec_corrupt(64'h907186b599569c0a, 32'h49a15114);   // bit 63 flipped
    vec_corrupt(64'h0a4e84dacbf81a18, 32'h40b37f33);   // bit 46 flipped
    vec_corrupt(64'h5562f538776392a6, 32'h6c74a09c);   // bit 59 flipped
    vec_len(64'hc1e71fd8c9338d3d, 32'hc845c41f, 32'hae1e09c0);
    vec_hold(64'h34af9886112d87c3, 32'h5f9ba8a2);
