// -----------------------------------------------------------------------------
// tb_synth.v - synthesised designs on the complete bob FPGA RTL (M8)
//
// For each example in examples/: yosys (tools/bob/synth.py) -> placed and routed
// (tools/bob/place.py) -> this testbench loads the chain through the configuration
// plane, writes BRAM contents over USER4, starts it, and steps the user clock
// with USER1 step. After every step the LEDs must equal the SOURCE Verilog's
// (tools/bob/equiv.py trace): once before the edge, once after.
//
// hw/tb/synth_vectors.vh is generated by sim/gen_synth_vectors.py.
//   sim/run_synth_sim.sh
// -----------------------------------------------------------------------------

`timescale 1ns / 1ps
`default_nettype none
`include "bob_params.vh"

module tb_synth;

    `include "bob_harness.vh"

    // apply inputs, compare before the edge, one user clock, compare after it
    // (not 'before'/'after': SystemVerilog keywords)
    task syn_vec(input [5:0] pi, input [2:0] exp_pre, input [2:0] exp_post);
        begin
            pad_i = pi;
            #20;
            checks = checks + 1;
            if (pad_o !== exp_pre) begin
                errors = errors + 1;
                $display("  FAIL  %0s: pad_i=%b before edge LD2..0=%b, source %b", dname, pi, pad_o, exp_pre);
            end
            write_user1(32'h8);
            write_user1(32'h0);
            #20;
            checks = checks + 1;
            if (pad_o !== exp_post) begin
                errors = errors + 1;
                $display("  FAIL  %0s: pad_i=%b after edge LD2..0=%b, source %b", dname, pi, pad_o, exp_post);
            end else
                dchecks = dchecks + 1;
        end
    endtask

    task finish_design;
        $display("  PASS  %0s   (%0d clocks, LEDs == source before and after each)", dname, dchecks);
    endtask

    `include "synth_vectors.vh"

    initial begin
        $display("");
        $display("=== synthesised designs on the complete bob FPGA (M8 hand-placed, M9 VPR) ===");
        tick(1'b1, 1'b0); tick(1'b1, 1'b0); tick(1'b1, 1'b0); tick(1'b1, 1'b0); tick(1'b1, 1'b0);
        tick(1'b0, 1'b0);
        run_synth;
        $display("");
        $display("    %0d checks", checks);
        if (errors == 0) $display("=== ALL TESTS PASSED ===");
        else             $display("=== %0d CHECK(S) FAILED ===", errors);
        if (errors != 0) $fatal(1);
        $finish;
    end

endmodule

`default_nettype wire
