"""
Bitstream generation for the 4x4 CLB fabric.

Every constant, field offset and pad position here is loaded from
tools/bob/device.json, generated by tools/bob/device.py - the single source of
truth. Set BOB_DEVICE_JSON to use another description (the K=4 tests do).
tests/test_device.py checks the description against hw/src/clb/clb_pkg.sv, and
sim/gen_vectors.py + the fabric testbench keep this engine honest against the RTL.

  Chain = ctrl tile (clock mode + divider) + 16 fabric tiles
  Tile  = CLB(2**K + 7) + connection box((K+2) muxes) + switch box(16 muxes)
          K=6: 71 + 40 + 80 = 191 bits; chain 8 + 16*191 = 3064 bits

Routing model
-------------
Every mux in a tile chooses from the same 20-entry source bus:

    0        const 0
    1        const 1
    2        this tile's CLB o
    3        this tile's CLB o5
    4..7     tracks arriving from the North
    8..11    tracks arriving from the East
    12..15   tracks arriving from the South
    16..19   tracks arriving from the West

The connection box has K LUT-input muxes plus the flip-flop's CE and SR muxes
(M4, UG474: CE/SR are routable). Tracks are point to point. Driving tile T's
switch box output in direction D on track t makes that signal arrive at T's
neighbour in direction D, on the opposite side, same track number:

    drive out_N[t]  ->  neighbour (r+1, c) sees it on in_S[t]
    drive out_E[t]  ->  neighbour (r, c+1) sees it on in_W[t]
    drive out_S[t]  ->  neighbour (r-1, c) sees it on in_N[t]
    drive out_W[t]  ->  neighbour (r, c-1) sees it on in_E[t]

The router is a breadth-first search over tiles, allocating one switch box mux
per hop. A mux already carrying the same signal is free to traverse again,
which is how fanout works without any special case.
"""

# --- architecture, loaded from tools/bob/device.json ------------------------

import json
import os

_DEVICE_JSON = os.environ.get("BOB_DEVICE_JSON") or os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "tools", "bob", "device.json")
with open(_DEVICE_JSON) as _fh:
    DEVICE = json.load(_fh)

_CLB = DEVICE["tile_types"]["clb"]
_CTRL = DEVICE["tile_types"]["ctrl"]
FIELD = {f["name"]: (f["offset"], f["width"]) for f in _CLB["fields"]}
CTRL_FIELD = {f["name"]: (f["offset"], f["width"]) for f in _CTRL["fields"]}


def _group(g):
    fs = [f for f in _CLB["fields"] if f["group"] == g]
    return min(f["offset"] for f in fs), sum(f["width"] for f in fs)


LUT_K = DEVICE["lut_k"]
LUT_INIT_W = 1 << LUT_K
NTRACK = DEVICE["routing"]["ntrack"]
GRID_R = DEVICE["grid"]["rows"]
GRID_C = DEVICE["grid"]["cols"]
SOURCES = DEVICE["routing"]["sources"]
NSRC = len(SOURCES)                              # 20
SELW = DEVICE["routing"]["selw"]                 # 5
_SRC = {name: i for i, name in enumerate(SOURCES)}

SRC_C0, SRC_C1 = _SRC["const0"], _SRC["const1"]
SRC_CLB_O, SRC_CLB_O5 = _SRC["clb_o"], _SRC["clb_o5"]
DIR_N, DIR_E, DIR_S, DIR_W = 0, 1, 2, 3
DIR_NAME = {DIR_N: "N", DIR_E: "E", DIR_S: "S", DIR_W: "W"}
DIR_OF_NAME = {v: k for k, v in DIR_NAME.items()}


def src_n(t): return _SRC[f"N{t}"]
def src_e(t): return _SRC[f"E{t}"]
def src_s(t): return _SRC[f"S{t}"]
def src_w(t): return _SRC[f"W{t}"]


SRC_OF_DIR = {DIR_N: src_n, DIR_E: src_e, DIR_S: src_s, DIR_W: src_w}
OPPOSITE = {DIR_N: DIR_S, DIR_S: DIR_N, DIR_E: DIR_W, DIR_W: DIR_E}
DELTA = {DIR_N: (1, 0), DIR_E: (0, 1), DIR_S: (-1, 0), DIR_W: (0, -1)}

TILE_CLB_LO, CLB_CFG_W = _group("clb")           # 0, 71  (K=6)
TILE_CB_LO, CB_CFG_W = _group("cb")              # 71, 40
TILE_SB_LO, SB_CFG_W = _group("sb")              # 111, 80
TILE_CFG_W = _CLB["width"]                       # 191

CLB_INIT_LO = FIELD["init"][0] - TILE_CLB_LO
CLB_FF_EN = FIELD["ff_en"][0] - TILE_CLB_LO
CLB_FF_RSTVAL = FIELD["ff_rstval"][0] - TILE_CLB_LO
CLB_FF_CE_EN = FIELD["ff_ce_en"][0] - TILE_CLB_LO
CLB_FF_SR_EN = FIELD["ff_sr_en"][0] - TILE_CLB_LO
CLB_CY_EN = FIELD["cy_en"][0] - TILE_CLB_LO
CLB_CY_DI_SEL = FIELD["cy_di_sel"][0] - TILE_CLB_LO
CLB_FF_D_SEL = FIELD["ff_d_sel"][0] - TILE_CLB_LO

NTILE = GRID_R * GRID_C
FABRIC_CFG_W = DEVICE["chain"]["width"]          # the WHOLE chain (3064 for K=6)
TILE_LO = {(t["row"], t["col"]): t["chain_lo"] for t in DEVICE["tiles"] if t["type"] == "clb"}
CTRL_LO = next(t["chain_lo"] for t in DEVICE["tiles"] if t["type"] == "ctrl")
CLOCK_MODES = DEVICE["clock"]["modes"]           # {"jtag": 0, "run": 1}
DIV_MIN_SHIFT = DEVICE["clock"]["div_min_shift"]
SYSCLK_HZ = DEVICE["clock"]["sysclk_hz"]

PAD_IN = {p["pad"]: p for p in DEVICE["pads"]["inputs"]}
PAD_OUT = {p["pad"]: p for p in DEVICE["pads"]["outputs"]}
EDGE_PAD = {(p["edge"], p["track"]): k for k, p in PAD_IN.items()}

FLAG_NAMES = ("ff_en", "ff_rstval", "ff_ce_en", "ff_sr_en", "cy_en", "cy_di_sel", "ff_d_sel")

# --- M5: the BRAM tile on the East edge ---------------------------------------
_BRAM_T = DEVICE["tile_types"]["bram"]
BRAM_FIELD = {f["name"]: (f["offset"], f["width"]) for f in _BRAM_T["fields"]}
BRAM_LO = next(t["chain_lo"] for t in DEVICE["tiles"] if t["type"] == "bram")
BRAM = DEVICE["bram"]
BRAM_PINS = BRAM["port_pins"]                    # addr0..9, di0..17, we, en, rst, regce
BRAM_WRITE_MODES = BRAM["write_modes"]
BRAM_SRC_JTAG = BRAM["pin_sources"].index("jtag")
BRAM_SRC_TRK0 = BRAM["pin_sources"].index("trk0")
BRAM_OUT_DOA0 = BRAM["out_sources"].index("doa0")
BRAM_OUT_DOB0 = BRAM["out_sources"].index("dob0")
N_EDGE = GRID_R * NTRACK                         # East edge tracks, index r*NTRACK + t

# --- M6: the DSP tile on the North edge ---------------------------------------
_DSP_T = DEVICE["tile_types"]["dsp"]
DSP_FIELD = {f["name"]: (f["offset"], f["width"]) for f in _DSP_T["fields"]}
DSP_LO = next(t["chain_lo"] for t in DEVICE["tiles"] if t["type"] == "dsp")
DSP = DEVICE["dsp"]
DSP_OPMODES = DSP["opmodes"]
DSP_BUS_SOURCES = DSP["bus_sources"]
DSP_CTRL_NAMES = DSP["ctrl_names"]
DSP_SRC_JTAG = DSP["ctrl_sources"].index("jtag")
DSP_SRC_TRK0 = DSP["ctrl_sources"].index("trk0")
DSP_OUT_P0 = DSP["out_sources"].index("p0_0")
DSP_OUT_P1 = DSP["out_sources"].index("p1_0")
N_NORTH = GRID_C * NTRACK                        # North edge tracks, index c*NTRACK + t


# --- LUT INIT builders -----------------------------------------------------

def lut(fn, nin=None):
    """Build a 2**K-bit INIT by evaluating fn(i0, i1, ...) over every address."""
    nin = LUT_K if nin is None else nin
    if nin > LUT_K:
        raise ValueError(f"a {nin}-input function does not fit a LUT{LUT_K}")
    init = 0
    for a in range(LUT_INIT_W):
        bits = [(a >> k) & 1 for k in range(LUT_K)]
        if fn(*bits[:nin]):
            init |= 1 << a
    return init


class LUT:
    @staticmethod
    def const0():  return 0
    @staticmethod
    def const1():  return (1 << LUT_INIT_W) - 1
    @staticmethod
    def buf(k=0):  return lut(lambda *b: b[k])
    @staticmethod
    def inv(k=0):  return lut(lambda *b: not b[k])
    @staticmethod
    def and2():    return lut(lambda a, b: a & b, 2)
    @staticmethod
    def or2():     return lut(lambda a, b: a | b, 2)
    @staticmethod
    def xor2():    return lut(lambda a, b: a ^ b, 2)
    @staticmethod
    def nand2():   return lut(lambda a, b: not (a & b), 2)
    @staticmethod
    def nor2():    return lut(lambda a, b: not (a | b), 2)
    @staticmethod
    def xnor2():   return lut(lambda a, b: not (a ^ b), 2)
    @staticmethod
    def and3():    return lut(lambda a, b, c: a & b & c, 3)
    @staticmethod
    def mux2():    return lut(lambda a, b, s: b if s else a, 3)
    @staticmethod
    def maj3():    return lut(lambda a, b, c: (a & b) | (b & c) | (a & c), 3)
    @staticmethod
    def and6():    return lut(lambda *b: all(b), 6)
    @staticmethod
    def xor6():    return lut(lambda *b: sum(b) & 1, 6)


# --- signals ---------------------------------------------------------------

class Signal:
    """Something a mux can be pointed at."""


class Const(Signal):
    def __init__(self, v): self.v = v
    def __repr__(self): return f"const{self.v}"


class Pad(Signal):
    """An input pad. pad_i[0..3] arrive on every row's West edge, tracks 0..3;
    pad_i[4] and pad_i[5] arrive on every column's South edge, tracks 0 and 1."""
    def __init__(self, k):
        if k not in PAD_IN:
            raise ValueError(f"input pads are pad_i[0..{len(PAD_IN) - 1}]")
        self.k = k
    def __repr__(self): return f"pad_i[{self.k}]"


class Cell(Signal):
    """A tile's CLB output. which is 'o' (the main output) or 'o5' (fracture)."""
    def __init__(self, r, c, which="o"):
        self.r, self.c, self.which = r, c, which
    @property
    def tile(self): return (self.r, self.c)
    def __repr__(self): return f"tile({self.r},{self.c}).{self.which}"


class BramOut(Signal):
    """A BRAM output bit (M5): port 'a' or 'b', bit 0..17. It enters the fabric
    on an East edge track the build allocates."""
    def __init__(self, port, bit):
        if port not in ("a", "b") or not 0 <= bit < BRAM["data_w"]:
            raise ValueError("BRAM outputs are do_a / do_b [0..17]")
        self.port, self.bit = port, bit
    def __repr__(self): return f"bram.do_{self.port}[{self.bit}]"


class DspOut(Signal):
    """A DSP output bit (M6): slice 0 or 1, P bit 0..47. It enters the fabric on a
    North edge track the build allocates."""
    def __init__(self, s, bit):
        if s not in (0, 1) or not 0 <= bit < 48:
            raise ValueError("DSP outputs are P0 / P1 [0..47]")
        self.s, self.bit = s, bit
    def __repr__(self): return f"dsp.p{self.s}[{self.bit}]"


class RouteError(Exception):
    pass


# --- the bitstream ---------------------------------------------------------

class Bitstream:
    """The raw chain word, with named accessors. No routing here."""

    def __init__(self):
        self.bits = bytearray(FABRIC_CFG_W)

    def _base(self, r, c):
        if not (0 <= r < GRID_R and 0 <= c < GRID_C):
            raise ValueError(f"tile ({r},{c}) is outside the {GRID_R}x{GRID_C} grid")
        return TILE_LO[(r, c)]

    def _put(self, lo, width, value):
        for b in range(width):
            self.bits[lo + b] = (value >> b) & 1

    def _get(self, lo, width):
        v = 0
        for b in range(width):
            v |= self.bits[lo + b] << b
        return v

    # --- ctrl tile: the user clock ---
    def set_ctrl(self, clk_mode=0, clk_div=0):
        lo, w = CTRL_FIELD["clk_mode"]
        self._put(CTRL_LO + lo, w, clk_mode)
        lo, w = CTRL_FIELD["clk_div"]
        if not 0 <= clk_div < (1 << w):
            raise ValueError(f"clk_div is {w} bits")
        self._put(CTRL_LO + lo, w, clk_div)

    def get_ctrl(self, name):
        lo, w = CTRL_FIELD[name]
        return self._get(CTRL_LO + lo, w)

    # --- BRAM tile ---
    def set_bram(self, name, value):
        lo, w = BRAM_FIELD[name]
        if not 0 <= value < (1 << w):
            raise ValueError(f"bram.{name} is {w} bits")
        self._put(BRAM_LO + lo, w, value)

    def get_bram(self, name):
        lo, w = BRAM_FIELD[name]
        return self._get(BRAM_LO + lo, w)

    # --- DSP tile ---
    def set_dsp(self, name, value):
        lo, w = DSP_FIELD[name]
        if not 0 <= value < (1 << w):
            raise ValueError(f"dsp.{name} is {w} bits")
        self._put(DSP_LO + lo, w, value)

    def get_dsp(self, name):
        lo, w = DSP_FIELD[name]
        return self._get(DSP_LO + lo, w)

    # --- CLB ---
    def set_field(self, r, c, name, value):
        lo, w = FIELD[name]
        self._put(self._base(r, c) + lo, w, value)

    def get_field(self, r, c, name):
        lo, w = FIELD[name]
        return self._get(self._base(r, c) + lo, w)

    def set_lut(self, r, c, init):
        self.set_field(r, c, "init", init)

    def set_clb_flags(self, r, c, ff_en=0, ff_rstval=0, ff_ce_en=0,
                      ff_sr_en=0, cy_en=0, cy_di_sel=0, ff_d_sel=0):
        for name, v in (("ff_en", ff_en), ("ff_rstval", ff_rstval),
                        ("ff_ce_en", ff_ce_en), ("ff_sr_en", ff_sr_en),
                        ("cy_en", cy_en), ("cy_di_sel", cy_di_sel),
                        ("ff_d_sel", ff_d_sel)):
            self.set_field(r, c, name, 1 if v else 0)

    # --- connection box: LUT input k, CE, SR <- source code ---
    def set_cb(self, r, c, k, src):
        if not 0 <= k < LUT_K:
            raise ValueError(f"a LUT{LUT_K} has inputs i[0..{LUT_K - 1}]")
        self.set_field(r, c, f"cb_i{k}", src)

    def get_cb(self, r, c, k):
        return self.get_field(r, c, f"cb_i{k}")

    def set_ce(self, r, c, src):
        self.set_field(r, c, "cb_ce", src)

    def set_sr(self, r, c, src):
        self.set_field(r, c, "cb_sr", src)

    # --- switch box: outgoing (dir, track) <- source code ---
    def set_sb(self, r, c, d, t, src):
        self.set_field(r, c, f"sb_{DIR_NAME[d]}{t}", src)

    def get_sb(self, r, c, d, t):
        return self.get_field(r, c, f"sb_{DIR_NAME[d]}{t}")

    # --- output ---
    def to_int(self):
        v = 0
        for i, b in enumerate(self.bits):
            if b:
                v |= 1 << i
        return v

    def to_hex(self):
        return f"{self.to_int():0{(FABRIC_CFG_W + 3) // 4}x}"

    def __len__(self):
        return FABRIC_CFG_W


# --- placement and routing -------------------------------------------------

class Design:
    """Place LUTs on tiles, name their inputs, and let the router wire it up."""

    def __init__(self):
        self.bs = Bitstream()
        self.cells = {}          # (r,c) -> dict(init, flags, inputs, ce, sr)
        self.outputs = {}        # pad index -> Signal
        self.sb_owner = {}       # (r,c,d,t) -> signal key, for reuse and conflicts
        self.clock = ("jtag", 0)
        # M5 BRAM
        self.bram_modes = {"a": ("WRITE_FIRST", False), "b": ("WRITE_FIRST", False)}
        self.bram_pins = {}      # (port, pin) -> Signal or "jtag"
        self.bram_out_slot = {}  # (port, bit) -> East edge track index carrying it
        self.bram_in_track = {}  # signal key -> East edge track index feeding BRAM pins
        # M6 DSP
        self.dsp_cfgs = {0: {}, 1: {}}
        self.dsp_ctrls = {}      # (slice, name) -> Signal / Const / "jtag"
        self.dsp_tracks = {}     # North track k -> Signal (bit k of every 'fabric' bus)
        self.dsp_out_slot = {}   # (slice, bit) -> North edge track index carrying it
        self.dsp_in_track = {}   # signal key -> North track feeding a DSP control
        self._built = False

    # --- description ---

    def input(self, k):
        return Pad(k)

    def const(self, v):
        return Const(1 if v else 0)

    def set_clock(self, mode="jtag", div=0):
        """The user clock: 'jtag' (one step per TCK edge while USER1 ce) or
        'run' (free-running, an enable every 2**(div+DIV_MIN_SHIFT) sysclk cycles)."""
        if mode not in CLOCK_MODES:
            raise ValueError(f"clock mode is one of {sorted(CLOCK_MODES)}")
        self.clock = (mode, div)

    def lut(self, r, c, init, inputs=(), ce=None, sr=None, **flags):
        """Place a LUT at tile (r,c). `inputs` maps positionally to i[0], i[1]...
        `ce` / `sr` are Signals routed to the flip-flop's CE and SR (defaults:
        CE = const1, SR = const0); they matter only with ff_ce_en / ff_sr_en."""
        if (r, c) in self.cells:
            raise ValueError(f"tile ({r},{c}) already holds a LUT")
        if len(inputs) > LUT_K:
            raise ValueError(f"a LUT{LUT_K} has at most {LUT_K} inputs")
        self.cells[(r, c)] = {"init": init, "inputs": list(inputs), "flags": flags,
                              "ce": ce, "sr": sr}
        return Cell(r, c, "o")

    def output(self, k, signal):
        """Drive pad_o[k]. pad_o[k] is row k's East edge, track 0."""
        if k not in PAD_OUT:
            raise ValueError(f"output pads are pad_o[0..{len(PAD_OUT) - 1}]")
        self.outputs[k] = signal

    # --- M5: the BRAM tile ---

    def bram_mode(self, port, write_mode="WRITE_FIRST", out_reg=False):
        if write_mode not in BRAM_WRITE_MODES:
            raise ValueError(f"write mode is one of {sorted(BRAM_WRITE_MODES)}")
        self.bram_modes[port] = (write_mode, bool(out_reg))

    def bram_pin(self, port, pin, source):
        """Connect BRAM port 'a'/'b' pin (addr0..9, di0..17, we, en, rst, regce)
        to a Signal (routed through the fabric to the East edge) or "jtag"."""
        if port not in ("a", "b") or pin not in BRAM_PINS:
            raise ValueError(f"no BRAM pin {port}.{pin}")
        self.bram_pins[(port, pin)] = source

    def bram_out(self, port, bit):
        return BramOut(port, bit)

    # --- M6: the DSP tile ---

    def dsp_config(self, s, opmode="M", use_d=False, d_sub=False, areg=0, breg=0, creg=0,
                   dreg=0, mreg=0, preg=0, bus_a="const0", bus_b="const0", bus_c="const0",
                   bus_d="const0"):
        if opmode not in DSP_OPMODES:
            raise ValueError(f"opmode is one of {sorted(DSP_OPMODES)}")
        for bus in (bus_a, bus_b, bus_c, bus_d):
            if bus not in DSP_BUS_SOURCES:
                raise ValueError(f"bus source is one of {sorted(DSP_BUS_SOURCES)}")
        self.dsp_cfgs[s] = {"opmode": DSP_OPMODES[opmode], "use_d": int(use_d), "d_sub": int(d_sub),
                            "areg": int(areg), "breg": int(breg), "creg": int(creg), "dreg": int(dreg),
                            "mreg": int(mreg), "preg": int(preg),
                            "bus_a": DSP_BUS_SOURCES[bus_a], "bus_b": DSP_BUS_SOURCES[bus_b],
                            "bus_c": DSP_BUS_SOURCES[bus_c], "bus_d": DSP_BUS_SOURCES[bus_d]}

    def dsp_track(self, k, signal):
        """Put `signal` on North edge track k: bit k of every DSP bus whose source is 'fabric'."""
        if not 0 <= k < N_NORTH:
            raise ValueError(f"North edge tracks are 0..{N_NORTH - 1}")
        self.dsp_tracks[k] = signal

    def dsp_ctrl(self, s, name, source):
        if s not in (0, 1) or name not in DSP_CTRL_NAMES:
            raise ValueError(f"no DSP control s{s}.{name}")
        self.dsp_ctrls[(s, name)] = source

    def dsp_out(self, s, bit):
        return DspOut(s, bit)

    def _dsp_out_track(self, sig):
        key = (sig.s, sig.bit)
        if key not in self.dsp_out_slot:
            used = set(self.dsp_out_slot.values())
            free = [k for k in range(N_NORTH) if k not in used]
            if not free:
                raise RouteError("all 16 DSP output tracks are in use")
            self.dsp_out_slot[key] = free[0]
            self.bs.set_dsp(f"out{free[0]}", (DSP_OUT_P0 if sig.s == 0 else DSP_OUT_P1) + sig.bit)
        return self.dsp_out_slot[key]

    def _to_north(self, k, sig):
        c, t = divmod(k, NTRACK)
        self.bs.set_sb(GRID_R - 1, c, DIR_N, t, self._reach(sig, (GRID_R - 1, c)))
        self.sb_owner[(GRID_R - 1, c, DIR_N, t)] = self._key(sig)

    def _bram_out_track(self, sig):
        key = (sig.port, sig.bit)
        if key not in self.bram_out_slot:
            used = set(self.bram_out_slot.values())
            free = [k for k in range(N_EDGE) if k not in used]
            if not free:
                raise RouteError("all 16 BRAM output tracks are in use")
            self.bram_out_slot[key] = free[0]
            base = BRAM_OUT_DOA0 if sig.port == "a" else BRAM_OUT_DOB0
            self.bs.set_bram(f"out{free[0]}", base + sig.bit)
        return self.bram_out_slot[key]

    # --- routing internals ---

    @staticmethod
    def _key(sig):
        if isinstance(sig, Const):
            return ("const", sig.v)
        if isinstance(sig, Pad):
            return ("pad", sig.k)
        if isinstance(sig, BramOut):
            return ("bram", sig.port, sig.bit)
        if isinstance(sig, DspOut):
            return ("dsp", sig.s, sig.bit)
        return ("cell", sig.r, sig.c, sig.which)

    def _sources_at(self, sig):
        """Tiles where `sig` is natively visible, and the source code there."""
        out = {}
        if isinstance(sig, Cell):
            code = SRC_CLB_O if sig.which == "o" else SRC_CLB_O5
            out[(sig.r, sig.c)] = code
        elif isinstance(sig, BramOut):                 # arrives from the East
            r, t = divmod(self._bram_out_track(sig), NTRACK)
            out[(r, GRID_C - 1)] = src_e(t)
        elif isinstance(sig, DspOut):                  # arrives from the North
            c, t = divmod(self._dsp_out_track(sig), NTRACK)
            out[(GRID_R - 1, c)] = src_n(t)
        elif isinstance(sig, Pad):
            p = PAD_IN[sig.k]
            if p["edge"] == "W":                 # West edge of every row
                for r in range(GRID_R):
                    out[(r, 0)] = src_w(p["track"])
            elif p["edge"] == "S":               # South edge of every column
                for c in range(GRID_C):
                    out[(0, c)] = src_s(p["track"])
            else:
                raise ValueError(f"pad edge {p['edge']} not supported by this router")
        return out

    def _bfs(self, sig, dest):
        """Shortest route making `sig` visible at tile `dest`.

        Returns (source_code_at_dest, [(r,c,dir,track), ...] hops to program).
        Traversing a switch box mux already carrying this signal is free, which
        is what lets one signal fan out to several sinks.
        """
        key = self._key(sig)
        starts = self._sources_at(sig)
        if dest in starts:
            return starts[dest], []

        from collections import deque
        q = deque((t, code, []) for t, code in starts.items())
        seen = set(starts)
        while q:
            (r, c), code, path = q.popleft()
            for d in (DIR_E, DIR_N, DIR_S, DIR_W):
                dr, dc = DELTA[d]
                nr, nc = r + dr, c + dc
                if not (0 <= nr < GRID_R and 0 <= nc < GRID_C):
                    continue
                for t in range(NTRACK):
                    owner = self.sb_owner.get((r, c, d, t))
                    if owner is not None and owner != key:
                        continue                       # track taken by another net
                    ncode = SRC_OF_DIR[OPPOSITE[d]](t)
                    npath = path + [(r, c, d, t, code)]
                    if (nr, nc) == dest:
                        return ncode, npath
                    if (nr, nc) in seen:
                        continue
                    seen.add((nr, nc))
                    q.append(((nr, nc), ncode, npath))
        raise RouteError(f"no route for {sig} to tile {dest}")

    def _commit(self, sig, hops):
        key = self._key(sig)
        for (r, c, d, t, code) in hops:
            self.bs.set_sb(r, c, d, t, code)
            self.sb_owner[(r, c, d, t)] = key

    def _reach(self, sig, dest):
        """Make sig visible at dest, programming switch boxes as needed."""
        if isinstance(sig, Const):
            return SRC_C1 if sig.v else SRC_C0
        code, hops = self._bfs(sig, dest)
        self._commit(sig, hops)
        return code

    # --- build ---

    def build(self):
        if self._built:
            raise RuntimeError("build() is single-shot; make a new Design")

        mode, div = self.clock
        self.bs.set_ctrl(CLOCK_MODES[mode], div)

        # LUTs first, so every cell exists before anything routes to it.
        for (r, c), spec in self.cells.items():
            self.bs.set_lut(r, c, spec["init"])
            self.bs.set_clb_flags(r, c, **spec["flags"])

        # Unused LUT inputs sit on const0; CE defaults to const1 (always
        # enabled), SR to const0 (never reset).
        for (r, c), spec in self.cells.items():
            for k in range(LUT_K):
                self.bs.set_cb(r, c, k, SRC_C0)
            for k, sig in enumerate(spec["inputs"]):
                self.bs.set_cb(r, c, k, self._reach(sig, (r, c)))
            self.bs.set_ce(r, c, SRC_C1 if spec["ce"] is None else self._reach(spec["ce"], (r, c)))
            self.bs.set_sr(r, c, SRC_C0 if spec["sr"] is None else self._reach(spec["sr"], (r, c)))

        # M5: BRAM modes and pins. A routed pin gets an East edge track of its
        # own (the output-pad tracks are reserved); one track per distinct signal.
        for port in "ab":
            mode, reg = self.bram_modes[port]
            self.bs.set_bram(f"wmode_{port}", BRAM_WRITE_MODES[mode])
            self.bs.set_bram(f"reg_{port}", int(reg))
        pad_tracks = {p["row"] * NTRACK + p["track"] for p in PAD_OUT.values()}
        for (port, pin), sig in self.bram_pins.items():
            if sig == "jtag":
                code = BRAM_SRC_JTAG
            elif isinstance(sig, Const):
                code = sig.v
            else:
                key = self._key(sig)
                if key not in self.bram_in_track:
                    used = set(self.bram_in_track.values()) | pad_tracks
                    free = [k for k in range(N_EDGE) if k not in used]
                    if not free:
                        raise RouteError("no free East edge track for another BRAM input")
                    r, t = divmod(free[0], NTRACK)
                    dest = (r, GRID_C - 1)
                    self.bs.set_sb(r, GRID_C - 1, DIR_E, t, self._reach(sig, dest))
                    self.sb_owner[(r, GRID_C - 1, DIR_E, t)] = key
                    self.bram_in_track[key] = free[0]
                code = BRAM_SRC_TRK0 + self.bram_in_track[key]
            self.bs.set_bram(f"{port}_{pin}", code)

        # M6: DSP configuration, fabric bus bits on fixed North tracks, then
        # controls on any remaining North track (one per distinct signal).
        for s in (0, 1):
            for name, v in self.dsp_cfgs[s].items():
                self.bs.set_dsp(f"s{s}_{name}", v)
        for k, sig in self.dsp_tracks.items():
            self._to_north(k, sig)
        for (s, name), sig in self.dsp_ctrls.items():
            if sig == "jtag":
                code = DSP_SRC_JTAG
            elif isinstance(sig, Const):
                code = sig.v
            else:
                key = self._key(sig)
                if key not in self.dsp_in_track:
                    used = set(self.dsp_in_track.values()) | set(self.dsp_tracks)
                    free = [k for k in range(N_NORTH) if k not in used]
                    if not free:
                        raise RouteError("no free North edge track for another DSP control")
                    self._to_north(free[0], sig)
                    self.dsp_in_track[key] = free[0]
                code = DSP_SRC_TRK0 + self.dsp_in_track[key]
            self.bs.set_dsp(f"s{s}_{name}", code)

        # Output pads: pad_o[k] is tile (k,3)'s East edge, track 0.
        for k, sig in self.outputs.items():
            p = PAD_OUT[k]
            dest = (p["row"], p["col"])
            d, t = DIR_OF_NAME[p["dir"]], p["track"]
            code = self._reach(sig, dest)
            self.bs.set_sb(dest[0], dest[1], d, t, code)
            self.sb_owner[(dest[0], dest[1], d, t)] = self._key(sig)

        self._built = True
        return self.bs

    # --- introspection ---

    def report(self):
        mode, div = self.clock
        lines = [f"design: {len(self.cells)} LUT(s), "
                 f"{len(self.sb_owner)} switch-box mux(es) used, clock {mode}"
                 + (f" div {div}" if mode == "run" else "")]
        for (r, c), spec in sorted(self.cells.items()):
            ins = ", ".join(f"i{k}={s}" for k, s in enumerate(spec["inputs"]))
            extra = "".join(f", {n}={spec[n]}" for n in ("ce", "sr") if spec[n] is not None)
            lines.append(f"  tile({r},{c})  INIT=0x{spec['init']:0{(LUT_INIT_W + 3) // 4}X}  "
                         f"{ins}{extra}")
        for (r, c, d, t), key in sorted(self.sb_owner.items()):
            lines.append(f"  route tile({r},{c}) -{DIR_NAME[d]}{t}->  {key}")
        for k, sig in sorted(self.outputs.items()):
            lines.append(f"  pad_o[{k}] <- {sig}")
        return "\n".join(lines)


# --- a software model, for checking a bitstream without hardware -----------

def simulate(bs, pad_i, cin=0, max_iter=256):
    """Evaluate the fabric for one input vector and return pad_o as a 3-bit int.

    Combinational only - flip-flops are not modelled here (tools/bob/model.py
    does that), so build designs without FF_EN to use this. The carry chain is
    modelled.

    Evaluation is an iterative fixed point over every CLB output and every
    track, rather than a recursive walk: the mesh has cycles by construction.
    """
    o = [0] * NTILE
    o5 = [0] * NTILE
    trk = {(r, c, d, t): 0
           for r in range(GRID_R) for c in range(GRID_C)
           for d in range(4) for t in range(NTRACK)}

    def in_track(r, c, d, t):
        """The value arriving at tile (r,c) from direction d on track t."""
        if d == DIR_N:
            return trk[(r + 1, c, DIR_S, t)] if r + 1 < GRID_R else 0
        if d == DIR_E:
            return trk[(r, c + 1, DIR_W, t)] if c + 1 < GRID_C else 0
        if d == DIR_S:
            if r - 1 >= 0:
                return trk[(r - 1, c, DIR_N, t)]
            k = EDGE_PAD.get(("S", t))                          # South edge pads
            return (pad_i >> k) & 1 if k is not None else 0
        if c - 1 >= 0:
            return trk[(r, c - 1, DIR_E, t)]
        k = EDGE_PAD.get(("W", t))                              # West edge pads
        return (pad_i >> k) & 1 if k is not None else 0

    def sources(r, c):
        idx = r * GRID_C + c
        s = [0] * NSRC
        s[SRC_C1] = 1
        s[SRC_CLB_O] = o[idx]
        s[SRC_CLB_O5] = o5[idx]
        for t in range(NTRACK):
            s[src_n(t)] = in_track(r, c, DIR_N, t)
            s[src_e(t)] = in_track(r, c, DIR_E, t)
            s[src_s(t)] = in_track(r, c, DIR_S, t)
            s[src_w(t)] = in_track(r, c, DIR_W, t)
        return s

    def pick(s, sel):
        return s[sel] if sel < NSRC else 0

    carry = {}
    o5_mask = (1 << (LUT_K - 1)) - 1

    for _ in range(max_iter):
        changed = False
        for r in range(GRID_R):
            for c in range(GRID_C):
                idx = r * GRID_C + c
                s = sources(r, c)

                i = 0
                for k in range(LUT_K):
                    i |= pick(s, bs.get_cb(r, c, k)) << k

                init = bs.get_field(r, c, "init")
                if bs.get_field(r, c, "ff_en"):
                    raise ValueError("simulate() models combinational designs only "
                                     f"(tile ({r},{c}) has FF_EN set) - use tools/bob/model.py")
                cy_en = bs.get_field(r, c, "cy_en")
                cy_di_sel = bs.get_field(r, c, "cy_di_sel")
                d_sel = bs.get_field(r, c, "ff_d_sel")

                lut_o6 = (init >> i) & 1
                lut_o5 = (init >> (i & o5_mask)) & 1

                c_in = cin if r == 0 else carry.get((r - 1, c), 0)
                di = lut_o5 if cy_di_sel else (i & 1)
                comb = (lut_o6 ^ c_in) if cy_en else (lut_o5 if d_sel else lut_o6)
                c_out = (c_in if lut_o6 else di) if cy_en else 0

                if carry.get((r, c)) != c_out:
                    carry[(r, c)] = c_out
                    changed = True
                if o[idx] != comb or o5[idx] != lut_o5:
                    o[idx], o5[idx] = comb, lut_o5
                    changed = True

                for d in range(4):
                    for t in range(NTRACK):
                        v = pick(s, bs.get_sb(r, c, d, t))
                        if trk[(r, c, d, t)] != v:
                            trk[(r, c, d, t)] = v
                            changed = True
        if not changed:
            break
    else:
        raise ValueError("fabric did not settle - combinational loop in the design")

    return sum(trk[(p["row"], p["col"], DIR_OF_NAME[p["dir"]], p["track"])] << k
               for k, p in PAD_OUT.items())
