#!/usr/bin/env python3
"""
Generate hw/tb/vectors.vh for hw/tb/tb_bob.v from host/designs.py,
host/bitstream.py, tools/bob/model.py and tools/bob/chainbits.py.

Each design is built and routed by the real bitstream engine; expected outputs
come from tools/bob/model.py (which evaluates the same routing-resource graph
the fabric RTL was generated from) - never from the Verilog. Every chain carries
its CRC-32C and is loaded through the configuration plane (JPROGRAM, expected
CRC, CFG_IN, JSTART), exactly as host/cfgplane.py does.

M7 adds random routed netlists: random LUTs and flip-flops placed across the
grid with random routed connections, stepped one clock at a time, every CLB
output and every LED compared with the model after every clock.

  ./gen_vectors.py [--out FILE]      honours BOB_DEVICE_JSON (K=4 runs)
"""

import argparse
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "host"))
sys.path.insert(0, os.path.join(HERE, "..", "tools", "bob"))

import bitstream as B                                                    # noqa: E402
from bitstream import FABRIC_CFG_W, LUT_K, Cell, Design, RouteError      # noqa: E402
from chainbits import crc32c_bits                                        # noqa: E402
from designs import (DESIGNS, BY_KEY, SKIPPED, BRAM_JTAG_VARIANTS, DSP_JTAG_VARIANTS,  # noqa: E402
                     COUNTER_X, PIPELINE_BRAM, d_gsr_probe, d_ce_sr, d_counter, d_bram_rom,
                     d_bram_jtag, d_dsp_jtag, d_dsp_mult_sw, d_dsp_accum, d_pipeline)
import model                                                             # noqa: E402

W = FABRIC_CFG_W
NCLB = B.NCLB
CE_SR_STEPS = (0b00, 0b01, 0b11, 0b01, 0b00, 0b10, 0b01, 0b00)
RANDOM_DESIGNS = 4
RANDOM_STEPS = 24


def hexw(v):
    return f"{W}'h{v:0{(W + 3) // 4}x}"


def crc(v):
    return f"32'h{crc32c_bits(v, W):08x}"


def define(name, word):
    return [f"`define {name}_WORD {hexw(word)}", f"`define {name}_CRC {crc(word)}"]


def q_expr(cells):
    """{dut.clb_o[i_n-1], ..., dut.clb_o[i_0]} for CLB coordinates, first = bit 0."""
    return "{" + ", ".join(f"dut.clb_o[{B.CLB_XY_INDEX[xy]}]" for xy in reversed(cells)) + "}"


def loop_free_random_chain(rng):
    """Random block fields; every routing mux const0 or out of range (reads 0), so
    committing it cannot build a combinational loop - a fully random chain can,
    and a zero-delay oscillation hangs the simulator (it did at M4)."""
    word = rng.getrandbits(W)
    for _node, (lo, w, base, ins) in B.MUX.items():
        lim = base + len(ins)
        val = rng.randrange(lim, 1 << w) if lim < (1 << w) else 0
        word = (word & ~(((1 << w) - 1) << lo)) | (val << lo)
    return word


def random_design(rng, ncells=14):
    """Random LUTs/FFs anywhere on the grid, connections without combinational
    loops: a LUT reads board inputs, constants, any flip-flop, or the
    combinational output of a LUT placed before it."""
    while True:
        d = Design()
        spots = rng.sample(sorted(B.CLB_AT), ncells)
        reg = {xy: rng.random() < 0.5 for xy in spots}
        for i, (x, y) in enumerate(spots):
            cands = [d.input(k) for k in range(6)] + [d.const(rng.randrange(2))]
            cands += [Cell(*xy) for xy in spots if reg[xy]]
            cands += [Cell(*xy, rng.choice(("o", "o5"))) for xy in spots[:i] if not reg[xy]]
            cands += [Cell(*xy, "o5") for xy in spots[:i] if reg[xy]]
            nin = rng.randrange(1, LUT_K + 1)
            ins = [rng.choice(cands) for _ in range(nin)]
            flags = {}
            ce = sr = None
            if reg[(x, y)]:
                flags = {"ff_en": 1, "ff_rstval": rng.randrange(2), "ff_d_sel": rng.randrange(2),
                         "ff_ce_en": int(rng.random() < 0.5), "ff_sr_en": int(rng.random() < 0.3)}
                if flags["ff_ce_en"]:
                    ce = rng.choice(cands)
                if flags["ff_sr_en"]:
                    sr = rng.choice(cands)
            elif rng.random() < 0.3:
                flags = {"ff_d_sel": 1}
            d.lut(x, y, rng.getrandbits(1 << LUT_K), ins, ce=ce, sr=sr, **flags)
        for k in range(3):
            d.output(k, Cell(*rng.choice(spots), rng.choice(("o", "o5"))))
        try:
            return d, d.build()
        except RouteError:
            continue


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.normpath(
        os.path.join(HERE, "..", "hw", "tb", "vectors.vh")))
    args = ap.parse_args()

    out = [
        "// hw/tb/vectors.vh - GENERATED by sim/gen_vectors.py, do not edit.",
        "//",
        f"// LUT K = {LUT_K}, chain {W} bits, {NCLB} CLBs. Bitstreams routed by host/bitstream.py,",
        "// expected values from tools/bob/model.py, CRCs from tools/bob/chainbits.py.",
        "",
    ]

    show_bs = BY_KEY["showcase"][1]().build()
    ce_sr_bs = d_ce_sr().build()
    cntj_bs = d_counter("jtag").build()
    cntr_bs = d_counter("run", 0).build()
    other = BY_KEY["three"][1]().build().to_int()

    out += define("RT", loop_free_random_chain(random.Random(0xF00D)))
    out += ["// one registered CLB, INIT 1, D 0 (designs.d_gsr_probe)"]
    out += define("GSR", d_gsr_probe().build().to_int())
    out += ["// showcase, and a corrupted 'three' chain carrying its true CRC"]
    out += define("SHOW", show_bs.to_int())
    out += [f"`define BAD_WORD {hexw(other ^ (1 << 1234))}", f"`define BAD_CRC {crc(other)}"]
    out += [f"`define SHOW_CAP_11 {NCLB}'h{model.Fabric(show_bs).clb_o(0b11):x}"
            "   // every CLB output with SW1=SW0=1"]
    out += ["// M4: routed CE/SR; 4-bit carry-chain counter, JTAG-stepped and free-running"]
    out += define("CE_SR", ce_sr_bs.to_int())
    out += define("CNTJ", cntj_bs.to_int())
    out += define("CNTR", cntr_bs.to_int())
    out += [f"`define CNT_Q {q_expr([(COUNTER_X, 1 + r) for r in range(4)])}"]
    out += ["// M7: an 8-bit counter up the full height of column 8 (seven carry directs)"]
    out += define("CNT8", d_counter("jtag", x=8, bits=8).build().to_int())
    out += [f"`define CNT8_Q {q_expr([(8, 1 + r) for r in range(8)])}"]
    out.append("")

    # --- combinational designs ---------------------------------------------------------
    out += ["task run_designs;", "begin"]
    total = 0
    for key, desc, fn, sweep in DESIGNS:
        bs = fn().build()
        word = bs.to_int()
        m = model.Fabric(bs)
        out.append(f"    // ---- {key}: {desc}")
        out.append(f'    dname  = "{key}: {desc}";')
        out.append(f"    cfgw   = {hexw(word)};")
        out.append(f"    cfgcrc = {crc(word)};")
        out.append("    load_config;")
        for v in sweep:
            out.append(f"    check_vec(6'b{v:06b}, 3'b{m.outputs(v):03b});")
            total += 1
        out.append("    finish_design;")
        out.append("")
    m = model.Fabric(show_bs)
    out += ["end", "endtask", "", "task check_showcase;", "begin"]
    for v in BY_KEY["showcase"][2]:
        out.append(f"    check_vec(6'b{v:06b}, 3'b{m.outputs(v):03b});")
    out += ["end", "endtask", ""]

    # --- routed CE/SR sequence ---------------------------------------------------------
    m = model.Fabric(ce_sr_bs)
    m.clock(gsr=1)
    out += ["task run_ce_sr;", "begin"]
    for v in CE_SR_STEPS:
        for _ in range(4):
            m.clock(pad_i=v)
        out.append(f"    ce_sr_step(6'b{v:06b}, 3'b{m.outputs(v):03b});")
    out += ["end", "endtask", ""]

    m = model.Fabric(ce_sr_bs)
    m.clock(gsr=1)
    out += ["task run_ce_sr_intest;", "begin"]
    for v in (0b00, 0b01, 0b11, 0b01, 0b00, 0b10, 0b01):
        m.clock(pad_i=v)
        out.append(f"    intest_step(6'b{v:06b}, 1'b{m.outputs(v) & 1});")
        m.clock(pad_i=v)
    out += ["end", "endtask", ""]

    # --- counter sequence -----------------------------------------------------------------
    m = model.Fabric(cntj_bs)
    m.clock(gsr=1)
    out += ["task init_cnt_seq;", "begin"]
    for n in range(16):
        state = sum(m.q[(COUNTER_X, 1 + r)] << r for r in range(4))
        out.append(f"    cnt_state[{n}] = 4'b{state:04b}; cnt_pad[{n}] = 3'b{m.outputs(0, cin=1):03b};")
        m.clock(cin=1)
    out += ["end", "endtask", ""]

    # --- M5: BRAM ROM through the fabric -------------------------------------------------
    rng_b = random.Random(0xB5)
    rom_bs = d_bram_rom().build()
    rom_words = [rng_b.getrandbits(18) for _ in range(4)]
    out += define("ROM", rom_bs.to_int())
    out += [f"`define ROM{i} 18'h{w:05x}" for i, w in enumerate(rom_words)]
    m = model.Fabric(rom_bs)
    m.clock(gsr=1)
    for i, w in enumerate(rom_words):
        m.bram.mem[i] = w
    out += ["task rom_check;", "begin"]
    for v in range(4):
        for _ in range(3):
            m.clock(pad_i=v)
        out.append(f"    rom_vec(6'b{v:06b}, 3'b{m.outputs(v):03b});")
    out += ["end", "endtask", ""]

    # --- M5: BRAM write modes / output registers, pins driven over JTAG -------------------
    idle = {"addr": 0, "di": 0, "we": 0, "en": 0, "rst": 0, "regce": 0}
    bm = None
    for name, v in BRAM_JTAG_VARIANTS:
        bs = d_bram_jtag(**v).build()
        out += define(name, bs.to_int())
        cfg = {"wmode_a": model.WRITE_MODES[v["wmode_a"]], "wmode_b": model.WRITE_MODES[v["wmode_b"]],
               "reg_a": int(v["reg_a"]), "reg_b": int(v["reg_b"])}
        mem = bm.mem if bm else [0] * 1024
        bm = model.Bram()
        bm.mem = list(mem)
        bm.clock(cfg, {"a": idle, "b": idle}, gsr=1)
        out += [f"task {name.lower()}_run;", "begin"]
        for addr in range(8):
            w = rng_b.getrandbits(18)
            bm.init(True, addr, w)
            out.append(f"    bram_poke(10'd{addr}, 18'h{w:05x});")
        out.append("    jstart;")
        for a, b in model.bram_random_ops(rng_b, 24):
            bm.clock(cfg, {"a": a, "b": b}, gce=1)
            out.append(f"    bram_op(64'h{model.pins_to_drive(a, b):016x}, "
                       f"18'h{bm.do('a', cfg):05x}, 18'h{bm.do('b', cfg):05x});")
        out += ["end", "endtask", ""]
    out += [f"`define BRAM0_MEM0 18'h{bm.mem[0]:05x}   // bram0 mem[0] after the JT runs"]

    # --- M6: DSP ----------------------------------------------------------------------------
    M48 = (1 << 48) - 1
    zero = {"a": 0, "b": 0, "c": 0, "d": 0, **{n: 0 for n in model.DSP_CTRL_NAMES}}
    rng_d = random.Random(0xD6)
    for name, c0, c1 in DSP_JTAG_VARIANTS:
        bs = d_dsp_jtag(c0, c1).build()
        out += define(name, bs.to_int())
        cfgs = model.Fabric(bs).dsp_cfgs
        slices = [model.Dsp(), model.Dsp()]
        out += [f"task {name.lower()}_run;", "begin", "    jstart;"]
        for p0, p1 in model.dsp_random_ops(rng_d, 20):
            model.dsp_cascade_clock(slices, cfgs, (p0, p1))
            e0, e1 = model.dsp_cascade_p(slices, cfgs, (p0, p1))
            out.append(f"    dsp_op(248'h{model.dsp_pins_to_drive(p0, p1):062x}, "
                       f"48'h{e0 & M48:012x}, 48'h{e1 & M48:012x});")
        out += ["end", "endtask", ""]

    mult_bs = d_dsp_mult_sw().build()
    out += define("MULT", mult_bs.to_int())
    fm = model.Fabric(mult_bs)
    fm.dsp_drive = model.dsp_pins_to_drive({**zero, "b": 3}, zero)
    out.append(f"`define MULT_DRIVE 248'h{fm.dsp_drive:062x}")
    out += ["task mult_check;", "begin"]
    for v in range(4):
        out.append(f"    mult_vec(6'b{v:06b}, 3'b{fm.outputs(v):03b});")
    out += ["end", "endtask", ""]

    out += define("ACC", d_dsp_accum(0).build().to_int())
    out.append(f"`define ACC_DRIVE 248'h{model.dsp_pins_to_drive({**zero, 'a': 1, 'b': 1}, zero):062x}")
    out.append("")

    # --- M7: pad -> LUT -> FF -> BRAM -> DSP -> pad ------------------------------------------
    rng_p = random.Random(0x77)
    pipe_bs = d_pipeline("run", 0).build()
    pipe_words = [rng_p.getrandbits(18) for _ in range(4)]
    out += define("PIPE", pipe_bs.to_int())
    out.append(f"`define PIPE_BRAM 4'd{PIPELINE_BRAM}")
    out += [f"`define PIPE{i} 18'h{w:05x}" for i, w in enumerate(pipe_words)]
    m = model.Fabric(pipe_bs)
    m.clock(gsr=1)
    for i, w in enumerate(pipe_words):
        m.brams[PIPELINE_BRAM].mem[i] = w
    out += ["task pipe_check;", "begin"]
    for v in (0, 1, 2, 3, 2, 0):
        for _ in range(4):
            m.clock(pad_i=v)
        out.append(f"    pipe_vec(6'b{v:06b}, 3'b{m.outputs(v):03b});")
    out += ["end", "endtask", ""]

    # --- M7: random routed netlists, one clock per step ---------------------------------------
    rng_r = random.Random(0x5EED)
    out += ["task run_random;", "begin"]
    for n in range(RANDOM_DESIGNS):
        d, bs = random_design(rng_r)
        word = bs.to_int()
        wires = sum(len(r) - 1 for r in d.routes.values())
        out.append(f'    dname  = "random netlist {n}: {len(d.cells)} CLBs, {len(d.routes)} nets, {wires} wires";')
        out.append(f"    cfgw   = {hexw(word)};")
        out.append(f"    cfgcrc = {crc(word)};")
        out.append("    load_config;")
        out.append("    dchecks = 0;")
        m = model.Fabric(bs)
        m.clock(gsr=1)
        for _ in range(RANDOM_STEPS):
            v = rng_r.randrange(64)
            m.clock(pad_i=v)
            out.append(f"    rnd_step(6'b{v:06b}, {NCLB}'h{m.clb_o(v):x}, 3'b{m.outputs(v):03b});")
        out.append("    finish_design;")
    out += ["end", "endtask", ""]

    with open(args.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {args.out}")
    print(f"  {len(DESIGNS)} designs, {total} vectors, {RANDOM_DESIGNS} random netlists x "
          f"{RANDOM_STEPS} clocks, {W} bits each, with CRC-32C"
          + (f"  (skipped at K={LUT_K}: {', '.join(SKIPPED)})" if SKIPPED else ""))


if __name__ == "__main__":
    main()
